---
title: "IFPH InFORM Join"
author: "Spencer Fiden"
date: "2026-05-29"
output: html_document
---

# Creating grid for oregon

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
library(ggplot2)
library(sf)
```

```{r}
landmark <- st_read("/Users/nikolefiden/Desktop/DATA-510/Indigenous_comm_lands_v202509/LandMark_IPLC_poly_public_v202509.shp")
us_lm <- landmark %>% filter(iso_code == "USA")
us_lm <- st_zm(us_lm)
us_lm <- st_transform(us_lm, crs="WGS84")
us_lm <- st_make_valid(us_lm)
```

## OR

```{r}
states <- usmap::us_map()
or <- states %>% filter(abbr=="OR")
# transforming OR so the coordinate system matches
or <- st_transform(or, crs="WGS84")

or %>% 
    ggplot() +
    geom_sf() + 
    theme_minimal()
```

## Create grid

```{r}
or_grid_square <- st_make_grid(or, cellsize=0.05)
plot(or_grid_square)
plot(st_geometry(or), add=TRUE)
plot(or_grid_square[or], col="#ff000088", add=TRUE)
```

## add names/identifier to each grid cell

```{r}
head(or_grid_square)
or_grid = or_grid_square[or]
length(or_grid_square)
length(or_grid)
```

```{r}
index = seq(1, length(or_grid), 1)
index_tib = tibble(index)

or_grid_df <- cbind(or_grid, index_tib)

```

# Add landmark data

```{r}
sf_use_s2(FALSE)
lm_int = st_intersects(or, us_lm)
dim(lm_int)

or_lm = us_lm[unlist(lm_int),]
dim(or_lm)
```

```{r}
indigenous <- st_intersects(or_grid, or_lm, sparse=FALSE)
indigenous_tibble <- tibble(indigenous)

or_grid_df <- cbind(or_grid_df, indigenous_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("indigenous"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        is_indigenous = ifelse(rowSums(across(starts_with("indigenous"))) == 0, 0, 1)
    )

or_grid_df <- or_grid_df %>% select(-indigenous)

lengths(or_grid_df)

```

# Add IFPH and InFORM data

```{r}
fire_shp <- st_read("data/fire_shp.shp")

```

## locked in. adding fire identifier

```{r}
head(or_grid)

# fire tibble with whether each fire occurred in each grid cell
fire <- st_intersects(or_grid, fire_shp, sparse=FALSE)
fire_tibble <- tibble(fire)
head(fire_tibble)
dim(fire_tibble)
dim(fire_tibble$fire)

# combining fire_tibble and or_grid_df to get counts of fires
or_grid_df <- cbind(or_grid_df, fire_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("fire"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_fires = rowSums(across(starts_with("fire")))
    )

# removing the interim fire columns (they are mostly false and mostly meaningless)
or_grid_df <- or_grid_df %>% select(-fire)

head(or_grid_df %>%
    arrange(desc(n_fires))
)
# max number of fires: 8

# getting grid index as list
grid_index <- or_grid_df$index

# new tibble that doesn't have a matrix
fire_tibble2 = cbind(tibble(data.frame(fire)), grid_index)

# for every grid index and fire, shows the unique fire identifier (unique_id) and whether that fire was in that grid cell (is_fire)
long_fire <- fire_tibble2 %>%
    pivot_longer(!grid_index, names_to="fire_index", values_to="is_fire") %>%
    mutate(fire_index = as.numeric(str_remove(fire_index, "X"))) %>%
    mutate(
        unique_id = fire_shp$UNQE_FI[fire_index],
        acres = fire_shp$GIS_ACR[fire_index],
        fire_management_n = fire_shp$fr_mgm_[fire_index],
        duration_hrs = fire_shp$fr_df__[fire_index]
    )

# confirming the order didn't shift around for some reason - it did not!
(long_fire %>% pull(unique_id))[1:100] == (fire_shp %>% pull(UNQE_FI))[1:100]

# creating new limited id column that has unique identifier if fire is present in that square, otherwise NA
# same for acres, fire_management_n, duration_hrs
# then pivoting so the unique ID shows in grid index col where the fire is present
wide_fire <- long_fire %>%
    # mutating unique ID to "missing" if NA and adding the constructed fire_index for referencing
    mutate(unique_id = ifelse(is.na(unique_id), paste("MISSING", as.symbol(fire_index)), unique_id)) %>%
    mutate(
        limited_uid = ifelse(is_fire==TRUE, unique_id, NA)
    ) %>%
    pivot_wider(names_from = grid_index, values_from = limited_uid)

head(wide_fire)



# creating new tibble with grid index
fire_lst_tibble <- tibble(grid_index)
fire_lst_tibble[,"fire_lst"]=""
fire_lst_tibble[,"max_acres"]=""
fire_lst_tibble[,"min_mgmt"]=""
fire_lst_tibble[,"max_duration"]=""
head(fire_lst_tibble,5)

# for every grid cell, pulling unique fire identifiers for fires that occurred in that cell, adding them to fire_lst_tibble
for (x in 1:dim(or_grid_df)[1]) {
    full_lst <- pull(wide_fire, x+6)
    fire_idx <- which(!is.na(full_lst))
    lst <- full_lst[!is.na(full_lst)]
    #print(lst)
    if (length(lst) == 0) {
        fire_lst_tibble$fire_lst[x] = NA
        fire_lst_tibble$max_acres[x] = NA
        fire_lst_tibble$min_mgmt[x] = NA
        fire_lst_tibble$max_duration[x] = NA
    } else {
        fire_lst_tibble$fire_lst[x] = paste(unlist(lst), collapse=", ")
        fire_lst_tibble$max_acres[x] = max(wide_fire$acres[fire_idx])
        fire_lst_tibble$min_mgmt[x] = min(wide_fire$fire_management_n[fire_idx])
        fire_lst_tibble$max_duration[x] = max(wide_fire$duration_hrs[fire_idx])
    }
}

# checking everything accurate
ex8 <- pull(wide_fire, `8`)
ex8_idx <- which(!is.na(ex8))
max(wide_fire$duration_hrs[ex8_idx])
ex8 <- ex8[!is.na(ex8)]
ex8
head(fire_lst_tibble,8)

ex8 == fire_lst_tibble$fire_lst[8]
```

```{r}
or_grid_tib <- tibble(left_join(or_grid_df, fire_lst_tibble, by=c("index"="grid_index")))

or_grid_tib
```

```{r}
# visualization? n_fires per square?
library(viridis)

or_grid_tib %>%
    mutate(is_indigenous = as_factor(is_indigenous)) %>%
    ggplot(aes(geometry=geometry, fill=n_fires, color=is_indigenous)) +
    geom_sf(linewidth=0.1) +
    scale_fill_viridis_c(option="inferno") +
    scale_colour_discrete(palette=c("gray", "black")) +
    theme_void()

```

```{r}
or_grid_tib %>%
    group_by(is_indigenous) %>%
    summarize(n=n())
```

```{r}
gbif <- read_csv("data/new_gbif_dataset.csv")
```

```{r}
gbif_sf <- st_as_sf(gbif, coords=c("decimalLongitude", "decimalLatitude"), crs="WGS84")
gbif_sf <- gbif_sf %>% select(-`...1`)
```

```{r}
str(gbif_sf)

gbif_sf %>%
    mutate(
        species = as_factor(species),
        eventDate = ifelse(str_starts(eventDate, "20"), ymd_hms(eventDate, truncated=3), mdy_hms(eventDate, truncated=3)),
        #eventDate = ifelse(is.Date(eventDate), eventDate, as_datetime(eventDate)),
        basisOfRecord = as_factor(basisOfRecord),
        license = as_factor(license)
    ) %>%
    arrange(eventDate)

gbif_sf <- gbif_sf %>%
    mutate(
        species = as_factor(species),
        eventDate = ifelse(str_starts(eventDate, "20"), ymd_hms(eventDate, truncated=3), mdy_hms(eventDate, truncated=3)),
        basisOfRecord = as_factor(basisOfRecord),
        license = as_factor(license)
    ) 

```

```{r}
unique(gbif_sf$species)

qg_gbif <- gbif_sf %>%
    filter(species == "Quercus garryana")

xt_gbif <- gbif_sf %>%
    filter(species == "Xerophyllum tenax")

tp_gbif <- gbif_sf %>%
    filter(species == "Thuja plicata")

pt_gbif <- gbif_sf %>%
    filter(species == "Populus trichocarpa")

ru_gbif <- gbif_sf %>%
    filter(species == "Rubus ursinus")

pp_gbif <- gbif_sf %>%
    filter(species == "Pinus ponderosa")

ss_gbif <- gbif_sf %>%
    filter(species == "Salix scouleriana")

qg_con <- st_contains(or_grid, qg_gbif, sparse=FALSE)
qg_tibble <- tibble(qg_con)

xt_con <- st_contains(or_grid, xt_gbif, sparse=FALSE)
xt_tibble <- tibble(xt_con)

tp_con <- st_contains(or_grid, tp_gbif, sparse=FALSE)
tp_tibble <- tibble(tp_con)

pt_con <- st_contains(or_grid, pt_gbif, sparse=FALSE)
pt_tibble <- tibble(pt_con)

ru_con <- st_contains(or_grid, ru_gbif, sparse=FALSE)
ru_tibble <- tibble(ru_con)

pp_con <- st_contains(or_grid, pp_gbif, sparse=FALSE)
pp_tibble <- tibble(pp_con)

ss_con <- st_contains(or_grid, ss_gbif, sparse=FALSE)
ss_tibble <- tibble(ss_con)

head(qg_tibble)

# quercus garryana
or_grid_df <- cbind(or_grid_df, qg_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("qg_con"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_quercus = rowSums(across(starts_with("qg_con")))
    )

or_grid_df <- or_grid_df %>% select(-qg_con)

# xerophyllum tenax
or_grid_df <- cbind(or_grid_df, xt_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("xt_con"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_xerophyllum = rowSums(across(starts_with("xt_con")))
    )

or_grid_df <- or_grid_df %>% select(-xt_con)

# thuja plicata
or_grid_df <- cbind(or_grid_df, tp_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("tp_con"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_thuja = rowSums(across(starts_with("tp_con")))
    )

or_grid_df <- or_grid_df %>% select(-tp_con)

# populus trichocarpa
or_grid_df <- cbind(or_grid_df, pt_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("pt_con"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_populus = rowSums(across(starts_with("pt_con")))
    )

or_grid_df <- or_grid_df %>% select(-pt_con)

# rubus ursinus
or_grid_df <- cbind(or_grid_df, ru_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("ru_con"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_rubus = rowSums(across(starts_with("ru_con")))
    )

or_grid_df <- or_grid_df %>% select(-ru_con)

# pinus ponderosa
or_grid_df <- cbind(or_grid_df, pp_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("pp_con"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_pinus = rowSums(across(starts_with("pp_con")))
    )

or_grid_df <- or_grid_df %>% select(-pp_con)

# salix scouleriana
or_grid_df <- cbind(or_grid_df, ss_tibble)

or_grid_df <- or_grid_df %>%
    mutate(across(starts_with("ss_con"), ~ ifelse(.x==TRUE, 1, 0))) %>% 
    mutate(
        n_salix = rowSums(across(starts_with("ss_con")))
    )

or_grid_df <- or_grid_df %>% select(-ss_con)
```

```{r}
head(or_grid_df)
```


```{r}
full_grid_tib <- tibble(left_join(or_grid_df, fire_lst_tibble, by=c("index"="grid_index")))

```

```{r}
names(full_grid_tib)
full_grid_shp <- st_as_sf(full_grid_tib, crs="WGS84")

write_csv(full_grid_tib, "data/processed_grid.csv")
st_write(full_grid_shp, "data/processed_grid.shp", append=FALSE)
```