---
title: "Data cleaning"
author: "Spencer Fiden"
date: "2026-05-29"
output: html_document
---

# Ingestion from download

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
library(ggplot2)
library(sf)
```

```{r}
landmark <- st_read("/Users/nikolefiden/Desktop/DATA-510/Indigenous_comm_lands_v202509/LandMark_IPLC_poly_public_v202509.shp")

ifph <- st_read("/Users/nikolefiden/Desktop/DATA-510/InterAgencyFirePerimeterHistory_All_Years_View/InteragencyFirePerimeterHistory.shp")

inform <- read_csv("/Users/nikolefiden/Desktop/DATA-510/InFORM_FireOccurrence_Public.csv")

```

# Limiting to OR

Getting just OR from `usmap` to filter fires/native land to our area of interest with `st_intersects`. 

```{r}
states <- usmap::us_map()
or <- states %>% filter(abbr=="OR")
# transforming OR so the coordinate system matches
or <- st_transform(or, crs=st_crs(landmark))

or %>% 
    ggplot() +
    geom_sf() + 
    theme_minimal()
```

## LandMark for OR

```{r}
# issue with dimensions, removing z
landmark <- st_zm(landmark)
# limiting to just US first so it doesn't take as long to run
us_lm <- landmark %>% filter(iso_code == "USA")

lengths(us_lm)
head(us_lm)

# creating intersection list for all polygons that intersect with OR border
# then selecting only those polygons
lm_int = st_intersects(or, us_lm)
dim(lm_int)

or_lm = us_lm[unlist(lm_int),]
dim(or_lm)

or_lm %>% ggplot() + geom_sf()
lengths(or_lm)
```

## IFPH for OR
```{r}
lengths(ifph)

# creating intersection list for all polygons that intersect with OR border
# then selecting only those polygons
ifph_int = st_intersects(or, ifph)
dim(ifph_int)

or_ifph = ifph[unlist(ifph_int),]
dim(or_ifph)

or_ifph %>% 
    ggplot() + geom_sf()

lengths(or_ifph)
```

# Creating dataframes

```{r}
# creating dataframes for each
ifph_df <- as.data.frame(or_ifph)
lm_df <- as.data.frame(or_lm)
```

# IFPH

## IFPH data types
```{r}
str(ifph_df)

# IRWINID
length(unique(ifph_df$IRWINID))
summary(is.na(ifph_df$IRWINID)) # lot of NAs
head(ifph_df %>% filter(!is.na(IRWINID)) %>% select(IRWINID)) # those that aren't look like chr is correct

# FORID
length(unique(ifph_df$FORID))
summary(is.na(ifph_df$FORID)) # lot of NAs
head(ifph_df %>% filter(!is.na(FORID)) %>% select(FORID)) # those that aren't look like chr is correct

# INCIDENT
length(unique(ifph_df$INCIDENT))
summary(is.na(ifph_df$INCIDENT)) # some repeated names - not sure what's up with that, bears some investigations

# GIS_ACRES
summary(is.na(ifph_df$GIS_ACRES)) # no missing values
summary(ifph_df$GIS_ACRES)
length(ifph %>% filter(GIS_ACRES == 0)) # 19 fires that were 0 acres? likely just very small, maybe rounding error? 
ifph %>% filter(GIS_ACRES == 0) %>% ggplot() + geom_sf()
# leaving for now, we can revisit these

# UNQE_FIRE_
length(unique(ifph_df$UNQE_FIRE_))
summary(is.na(ifph_df$UNQE_FIRE_)) # a few missing, but shouldn't be a problem
head(ifph_df %>% filter(!is.na(UNQE_FIRE_)) %>% select(UNQE_FIRE_)) # looks good

# DATE_CUR
summary(is.na(ifph_df$DATE_CUR)) # no missing values
head(ifph_df %>% select(DATE_CUR)) # should not be chr

# FIRE_YEAR_
summary(is.na(ifph_df$FIRE_YEAR_)) # no missing values
summary(ifph_df$FIRE_YEAR_) # need to limit years

# UNIT_ID
length(unique(ifph_df$UNIT_ID))
summary(is.na(ifph_df$UNIT_ID)) # some missing
ifph_df %>%
    group_by(UNIT_ID) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# seems fine that it's like that

# POO_RESP_I
length(unique(ifph_df$POO_RESP_I))
summary(is.na(ifph_df$POO_RESP_I)) # some missing
ifph_df %>%
    group_by(POO_RESP_I) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# seems fine

# LOCAL_NUM
length(unique(ifph_df$LOCAL_NUM))
summary(is.na(ifph_df$LOCAL_NUM)) # some missing
ifph_df %>%
    group_by(LOCAL_NUM) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# not sure why there are so many 0? maybe should be NA, but not relevant to our analysis so I'll leave it

# FEATURE_CA
length(unique(ifph_df$FEATURE_CA))
summary(is.na(ifph_df$FEATURE_CA)) # some missing
ifph_df %>%
    group_by(FEATURE_CA) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# this should be a factor

# MAP_METHOD
length(unique(ifph_df$MAP_METHOD)) # 30 unique
summary(is.na(ifph_df$MAP_METHOD)) # some missing
ifph_df %>%
    mutate(MAP_METHOD = toupper(MAP_METHOD)) %>%
    group_by(MAP_METHOD) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# this should be a factor

# COMMENTS
length(unique(ifph_df$COMMENTS)) 
summary(is.na(ifph_df$COMMENTS))
ifph_df %>%
    group_by(COMMENTS) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# some repeated comments but it seems normal and fine

# GEO_ID
length(unique(ifph_df$GEO_ID))
summary(is.na(ifph_df$GEO_ID)) # none missing

# SOURCE
length(unique(ifph_df$SOURCE)) 
summary(is.na(ifph_df$SOURCE)) # none missing
ifph_df %>%
    group_by(SOURCE) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# should be a factor

# AGENCY
length(unique(ifph_df$AGENCY)) 
summary(is.na(ifph_df$AGENCY)) # none missing
ifph_df %>%
    group_by(AGENCY) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# should be a factor

# FIRE_YEAR
summary(is.na(ifph_df$FIRE_YEAR)) # none missing
ifph_df %>%
    mutate(FIRE_YEAR = as.integer(FIRE_YEAR)) %>%
    filter(FIRE_YEAR != FIRE_YEAR_) %>%
    count()
# FIRE_YEAR always = FIRE_YEAR_, can be removed

# GlobalID
# it bothers me that this one is not in all caps but whatever
length(unique(ifph_df$GlobalID))
summary(is.na(ifph_df$GlobalID)) # none missing, all unique

# last is geometry column which I will not be touching
```

## IFPH Cleaning

```{r}
# limiting FIRE_YEAR_ to 2015-2025 (inclusive)
ifph_df <- ifph_df %>%
    filter(FIRE_YEAR_ >= 2015, FIRE_YEAR_ <= 2025) 
    
ifph_df%>%
    select(FIRE_YEAR_) %>%
    summary()
```

```{r}
# converting INCIDENT = UNNAMED, UNKNOWN to NA
ifph_df %>%
    mutate(INCIDENT = toupper(INCIDENT)) %>%
    group_by(INCIDENT) %>%
    summarize(n = n()) %>%
    arrange(desc(n))

ifph_df <- ifph_df %>%
    mutate(INCIDENT = toupper(INCIDENT)) %>%
    mutate(INCIDENT = ifelse(INCIDENT %in% c("UNNAMED", "UNKNOWN"), NA, INCIDENT)) 

ifph_df %>%
    mutate(INCIDENT = toupper(INCIDENT)) %>%
    group_by(INCIDENT) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
```

```{r}
# converting DATE_CUR to actual datetime 
# not sure what the timezone is. but it probably doesn't matter for our purposes
ifph_df <- ifph_df %>%
    mutate(DATE_CUR = lubridate::ymd_hms(DATE_CUR))

# shows an error for the NAs that they "failed to parse" - it's fine
summary(is.na(ifph_df$DATE_CUR))
```

```{r}
# making FEATURE_CA into a factor
ifph_df <- ifph_df %>%
    mutate(FEATURE_CA = as_factor(FEATURE_CA)) 

```

```{r}
# cleaning MAP_METHOD and turning into factor
print(n=30, ifph_df %>%
    mutate(MAP_METHOD = toupper(MAP_METHOD)) %>%
    group_by(MAP_METHOD) %>%
    summarize(n = n()) %>%
    arrange(desc(n)))

ifph_df <- ifph_df %>%
    mutate(MAP_METHOD = ifelse(MAP_METHOD %in% c("Mixed Method", "Mixed Collection Methods"), "Mixed Methods", MAP_METHOD),
        MAP_METHOD = ifelse(MAP_METHOD == "Digitized Other", "Digitized-Other", MAP_METHOD)) %>%
    mutate(MAP_METHOD = as_factor(MAP_METHOD))

# there are others that could be grouped (or are just the same) but for our purposes I'm not going to 
```

```{r}
# making SOURCE into a factor
ifph_df <- ifph_df %>%
    mutate(SOURCE = as_factor(SOURCE)) 

```

```{r}
# making AGENCY into a factor
ifph_df <- ifph_df %>%
    mutate(AGENCY = as_factor(AGENCY)) 

```

```{r}
# removing FIRE_YEAR col
ifph_df <- ifph_df %>%
    select(-FIRE_YEAR)
```

# InFORM

## InFORM Data Types

```{r}
# replacing spaces in col names with "." (i want it to be nothing or _ but alas. this function exists already)
inform <- inform %>% dplyr::rename_all(funs(make.names(.)))

```

```{r}
str(inform)
class(inform)
dim(inform)
# hey what's a spec_tbl_df. what is all of this. huh
names(inform) # that's a lot of columns. that's a LOT of columns
summary(inform)

head(inform %>% arrange(desc(`Calendar.Year`)) %>% select(`Calendar.Year`))
# one year marked as 2121 - probably actually 2021, but I feel like I should flag it somehow
# for now it will just be removed in the limiting to 2015-2026
```

``` {r}
# OBJECTID
class(inform$OBJECTID) # numeric
length(unique(inform$OBJECTID)) # all unique
summary(is.na(inform$OBJECTID)) # none missing

# ABCD.Misc
class(inform$ABCD.Misc)
summary(is.na(inform$ABCD.Misc)) # LOT of missing values
length(unique(inform$ABCD.Misc)) 
head(inform %>%
    group_by(ABCD.Misc) %>%
    summarize(n = n()) %>%
    arrange(desc(n)))
# 682 unique, a LOT of NAs, seems fine

# ADS Permission States
class(inform$ADS.Permission.State)
summary(is.na(inform$ADS.Permission.State)) # no missing values
length(unique(inform$ADS.Permission.State))
inform %>% 
    group_by(ADS.Permission.State) %>% 
    summarize(n=n())
# should be a factor

# Calculated.Acres
class(inform$Calculated.Acres) # numeric
summary(inform$Calculated.Acres) # no missing values
summary(is.na(inform$Calculated.Acres))
head(inform %>%
    group_by(Calculated.Acres) %>%
    summarize(n=n()) %>%
    arrange(Calculated.Acres))
# apparently one fire burned -1 acres. I dont think that's right and perhaps we should just remove that one

# Containment.Date.Time
class(inform$Containment.Date.Time) # character
head(inform %>% select(Containment.Date.Time)) # looks like a date/time
summary(is.na(inform$Containment.Date.Time)) # MANY missing values

# Control.Date.Time
class(inform$Control.Date.Time) # character
summary(is.na(inform$Control.Date.Time)) # many missing values
head(inform %>% select(Control.Date.Time)) # also looks like a date/time

# Created.By.System
class(inform$Created.By.System)
length(unique(inform$Created.By.System))
inform %>% 
    #mutate(Created.By.System = toupper(Created.By.System)) %>%
    group_by(Created.By.System) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should be a factor

# Created.On.Date.Time
class(inform$Created.On.Date.Time) # numeric??? ok
head(inform$Created.On.Date.Time) # is this like the posix thing? i will try lubridate
summary(is.na(inform$Created.On.Date.Time)) # none missing
length(unique(inform$Created.On.Date.Time)) # mostly unique, good

# Incident.Size
class(inform$Incident.Size) # numeric
summary(is.na(inform$Incident.Size)) # decent number of NA
summary(inform$Incident.Size)

# Discovery.Acres
class(inform$Discovery.Acres) # logical?
summary(inform$Discovery.Acres) # all. missing. hm. 
# not sure what to do about this?

# Dispatch.Center.ID
class(inform$Dispatch.Center.ID) # char
summary(is.na(inform$Dispatch.Center.ID)) # about split NA
head(inform$Dispatch.Center.ID)
length(unique(inform$Dispatch.Center.ID)) # only 241 unique, should probably be factor

# Estimated.Cost.To.Date
class(inform$Estimated.Cost.To.Date) # logical?
summary(is.na(inform$Estimated.Cost.To.Date)) # also all NA
# don't know what to do about this either

# Final.Acres
class(inform$Final.Acres) # logical?
summary(is.na(inform$Final.Acres)) # once again all NA

# Final.Fire.Report.Approved.By.Title
class(inform$Final.Fire.Report.Approved.By.Title) # char
summary(is.na(inform$Final.Fire.Report.Approved.By.Title)) # many NA
length(unique(inform$Final.Fire.Report.Approved.By.Title)) # abt 1000 unique
inform %>% 
    group_by(Final.Fire.Report.Approved.By.Title) %>% 
    summarize(n=n()) %>% 
    arrange(desc(n))
# should be a factor, needs to be cleaned as well (AFMO <- Acting FMO, etc.)
# the cleaning is deeply difficult. will return later if relevant

# Final.Fire.Report.Approved.By.Unit
class(inform$Final.Fire.Report.Approved.By.Unit) # logical?
summary(is.na(inform$Final.Fire.Report.Approved.By.Unit)) # all NA
# idk, probably remove

# Final.Fire.Report.Approved.Date
class(inform$Final.Fire.Report.Approved.Date) # char
summary(is.na(inform$Final.Fire.Report.Approved.Date)) # pretty split NA
head(inform$Final.Fire.Report.Approved.Date)
# should be turned into date format

# Fire.Behavior.General
class(inform$Fire.Behavior.General) # logical
summary(is.na(inform$Fire.Behavior.General)) # all NA

# FireCode
class(inform$FireCode) # char
summary(is.na(inform$FireCode)) # many NA
length(unique(inform$FireCode)) # why are they mostly unique. hey now.
inform %>% 
    group_by(FireCode) %>% 
    summarize(n=n()) %>% 
    arrange(desc(n))
# I don't really know what's going on here
# apparently it's something to do with cost information? but don't have a way to decode

# FireDepartmentID
class(inform$FireDepartmentID) # char
summary(is.na(inform$FireDepartmentID)) # mostly NA
length(unique(inform$FireDepartmentID)) # 831 unique
inform %>% 
    group_by(FireDepartmentID) %>% 
    summarize(n=n()) %>% 
    arrange(desc(n))
# should probably be factor, but seems lowkey useless

# Fire.Discovery.Date.Time
class(inform$Fire.Discovery.Date.Time) # char
summary(is.na(inform$Fire.Discovery.Date.Time)) # no NA
head(inform$Fire.Discovery.Date.Time)
# convert to datetime

# Fire.Mgmt.Complexity
length(unique(inform$Fire.Mgmt.Complexity))
unique(inform$Fire.Mgmt.Complexity)
inform %>%
    group_by(Fire.Mgmt.Complexity) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# 9 options, a lot of NA - should look into NA sizes (maybe small ones aren't rated like this)
# should be a factor

# FireOutDateTime
class(inform$FireOutDateTime) # char
summary(is.na(inform$FireOutDateTime)) # about half NA
head(inform$FireOutDateTime)
# should be converted to datet

# FS.Job.Code 
class(inform$FS.Job.Code) # char
summary(is.na(inform$FS.Job.Code)) # mostly NA
length(unique(inform$FS.Job.Code)) # only 78 unique, probably factor
inform %>%
    group_by(FS.Job.Code) %>%
    summarize(n = n()) %>%
    arrange(desc(n))

# FS.Override.Code
class(inform$FS.Override.Code) # char
summary(is.na(inform$FS.Override.Code)) # mostly NA
length(unique(inform$FS.Override.Code)) # only 221, probably factor
inform %>%
    group_by(FS.Override.Code) %>%
    summarize(n = n()) %>%
    arrange(desc(n))

# GACC
class(inform$GACC) # char
summary(is.na(inform$GACC)) # only 27 NA
inform %>% 
    group_by(GACC) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should be factor

# Incident.Name
class(inform$Incident.Name) # char
summary(is.na(inform$Incident.Name)) # no NA
inform %>% 
    group_by(Incident.Name) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should not be a factor

# Incident.Short.Description
class(inform$Incident.Short.Description) # logical
summary(is.na(inform$Incident.Short.Description)) # all NA
# idk what to do with her

# Incident.Type.Category
class(inform$Incident.Type.Category) # char
length(unique(inform$Incident.Type.Category))
inform %>% 
    group_by(Incident.Type.Category) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should be factor - only WF or RX

# Incident.Type.Kind
class(inform$Incident.Type.Kind) # char
length(unique(inform$Incident.Type.Kind)) # only 1?
summary(is.na(inform$Incident.Type.Kind)) # no NA
inform %>% 
    group_by(Incident.Type.Kind) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# it's only FI, presumably for fire. possibly some of the excluded columns have another value. 

# Initial.Latitude
class(inform$Initial.Latitude) # numeric
summary(inform$Initial.Latitude) # 30k NA, range -32 to 123

# Initial.Longitude
class(inform$Initial.Longitude) # numeric
summary(inform$Initial.Longitude) # 30k NA, range -180 to 114

# Initial.Response.Date.Time
class(inform$Initial.Response.Date.Time) # char
summary(is.na(inform$Initial.Response.Date.Time)) # many NA
head(inform$Initial.Response.Date.Time)
# should be converted to datetime

# Is.Fire.Cause.Investigated
class(inform$Is.Fire.Cause.Investigated) # numeric?
summary(inform$Is.Fire.Cause.Investigated) # many NA, seems like a boolean
unique(inform$Is.Fire.Cause.Investigated)
# should be logical

# Is.FS.Assisted
class(inform$Is.FS.Assisted) # numeric
summary(inform$Is.FS.Assisted) # many NA, also boolean
unique(inform$Is.FS.Assisted)
# should be logical

# Is.Reimbursable
class(inform$Is.Reimbursable) # logical
summary(inform$Is.Reimbursable) # all NA

# Is.Trespass
class(inform$Is.Trespass) # numeric
summary(inform$Is.Trespass) # also seems to be bool, many NA
unique(inform$Is.Trespass)
# should be logical

# Local.Incident.Identifier
class(inform$Local.Incident.Identifier) # char
summary(is.na(inform$Local.Incident.Identifier)) # all present
length(unique(inform$Local.Incident.Identifier)) # mostly unique, char is good

# Modified.On.Date.Time
class(inform$Modified.On.Date.Time) # char
summary(is.na(inform$Modified.On.Date.Time)) # all present
head(inform$Modified.On.Date.Time)
# convert to datetime

# Percent.Contained
class(inform$Percent.Contained) # logical
summary(is.na(inform$Percent.Contained)) # all NA

# City
class(inform$City) # char
summary(is.na(inform$City)) # mostly missing
length(unique(inform$City)) # motsly unique
inform %>% 
    group_by(City) %>%
    summarize(n=n()) %>%
    arrange(desc(n))

# POO.County
class(inform$POO.County) # char
summary(is.na(inform$POO.County)) # only 16 NA
length(unique(inform$POO.County))
inform %>% 
    group_by(POO.County) %>%
    summarize(n=n()) %>%
    arrange(desc(n))

# POODispatchCenterID
class(inform$POODispatchCenterID) # char
summary(is.na(inform$POODispatchCenterID)) # only 89 NA
length(unique(inform$POODispatchCenterID)) # only 172 unique
inform %>% 
    group_by(POODispatchCenterID) %>%
    summarize(n=n()) %>%
    arrange(desc(n))

# POO.Fips
class(inform$POO.Fips) # char
summary(is.na(inform$POO.Fips)) # about half NA
length(unique(inform$POO.Fips))
inform %>% 
    group_by(POO.Fips) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# 5 digits, likely county codes

# POO.Jurisdictional.Agency
class(inform$POO.Jurisdictional.Agency) # char
summary(is.na(inform$POO.Jurisdictional.Agency)) # about half NA
inform %>% 
    group_by(POO.Jurisdictional.Agency) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# 64 unique, this may actually be useful!
# should be a factor

# POO.Jurisdictional.Unit
class(inform$POO.Jurisdictional.Unit) # char
summary(is.na(inform$POO.Jurisdictional.Unit)) # about half NA
inform %>% 
    group_by(POO.Jurisdictional.Unit) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# many unique

# POO.Jurisdictional.Unit.Parent.Unit
class(inform$POO.Jurisdictional.Unit.Parent.Unit) # logical
summary(is.na(inform$POO.Jurisdictional.Unit.Parent.Unit)) # all NA

# POOLandownerCategory
class(inform$POOLandownerCategory) # char
summary(is.na(inform$POOLandownerCategory)) # few NA
length(unique(inform$POOLandownerCategory)) # 21 unique
inform %>% 
    group_by(POOLandownerCategory) %>%
    summarize(n=n()) %>%
    arrange(desc(n)) %>%
    print(n=21)
# convert to factor, could be useful!

# POOLandownerKind
class(inform$POOLandownerKind) # char
summary(is.na(inform$POOLandownerKind)) # ~400 missing
length(unique(inform$POOLandownerKind)) # only 8
inform %>% 
    group_by(POOLandownerKind) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# convert to factor

# POO.Protecting.Agency
class(inform$POO.Protecting.Agency) # char
summary(is.na(inform$POO.Protecting.Agency)) # many NA
length(unique(inform$POO.Protecting.Agency)) # 58 unique
inform %>% 
    group_by(POO.Protecting.Agency) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# convert to factor

# POO.Protecting.Unit
class(inform$POO.Protecting.Unit) # char
summary(is.na(inform$POO.Protecting.Unit)) # some NA
length(unique(inform$POO.Protecting.Unit)) # ~1600 unique
inform %>% 
    group_by(POO.Protecting.Unit) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# I don't know what any of this means

# POO.State
class(inform$POO.State) # char
length(unique(inform$POO.State)) # 58 unique
inform %>% 
    group_by(POO.State) %>%
    summarize(n=n()) %>%
    arrange(POO.State) # a few in MX
# convert to factor

# Predominant.Fuel.Group
class(inform$Predominant.Fuel.Group) # char
length(unique(inform$Predominant.Fuel.Group)) # 7 unique
inform %>% 
    group_by(Predominant.Fuel.Group) %>%
    summarize(n=n()) %>%
    arrange(desc(n)) # many NA, could be useful though
# convert to factor

# Predominant.Fuel.Model
class(inform$Predominant.Fuel.Model) # char
length(unique(inform$Predominant.Fuel.Model)) # 46 unique
inform %>% 
    group_by(Predominant.Fuel.Model) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# i don't know what any of that means!

# UniqueFireIdentifier
class(inform$UniqueFireIdentifier) # char
summary(is.na(inform$UniqueFireIdentifier)) # ALL PRESENT this is excellent news friends
length(unique(inform$UniqueFireIdentifier)) # a few duplicates apparently?
inform %>% 
    group_by(UniqueFireIdentifier) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# not sure about the duplicates but otherwise this looks AWESOME

# FORID
class(inform$FORID) # char
summary(is.na(inform$FORID)) # all present
length(unique(inform$FORID)) # a few duplicates

# Initial.Response.Agencies
class(inform$Initial.Response.Agencies) # char
summary(is.na(inform$Initial.Response.Agencies)) # lots missing
length(unique(inform$Initial.Response.Agencies)) # ~1000
inform %>% 
    group_by(Initial.Response.Agencies) %>%
    summarize(n=n()) %>%
    arrange(Initial.Response.Agencies)
# should be cleaned up if we're going to use it, comma separated for doubles but at least alphabetical

# Fire.Cause
class(inform$Fire.Cause) # numeric?
summary(is.na(inform$Fire.Cause)) # some missing
length(unique(inform$Fire.Cause)) # only 4
inform %>% 
    group_by(Fire.Cause) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# ok. well. wish i knew what that meant.

# Fire.Cause.General
class(inform$Fire.Cause.General) # numeric?
summary(is.na(inform$Fire.Cause.General)) # many missing
length(unique(inform$Fire.Cause.General)) # 14 unique
inform %>% 
    group_by(Fire.Cause.General) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# it's numbers! wish i knew what they meant!

# Fire.Cause.Specific
class(inform$Fire.Cause.Specific) # numeric?
summary(is.na(inform$Fire.Cause.Specific)) # many missing
length(unique(inform$Fire.Cause.Specific)) # 77 unique
inform %>% 
    group_by(Fire.Cause.Specific) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# once again saying I wish I knew what these numbers meant

# Fire.Cause.Specific.Detail
class(inform$Fire.Cause.Specific.Detail) # numeric?
summary(is.na(inform$Fire.Cause.Specific.Detail)) # mostly missing
length(unique(inform$Fire.Cause.Specific.Detail)) # 56 unique
inform %>% 
    group_by(Fire.Cause.Specific.Detail) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# again, wish I knew what it meant

# Fire.Cause.Age.Category
class(inform$Fire.Cause.Age.Category) # numeric
summary(is.na(inform$Fire.Cause.Age.Category)) # many missing
length(unique(inform$Fire.Cause.Age.Category)) # only 5
inform %>% 
    group_by(Fire.Cause.Age.Category) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# yep. wish I knew what it meant.

# Fire.Cause.Activity.Group
class(inform$Fire.Cause.Activity.Group) # numeric
summary(is.na(inform$Fire.Cause.Activity.Group)) # mostly missing
length(unique(inform$Fire.Cause.Activity.Group)) # 20 unique
inform %>% 
    group_by(Fire.Cause.Activity.Group) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# more meaningless undefined numbers. thanks NIFC this is awesome

# GlobalID 
class(inform$GlobalID) # char
summary(is.na(inform$GlobalID)) # all present
length(unique(inform$GlobalID)) # all unique!
head(inform$GlobalID)
# yep looks fine to me

# IsCauseProhibited
class(inform$IsCauseProhibited) # numeric
inform %>% 
    group_by(IsCauseProhibited) %>%
    summarize(n=n()) %>%
    arrange(desc(n)) # mostly missing
# convert to logical

# ModifiedBySystem
class(inform$ModifiedBySystem) # char
summary(is.na(inform$ModifiedBySystem)) # about half NA
length(unique(inform$ModifiedBySystem)) # 21 unique
inform %>% 
    group_by(ModifiedBySystem) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# convert to factor

# Related.Irwin.IDs
class(inform$Related.Irwin.IDs) # char
summary(is.na(inform$Related.Irwin.IDs)) # about half NA
length(unique(inform$Related.Irwin.IDs)) # mostly unique
head(inform$Related.Irwin.IDs) # yep looks fine to me

# Status
class(inform$Status) # char
summary(is.na(inform$Status)) # all present
length(unique(inform$Status)) # 3 unique
inform %>% 
    group_by(Status) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# factor - Incomplete, Certified, Complete

# AcresBIA

# AcresBLM

# AcresBOR

# AcresDOD

# AcresDOE

# AcresNPS

# AcresUSFS

# AcresUSFWS

# AcresForeign

# AcresTribal

# AcresCity

# AcresCounty

# AcresState

# AcresPrivate

# AcresANCSA

# AcresOtherLocal

# AcresOtherFederal

# Fire.Cause.Comments

# Calendar.Year

# x

# y

```

## InFORM Cleaning

```{r}
# limiting Calendar.Year to just 2015-2026
inform <- inform %>%
    filter(Calendar.Year >= 2015, Calendar.Year <= 2026)

inform %>%
    group_by(Calendar.Year) %>%
    summarize(n = n())
```

```{r}
# changing ADS.Permission.State to a factor
inform <- inform %>%
    mutate(ADS.Permission.State = as_factor(ADS.Permission.State))
```


```{r}
# removing anomaly -1 acres burned fire
inform <- inform %>%
    filter(Calculated.Acres >= 0)
```

```{r}
# converting Containment.Date.Time to a date
inform <- inform %>%
    mutate(Containment.Date.Time = lubridate::mdy_hms(Containment.Date.Time))

summary(inform$Containment.Date.Time)
# hey why is there one for 1970. hey.
inform %>% select(Containment.Date.Time, Calendar.Year, Fire.Discovery.Date.Time) %>% 
    group_by(Containment.Date.Time, Calendar.Year) %>%
    filter(!is.na(Containment.Date.Time)) %>%
    summarize(n=n()) %>%
    arrange(Containment.Date.Time)

# 1970-01-01 has to be a placeholder. changing to NA
inform %>% 
    mutate(Containment.Date.Time = na_if(Containment.Date.Time, as_datetime("1970-01-01 00:00:00"))) %>%
    group_by(Containment.Date.Time) %>%
    summarize(n=n()) %>%
    arrange(Containment.Date.Time)

inform <- inform %>% 
    mutate(Containment.Date.Time = na_if(Containment.Date.Time, as_datetime("1970-01-01 00:00:00")))

```

```{r}
# converting Control.Date.Time to a date
inform <- inform %>%
    mutate(Control.Date.Time = lubridate::mdy_hms(Control.Date.Time))

summary(inform$Control.Date.Time)
# these are not marked 1970! go team
```

```{r}
# Created.By.System -> factor
inform <- inform %>%
    mutate(Created.By.System = as_factor(Created.By.System))
```

```{r}
# converting Created.On.Date.Time to datetime
inform <- inform %>%
    mutate(Created.On.Date.Time = as_datetime(Created.On.Date.Time/1000)) 

inform %>%
    select(Created.On.Date.Time)

```

```{r}
# converting Dispatch.Center.ID to factor
inform <- inform %>% 
    mutate(Dispatch.Center.ID = as_factor(Dispatch.Center.ID))

inform %>% 
    group_by(Dispatch.Center.ID) %>% 
    summarize(n = n()) %>% 
    arrange(desc(n))
```

```{r}
# IN PROGRESS
# this is taking a long long long time
# so. going to move on for now

inform_report_title <- interim_inform %>% 
    #mutate(Final.Fire.Report.Approved.By.Title = toupper(Final.Fire.Report.Approved.By.Title)) %>%
    group_by(Final.Fire.Report.Approved.By.Title) %>% 
    summarize(n=n()) %>% 
    arrange(Final.Fire.Report.Approved.By.Title)

print(inform_report_title[60:200, 1:2], n=100)
length(unique(inform_report_title$Final.Fire.Report.Approved.By.Title))
length(unique(inform$Final.Fire.Report.Approved.By.Title))

interim_inform <- inform %>%
    mutate(
        # (Supervisory) Range Tech
        Final.Fire.Report.Approved.By.Title = ifelse(
            Final.Fire.Report.Approved.By.Title %in% c(
                "(Supervisor) Range Tech", 
                "(Supervisory Range Tech", 
                "(Supervisory) Range Tech)", 
                "(Supervsory) Range Tech"
            ), 
            "(Supervisory) Range Tech", Final.Fire.Report.Approved.By.Title),
        # Acting AFMO
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACTING AFMO", 
                "ACTING  AFMO",
                "AFMO (ACTING)", 
                "ACT AFMO",
                "ACTING ASSISTANT FMO", 
                "ACTING ASST. FMO",
                "ACTINT AFMO"
            ),
            "Acting AFMO", Final.Fire.Report.Approved.By.Title
        ),
        # Acting FMO
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACT FMO", 
                "ACTIG FIRE MANAGEMENT OFFICER", 
                "ACTING FMMO", 
                "ACTING FIRE MANAGEMENT OFFICE", 
                "ACTING FIRE MANAGEMENT OFFICER", 
                "ACTING FIRE MANAGEMENT OFFIER", 
                "ACTING FIRE MANAGEMTN", 
                "ACTING FIRE MANAGEMTN OFICER", 
                "ACTING FIRE MANAGMENT OFFICER", 
                "ACTING FIRE MGMT OFFICER", 
                "ACTING FMO", 
                "ACTING FIRE MANAGEMTN OFFICER", 
                "ACTING FRIE MANAGEMENT OFFICER", 
                "ACTING-FMO"
            ),
            "Acting FMO", Final.Fire.Report.Approved.By.Title
        ),
        # Acting Superintendent
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACTING SUPERINTENDENT", 
                "ACTING SUPT", 
                "ACTING SUPT."
            ),
            "Acting Superintendent", Final.Fire.Report.Approved.By.Title
        ),
        # Acting Zone FMO
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACTING ZONE FMO", 
                "ACTING ZONE FIRE MANAGEMENT OFFICER", 
                "ACTING ZONE FIRE MGMT OFFICER",
                "ACTING ZONE FIRE MGT OFFICER",
                "ACTING ZONE FRIE MGMT OFFICER"
            ),
            "Acting Zone FMO", Final.Fire.Report.Approved.By.Title
        ),
        # AFMO (Assistant Fire Management Officer)
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "AFMO",
                "AMFO",
                "ASSIST FMO",
                "ASSISTANT FMO",
                "ASSISTANT FIRE MANAGEMENT OFFI",
                "ASST FIRE MANAGEMENT OFFICER",
                "ASST. FIRE MANAGEMENT OFFICER"
            ),
            "AFMO", Final.Fire.Report.Approved.By.Title
        ),
        # AFMO Ops
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "AFMO OPS",
                "AFMO  OPS",
                "AFMO OPS.",
                "AFMO OPERATIONS",
                "AFMO. OPS",
                "AFMO - OPERATIONS"
            ),
            "AFMO Ops", Final.Fire.Report.Approved.By.Title
        ),
        # Asst. District Forester
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ASST DISCT. FORESTER",
                "ASST DISTRICT FORESTER",
                "ASST. DISTRICT FORESTER",
                "ASST, DISPTRICT FORESTER",
                "ASST, DISTC FORESTER",
                "ASST, DISTRICT FORESTER",
                "ASST. DISC FORESTER",
                "ASST. DISCTRIC FORESTER",
                "ASST. DITRICT FORESTER",
                "ASST, DISTRICT FOREST",
                "ASST. DISCTRIC FORESTER"
            ), "Asst. District Forester", Final.Fire.Report.Approved.By.Title
        ),
        # ASFT
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "A.S.F.T", 
                "A.S.F.T.", 
                "ASFT"
            ),
            "ASFT", Final.Fire.Report.Approved.By.Title
        )
    )

```

```{r}
# converting Final.Fire.Report.Approved.Date to datetime
inform %>% 
    select(Final.Fire.Report.Approved.Date) 

inform <- inform %>%
    mutate(Final.Fire.Report.Approved.Date = mdy_hms(Final.Fire.Report.Approved.Date))
```

```{r}
# converting Fire.Discovery.Date.Time to datetime
inform %>% 
    select(Fire.Discovery.Date.Time)

inform <- inform %>%
    mutate(Fire.Discovery.Date.Time = mdy_hms(Fire.Discovery.Date.Time))
```

```{r}
# converting Fire.Mgmt.Complexity to factor
inform %>% 
    group_by(Fire.Mgmt.Complexity) %>%
    summarize(n = n())

inform <- inform %>%
    mutate(Fire.Mgmt.Complexity = factor(Fire.Mgmt.Complexity, 
        levels=c(
            "Type 1 Incident",
            "Type 1 Prescribed Fire",
            "Type 2 Incident",
            "Type 3 Incident", 
            "Type 3 Prescribed Fire",
            "Type 4 Incident",
            "Type 5 Incident",
            "Complex Incident"
        ), ordered=TRUE))
```

```{r}
# converting FireOutDateTime to datetime
inform %>% 
    select(FireOutDateTime)

inform <- inform %>%
    mutate(FireOutDateTime = mdy_hms(FireOutDateTime))
```

```{r}
# converting FS.Job.Code to factor
inform <- inform %>%
    mutate(FS.Job.Code = as_factor(FS.Job.Code))

```

```{r}
# converting FS.Override.Code to factor
inform <- inform %>%
    mutate(FS.Override.Code = as_factor(FS.Override.Code))

```

```{r}
# converting GACC to factor
inform <- inform %>%
    mutate(GACC = as_factor(GACC))

```

```{r}
# converting Incident.Type.Category to factor
inform <- inform %>%
    mutate(Incident.Type.Category = as_factor(Incident.Type.Category))

```

```{r}
# converting Initial.Response.Date.Time to datetime
inform %>%
    select(Initial.Response.Date.Time)

inform <- inform %>%
    mutate(Initial.Response.Date.Time = mdy_hms(Initial.Response.Date.Time))

```

```{r}
# convert Is.Fire.Cause.Investigated to bool
inform %>% 
    select(Is.Fire.Cause.Investigated) 

inform <- inform %>% 
    mutate(Is.Fire.Cause.Investigated = as.logical(Is.Fire.Cause.Investigated))

```

```{r}
# convert Is.FS.Assisted to bool
inform %>% 
    select(Is.FS.Assisted) 

inform <- inform %>% 
    mutate(Is.FS.Assisted = as.logical(Is.FS.Assisted))

```

```{r}
# convert Is.Trespass to bool
inform %>% 
    select(Is.Trespass) 

inform <- inform %>% 
    mutate(Is.Trespass = as.logical(Is.Trespass))

```

```{r}
# converting Modified.On.Date.Time to datetime
inform %>%
    select(Modified.On.Date.Time)

inform <- inform %>%
    mutate(Modified.On.Date.Time = mdy_hms(Modified.On.Date.Time))

```

```{r}
# converting POO.Fips to numeric
inform <- inform %>%
    mutate(POO.Fips = as.numeric(POO.Fips)) 

```

```{r}
# converting POO.Jurisdictional.Agency to factor
inform <- inform %>%
    mutate(POO.Jurisdictional.Agency = as_factor(POO.Jurisdictional.Agency))

```

```{r}
# converting POOLandownerCategory to factor
inform <- inform %>%
    mutate(POOLandownerCategory = as_factor(POOLandownerCategory))
```

```{r}
# converting POOLandownerKind to factor
inform <- inform %>%
    mutate(POOLandownerKind = as_factor(POOLandownerKind))
```

```{r}
# converting POO.Protecting.Agency to factor
inform <- inform %>%
    mutate(POO.Protecting.Agency = as_factor(POO.Protecting.Agency))
```

```{r}
# converting POO.State to factor
inform <- inform %>%
    mutate(POO.State = as_factor(POO.State))
```

```{r}
# converting Predominant.Fuel.Group to factor
inform <- inform %>%
    mutate(Predominant.Fuel.Group = as_factor(Predominant.Fuel.Group))
```

```{r}
# convert IsCauseProhibited to bool
inform <- inform %>% 
    mutate(IsCauseProhibited = as.logical(IsCauseProhibited))
```

```{r}
# converting ModifiedBySystem to factor
inform <- inform %>%
    mutate(ModifiedBySystem = as_factor(ModifiedBySystem))
```

```{r}
# converting Status to factor
inform <- inform %>%
    mutate(Status = as_factor(Status))
```