---
title: "Fire Severity Feature Engineering"
author: "Spencer Fiden"
date: "2026-05-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
library(ggplot2)
library(sf)
library(viridis)
# install.packages("reticulate")
```

```{r}
df <- read_csv("data/processed_grid.csv")
shp <- st_read("data/processed_grid.shp")

inform <- read_csv("/Users/nikolefiden/Desktop/DATA-510/InFORM_FireOccurrence_Public.csv")
# replacing spaces in col names with "." 
inform <- inform %>% dplyr::rename_all(~ make.names(.))

```

## Cleaning

### Data type conversion

#### Numeric 

```{r}
# converting POO.Fips to numeric
inform <- inform %>%
    mutate(POO.Fips = as.numeric(POO.Fips)) 

```

#### Factor

```{r}
# changing ADS.Permission.State to a factor
inform <- inform %>%
    mutate(ADS.Permission.State = as_factor(ADS.Permission.State))
```

```{r}
# Created.By.System -> factor
inform <- inform %>%
    mutate(Created.By.System = as_factor(Created.By.System))
```

```{r}
# converting Dispatch.Center.ID to factor
inform <- inform %>% 
    mutate(Dispatch.Center.ID = as_factor(Dispatch.Center.ID))

```

```{r}
# converting Fire.Mgmt.Complexity to ordered factor
inform %>% 
    group_by(Fire.Mgmt.Complexity) %>%
    summarize(n = n())

inform <- inform %>%
    mutate(Fire.Mgmt.Complexity = factor(Fire.Mgmt.Complexity, 
        levels=c(
            "Type 1 Incident",
            "Type 1 Prescribed Fire",
            "Type 2 Incident",
            "Type 3 Incident", 
            "Type 3 Prescribed Fire",
            "Type 4 Incident",
            "Type 5 Incident",
            "Complex Incident"
        ), ordered=TRUE))
```

```{r}
# converting FS.Job.Code to factor
inform <- inform %>%
    mutate(FS.Job.Code = as_factor(FS.Job.Code))

```

```{r}
# converting FS.Override.Code to factor
inform <- inform %>%
    mutate(FS.Override.Code = as_factor(FS.Override.Code))

```

```{r}
# converting GACC to factor
inform <- inform %>%
    mutate(GACC = as_factor(GACC))

```

```{r}
# converting Incident.Type.Category to factor
inform <- inform %>%
    mutate(Incident.Type.Category = as_factor(Incident.Type.Category))

```

```{r}
# converting POO.Jurisdictional.Agency to factor
inform <- inform %>%
    mutate(POO.Jurisdictional.Agency = as_factor(POO.Jurisdictional.Agency))

```

```{r}
# converting POOLandownerCategory to factor
inform <- inform %>%
    mutate(POOLandownerCategory = as_factor(POOLandownerCategory))
```

```{r}
# converting POOLandownerKind to factor
inform <- inform %>%
    mutate(POOLandownerKind = as_factor(POOLandownerKind))
```

```{r}
# converting POO.Protecting.Agency to factor
inform <- inform %>%
    mutate(POO.Protecting.Agency = as_factor(POO.Protecting.Agency))
```

```{r}
# converting POO.State to factor
inform <- inform %>%
    mutate(POO.State = as_factor(POO.State))
```

```{r}
# converting Predominant.Fuel.Group to factor
inform <- inform %>%
    mutate(Predominant.Fuel.Group = as_factor(Predominant.Fuel.Group))
```

```{r}
# converting ModifiedBySystem to factor
inform <- inform %>%
    mutate(ModifiedBySystem = as_factor(ModifiedBySystem))
```

```{r}
# converting Status to factor
inform <- inform %>%
    mutate(Status = as_factor(Status))
```

#### Logical

```{r}
# convert Is.Fire.Cause.Investigated to bool
inform %>% 
    select(Is.Fire.Cause.Investigated) 

inform <- inform %>% 
    mutate(Is.Fire.Cause.Investigated = as.logical(Is.Fire.Cause.Investigated))

```

```{r}
# convert Is.FS.Assisted to bool
inform %>% 
    select(Is.FS.Assisted) 

inform <- inform %>% 
    mutate(Is.FS.Assisted = as.logical(Is.FS.Assisted))

```

```{r}
# convert Is.Trespass to bool
inform %>% 
    select(Is.Trespass) 

inform <- inform %>% 
    mutate(Is.Trespass = as.logical(Is.Trespass))

```

```{r}
# convert IsCauseProhibited to bool
inform <- inform %>% 
    mutate(IsCauseProhibited = as.logical(IsCauseProhibited))
```


#### Datetime

```{r}
# converting Containment.Date.Time to a date
inform <- inform %>%
    mutate(Containment.Date.Time = lubridate::mdy_hms(Containment.Date.Time))

# hey why is there one for 1970. hey.
inform %>% select(Containment.Date.Time, Calendar.Year, Fire.Discovery.Date.Time) %>% 
    group_by(Containment.Date.Time, Calendar.Year) %>%
    filter(!is.na(Containment.Date.Time)) %>%
    summarize(n=n()) %>%
    arrange(Containment.Date.Time)

```

```{r}
# converting Control.Date.Time to a date
inform <- inform %>%
    mutate(Control.Date.Time = lubridate::mdy_hms(Control.Date.Time))

```

```{r}
# converting Created.On.Date.Time to datetime
inform <- inform %>%
    mutate(Created.On.Date.Time = as_datetime(Created.On.Date.Time/1000)) 

inform %>%
    select(Created.On.Date.Time)

```

```{r}
# converting Final.Fire.Report.Approved.Date to datetime
inform %>% 
    select(Final.Fire.Report.Approved.Date) 

inform <- inform %>%
    mutate(Final.Fire.Report.Approved.Date = mdy_hms(Final.Fire.Report.Approved.Date))
```

```{r}
# converting Fire.Discovery.Date.Time to datetime
inform %>% 
    select(Fire.Discovery.Date.Time)

inform <- inform %>%
    mutate(Fire.Discovery.Date.Time = mdy_hms(Fire.Discovery.Date.Time))
```

```{r}
# converting FireOutDateTime to datetime
inform %>% 
    select(FireOutDateTime)

inform <- inform %>%
    mutate(FireOutDateTime = mdy_hms(FireOutDateTime))
```

```{r}
# converting Initial.Response.Date.Time to datetime
inform %>%
    select(Initial.Response.Date.Time)

inform <- inform %>%
    mutate(Initial.Response.Date.Time = mdy_hms(Initial.Response.Date.Time))

```

```{r}
# converting Modified.On.Date.Time to datetime
inform %>%
    select(Modified.On.Date.Time)

inform <- inform %>%
    mutate(Modified.On.Date.Time = mdy_hms(Modified.On.Date.Time))

```

### Column removal, filtering

```{r}
# removing columns that are missing all values
inform <- inform %>% 
    select(-c(
        Discovery.Acres, 
        Estimated.Cost.To.Date, 
        Final.Acres, 
        Final.Fire.Report.Approved.By.Unit, 
        Fire.Behavior.General, 
        Incident.Short.Description, 
        Is.Reimbursable, 
        POO.Jurisdictional.Unit.Parent.Unit, 
        Percent.Contained
    ))
```

```{r}
# limiting Calendar.Year to just 2015-2026
# missing values for Calendar.Year are all present for Fire.Discovery.Date.Time - can impute


inform <- inform %>%
    mutate(
        # imputing values that are off by 100 - can assume 1922 -> 2022 and 2121 -> 2021
        Calendar.Year = ifelse(abs(year(Fire.Discovery.Date.Time) - Calendar.Year)==100, 
                        year(Fire.Discovery.Date.Time), 
                        Calendar.Year),
        # imputing missing values 
        Calendar.Year = ifelse(is.na(Calendar.Year), 
                        year(Fire.Discovery.Date.Time), 
                        Calendar.Year)
    ) 

inform <- inform %>%
    mutate(
        Calendar.Year = ifelse(Calendar.Year > 2100, year(Fire.Discovery.Date.Time), Calendar.Year)
    )

    
inform %>%
    # removing all where Fire.Discovery.Date.Time and Calendar.Year are misaligned by more than one year
    filter(abs(year(Fire.Discovery.Date.Time) - Calendar.Year) <= 1) %>%
    filter(Calendar.Year >= 2015, Calendar.Year <= 2026)

inform %>%
    group_by(Calendar.Year) %>%
    summarize(n = n())
```

```{r}
summary(inform$Calendar.Year)

inform %>%
    select(Calendar.Year) %>%
    arrange(desc(Calendar.Year))

inform %>%
    filter(Calendar.Year > 2026) %>%
    summarize(sum(is.na(Fire.Discovery.Date.Time)))

summary(is.na(inform$Fire.Discovery.Date.Time))
```

```{r}
# removing anomaly -1 acres burned fire
inform <- inform %>%
    filter(Calculated.Acres >= 0)
```

### Parsing/changing specific entry types to NA

```{r}
# 1970-01-01 is to be a placeholder, changing to NA
inform %>% 
    mutate(Containment.Date.Time = na_if(Containment.Date.Time, as_datetime("1970-01-01 00:00:00"))) %>%
    group_by(Containment.Date.Time) %>%
    summarize(n=n()) %>%
    arrange(Containment.Date.Time)

inform <- inform %>% 
    mutate(Containment.Date.Time = na_if(Containment.Date.Time, as_datetime("1970-01-01 00:00:00")))

```


```{r}
# cleaning Fire.Cause.Comments
inform %>%
    group_by(Fire.Cause.Comments) %>%
    summarize(n = n()) %>%
    arrange(Fire.Cause.Comments)

inform %>%
    mutate(Fire.Cause.Comments = str_remove(Fire.Cause.Comments, "\n")
    ) %>%
    mutate(Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("N/A", "NA", "", "*", ".", "-", ".."), NA, Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c(
                "UNKNOWN", 
                "UNDETERMINED", 
                "UNK", 
                "UN", 
                "UNKOWN", 
                "UNKNOWN CAUSE",
                "UK"
           ), "Unknown", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("UNDER INVESTIGATION"), "Under investigation", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NOT INVESTIGATED"), "Not investigated", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NONE"), "None", Fire.Cause.Comments)
    ) %>%
    group_by(Fire.Cause.Comments) %>%
    summarize(n = n()) %>%
    arrange(desc(n)) %>%
    print(n=25)

inform <- inform %>% 
    mutate(Fire.Cause.Comments = str_remove(Fire.Cause.Comments, "\n")) %>%
    mutate(Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("N/A", "NA", "", "*", ".", "-", ".."), NA, Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c(
                "UNKNOWN", 
                "UNDETERMINED", 
                "UNK", 
                "UN", 
                "UNKOWN", 
                "UNKNOWN CAUSE",
                "UK"
           ), "Unknown", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("UNDER INVESTIGATION"), "Under investigation", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NOT INVESTIGATED"), "Not investigated", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NONE"), "None", Fire.Cause.Comments)
    )
```

## Fire Severity Feature

```{r}
inform <- inform %>%
    filter(Calendar.Year >= 2005)
```

```{r}
inform %>%
    group_by(Fire.Mgmt.Complexity, Incident.Type.Category) %>%
    summarize(
        n=n(),
        avg_acres = mean(Calculated.Acres, na.rm=TRUE)
    ) %>%
    arrange(avg_acres)

inform %>%
    group_by(Incident.Type.Category) %>%
    summarize(
        n=n()
    ) %>%
    arrange(n)
```

```{r}
inform %>%
    group_by(Fire.Mgmt.Complexity, Incident.Type.Category) %>%
    summarize(
        n=n(),
        avg_acres = mean(Calculated.Acres, na.rm=TRUE),
        max_acres = max(Calculated.Acres, na.rm=TRUE),
        min_acres = min(Calculated.Acres, na.rm=TRUE)
    ) %>%
    arrange(avg_acres) %>%
    print(width=Inf)
```
