---
title: "grid EDA"
author: "Spencer Fiden"
date: "2026-07-21"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(sf)
library(viridis)
```

```{r}
grid <- st_read("data/processed_grid/processed_grid.shp")
grid_df <- tibble(grid) # tibble will run summarize faster!
```

```{r}
names(grid)

grid_df %>%
    filter(n_wldfr > 0) %>%
    mutate(has_rx = n_rx_fr > 0) %>%
    group_by(has_rx) %>%
    summarize(
        mean_acres = mean(max_crs, na.rm=TRUE),
        median_acres = median(max_crs, na.rm=TRUE),
        mean_dur = mean(mx_drtn, na.rm=TRUE),
        median_dur = median(mx_drtn, na.rm=TRUE),
        n=n()
    )

```

Grid cells with wildfires and without prescribed burns had more acres burned (by mean and median) than those with prescribed burns, and shorter mean duration but longer median duration.

With vs without prescribed burns

```{r}
# boxplot
grid_df %>%
    filter(n_wldfr > 0) %>%
    mutate(has_rx = n_rx_fr > 0) %>%
    ggplot(aes(has_rx, max_crs, fill=has_rx)) +
    geom_boxplot(show.legend=FALSE) +
    scale_y_log10() + 
    theme_minimal() +
    labs(
        x="Prescribed burns present in cell",
        y="Maximum acres burned during fire in cell (log scale)",
        title="Fire size in areas with vs. without prescribed burns"
    )

```

```{r}
grid_df %>%
    filter(n_wldfr > 0) %>%
    mutate(
        has_rx = n_rx_fr > 0
    ) %>%
    group_by(has_rx, mx_sz_c) %>%
    summarize(n=n()) %>%
    group_by(has_rx) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(mx_sz_c, pct_sz, fill=has_rx)) +
    geom_col(position="dodge", color="white") +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum size class of fires in cell",
        y="Percent of cells",
        title="Distribution of fire size class in areas with vs. without prescribed burns"
    )

```

Indigenous vs non-Indigeous

```{r}
grid_df %>%
    filter(n_wldfr > 0) %>%
    mutate(is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")) %>%
    group_by(is_ndgn, mx_sz_c) %>%
    summarize(n=n()) %>%
    group_by(is_ndgn) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(mx_sz_c, pct_sz, fill=is_ndgn)) +
    geom_col(position="dodge", color="white") +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum size class of fires in cell",
        y="Percent of cells",
        title="Distribution of fire size class for Indigenous vs non-Indigenous land"
    )

```

```{r}
# boxplot duration
ind_fire_dur_boxplot <- grid_df %>%
    filter(n_wldfr > 0) %>%
    mutate(is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")) %>%
    ggplot(aes(is_ndgn, mx_drtn, fill=is_ndgn)) +
    geom_boxplot(show.legend=FALSE) +
    scale_y_log10() + 
    theme_minimal() +
    labs(
        x="Whether Indigenous land",
        y="Maximum duration burned during fire in cell (log scale)",
        title="Maximum fire duration for Indigenous vs \nnon-Indigenous land"
    )


```

```{r}
ind_rx_grid_hist <- grid_df %>%
    filter(n_wldfr > 0) %>%
    mutate(
        has_rx = ifelse(n_rx_fr > 0, "prescribed burns", "no prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "indigenous", "not indigenous")
    ) %>%
    group_by(has_rx, is_ndgn, mx_sz_c) %>%
    summarize(n=n()) %>%
    group_by(has_rx, is_ndgn) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(mx_sz_c, pct_sz, fill=has_rx)) +
    geom_col(color="white", show.legend=FALSE) +
    facet_grid(is_ndgn~has_rx) +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum fire size class",
        y="Percent of fires",
        title="Fire size distribution by presence of prescribed burn and whether \nfederally recognized Indigenous land"
    )

ggsave("images/ind_rx_grid_hist.jpeg", ind_rx_grid_hist, width=7, height=4, units="in")

```


```{r}
grid_df %>%
    filter(n_wldfr > 0) %>%
    mutate(
        has_rx = ifelse(n_rx_fr > 0, "prescribed burns", "no prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "indigenous", "not indigenous")
    ) %>%
    group_by(has_rx, is_ndgn, mx_sz_c) %>%
    summarize(n_fires=n()) %>%
    ggplot(aes(mx_sz_c, n_fires, fill=has_rx)) +
    geom_col(color="white", show.legend=FALSE) +
    facet_grid(is_ndgn~has_rx, scales="free_y") +
    #scale_y_continuous(labels=scales::percent) +
    theme_minimal() 

```


```{r}
grid_cell_areas = st_area(grid)

max(grid_cell_areas)
min(grid_cell_areas)
mean(grid_cell_areas)
median(grid_cell_areas)

```