---
title: "IFPH InFORM Join"
author: "Spencer Fiden"
date: "2026-05-29"
output: html_document
---

# IFPH InFORM join

## Ingestion from download

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
library(ggplot2)
library(sf)
```

```{r}
ifph <- st_read("data/ifph_clean/ifph_clean.shp")
ifph_df <- read_csv("data/ifph_clean/ifph_clean.csv")

inform <- read_csv("../DATA-510/inform_clean.csv")
inform_shp <- st_read("data/inform_clean/inform_clean.shp")
```

```{r}
lengths(inform)
lengths(inform_shp)
lengths(ifph)
lengths(ifph_df)
```

# Joining them

## Checking Unique Fire ID for join validity

```{r}
# making tibble for this so it runs faster
ifph_df %>%
    mutate(FORID = str_remove_all(FORID, "[{}]")) %>%
    mutate(
        unqe_match = ifelse(UNQE_FIRE_ %in% inform$UniqueFireIdentifier, T, F),
        forid_match = ifelse(FORID %in% inform$FORID, T, F),
        globalid_match = ifelse(GlobalID %in% inform$GlobalID, T, F)
    ) %>%
    group_by(unqe_match, forid_match, globalid_match)%>%
    summarize(n=n())

head(inform %>% select(UniqueFireIdentifier, FORID, GlobalID))
head(ifph %>% select(UNQE_FIRE_, FORID, GlobalID))

sum(ifph_df$UNQE_FIRE_ %in% inform$UniqueFireIdentifier)

```

```{r}
ifph_df %>%
    group_by(UNQE_FIRE_, GlobalID) %>%
    summarize(n=n()) %>%
    filter(n > 1) %>%
    arrange(desc(n))

inform %>%
    group_by(UniqueFireIdentifier, GlobalID) %>%
    summarize(n=n()) %>%
    filter(n > 1, !is.na(UniqueFireIdentifier)) %>%
    arrange(desc(n))

# everything with duplicated unique fire identifiers has a distinct global id for each entry. so i guess that makes sense. however the global IDs don't overlap across datasets
```

## checking lat lon presence

```{r}
inform %>%
    group_by(Incident.Type.Category) %>%
    summarize(
        lat_missing = sum(is.na(Initial.Latitude)),
        lon_missing = sum(is.na(Initial.Longitude)),
        n=n()
    ) %>%
    mutate(
        pct_present = 1 - (lat_missing/n)
    )

ifph_df %>% 
    mutate(is_ifph = TRUE) %>%
    full_join(inform %>% mutate(is_inform = TRUE) %>% filter(!is.na(UniqueFireIdentifier)), by=c("UNQE_FIRE_" = "UniqueFireIdentifier")) %>%
    group_by(is_ifph, is_inform, Incident.Type.Category) %>%
    summarize(
        n=n(),
        lat_missing = sum(is.na(Initial.Latitude))
    ) %>%
    mutate(
        pct_present = 1 - (lat_missing/n)
    )

inform_shp %>%
    ggplot(aes(geometry=geometry)) +
    geom_sf(data=or, aes(geometry=geom)) +
    geom_sf(aes(color=Inc_T_C, size=Clclt_A), alpha=0.5) +
    scale_color_discrete(palette=c("RX" = "green3", "WF" = "firebrick")) +
    theme_minimal()

```

# Joining on UNQE_FIRE_

```{r}
inform %>%
    filter(UniqueFireIdentifier %in% ifph_df$UNQE_FIRE_) %>%
    group_by(is.na(Fire.Mgmt.Complexity)) %>% 
    summarize(n=n())

ifph_df %>% 
    mutate(is_ifph = TRUE) %>%
    full_join(inform %>% mutate(is_inform = TRUE) %>% filter(!is.na(UniqueFireIdentifier)), by=c("UNQE_FIRE_" = "UniqueFireIdentifier")) %>%
    group_by(is_ifph, is_inform, Calendar.Year) %>%
    summarize(n=n()) %>%
    arrange(desc(Calendar.Year))

```

```{r}
# left join on IFPH, as non-IFPH data will be point geometries from inform
ifph_inform <- ifph %>% 
    mutate(is_ifph = TRUE) %>%
    inner_join(inform %>% mutate(is_inform = TRUE) %>% filter(!is.na(UniqueFireIdentifier)), by=c("UNQE_FIRE_" = "UniqueFireIdentifier"))

# assorted checks
tibble(ifph_inform) %>% 
    filter(FIRE_YEAR_ >= 2015, FIRE_YEAR_ <= 2025) %>%
    group_by(is_inform, FIRE_YEAR_) %>%
    summarize(n=n()) %>%
    arrange(desc(n)) %>%
    print(n=20)

tibble(ifph_inform) %>% 
    group_by(is_inform) %>%
    summarize(
        n=n(),
        quant_year = as_tibble_row(quantile(FIRE_YEAR_))
    ) %>%
    arrange(desc(n)) 

tibble(ifph_inform) %>%
    filter(is.na(Fire.Mgmt.Complexity)) %>%
    summarize(n=n())

ifph_df %>%
    summarize(
        n=n(),
        quant_year = as_tibble_row(quantile(FIRE_YEAR_))
    )
# this is a potential issue - the year spread is pretty distinct.
# can no longer see bc i made it an inner join. lol

tibble(ifph_inform) %>%
    filter(is_inform == TRUE) %>%
    mutate(acre_diff = abs(Calculated.Acres - GIS_ACRES)) %>%
    summarize(
        mean_diff = mean(acre_diff),
        quant_diff = as_tibble_row(quantile(acre_diff))
    )

ifph_inform %>%
    mutate(acre_diff = abs(Calculated.Acres - GIS_ACRES)) %>%
    mutate(area = st_area(geometry)/4047) %>%
    filter(acre_diff > 10) %>%
    arrange(desc(acre_diff)) %>%
    select(GIS_ACRES, Calculated.Acres, acre_diff, area, FIRE_YEAR_)
# some significant differences here. not ideal. 
# GIS_ACRES align with calculation based on multipolygon
```

# Adding coordinate data from inform records that don't match ifph

```{r}
tibble(ifph_inform) %>%
    group_by(is_inform) %>%
    summarize(n=n())

inform %>%
    mutate(unqe_match = UniqueFireIdentifier %in% ifph_inform$UNQE_FIRE_) %>%
    group_by(unqe_match) %>%
    summarize(n=n()) # so i'm not sure why this is 791 and not 819? seems strange.

# filtering to fire IDs not present in UNQE_FIRE_
# selecting only columns we will use in our analysis
inform_shp_lim <- inform_shp %>% 
    filter(!(UnqFrId %in% ifph_inform$UNQE_FIRE_)) %>% 
    select(UnqFrId, Clclt_A, Cntn_D_T, Cntr_D_T, Fr_Mg_C, FrOtDtT, Inc_T_C, AcrsTrb, Clndr_Y, geometry)

# selecting only matching cols
ifph_inform_lim <- ifph_inform %>%
    select(GIS_ACRES, UNQE_FIRE_, FIRE_YEAR_, is_ifph, Calculated.Acres, Containment.Date.Time, Control.Date.Time, Fire.Mgmt.Complexity, FireOutDateTime, Incident.Type.Category, AcresTribal, Calendar.Year, is_inform, geometry)

# renaming columns to match, adding NAs for cols that are ifph-specifc
inform_shp_lim <- inform_shp_lim %>%
    rename(c(
        UNQE_FIRE_ = UnqFrId,
        Calculated.Acres = Clclt_A,
        Containment.Date.Time = Cntn_D_T,
        Control.Date.Time = Cntr_D_T,
        Fire.Mgmt.Complexity = Fr_Mg_C,
        FireOutDateTime = FrOtDtT,
        Incident.Type.Category = Inc_T_C,
        AcresTribal = AcrsTrb,
        Calendar.Year = Clndr_Y
    )) %>%
    mutate(
        GIS_ACRES = NA,
        FIRE_YEAR_ = NA,
        is_ifph = FALSE,
        is_inform = TRUE
    )

# ensuring names all match
names(inform_shp_lim) %in% names(ifph_inform_lim)
names(ifph_inform_lim) %in% names(inform_shp_lim)

# checking dims - everything lines up
dim(inform_shp_lim)
dim(ifph_inform_lim)
dim(rbind(inform_shp_lim, ifph_inform_lim))

# creating full version with rbind
ifph_inform_full <- rbind(inform_shp_lim, ifph_inform_lim)

# so it turns out. you can't write multipolygon and point geometries to the same shapefile. so it'll just have to be two shapefiles. whatever.

ifph_inform_lim %>%
    filter(is.na(Fire.Mgmt.Complexity))

```

# Writing to shp/csv

```{r}
object.size(ifph_inform_full)

st_write(ifph_inform_lim, "data/ifph_inform_multipolygon.shp", append=FALSE)
st_write(inform_shp_lim, "data/ifph_inform_point.shp", append=FALSE)

ifph_inform_full_df <- tibble(ifph_inform_full) %>% select(-geometry)

object.size(ifph_inform_full_df)

write_csv(ifph_inform_full_df, "data/ifph_inform_full.csv")

# st_write(ifph_inform, "data/ifph_inform.shp")
# write_csv(ifph_inform, "data/ifph_inform.csv")
```
