---
title: "Data cleaning"
author: "Spencer Fiden"
date: "2026-05-29"
output: html_document
---

# Ingestion from download

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
library(ggplot2)
library(sf)
```

```{r}
ifph <- st_read("/Users/nikolefiden/Desktop/DATA-510/InterAgencyFirePerimeterHistory_All_Years_View/InteragencyFirePerimeterHistory.shp")
ifph <- st_transform(ifph, crs="WGS84")
ifph <- st_make_valid(ifph) # this takes some time to run
```

# Limiting to OR

Getting just OR from `usmap` to filter fires/native land to our area of interest with `st_intersects`. 

```{r}
states <- usmap::us_map()
or <- states %>% filter(abbr=="OR")
# transforming OR so the coordinate system matches
or <- st_transform(or, crs="WGS84")

or %>% 
    ggplot() +
    geom_sf() + 
    theme_minimal()
```

```{r}
lengths(ifph)

# creating intersection list for all polygons that intersect with OR border
# then selecting only those polygons
ifph_int = st_intersects(or, ifph)
dim(ifph_int)

ifph_or = ifph[unlist(ifph_int),]
dim(ifph_or)

ifph_or %>% 
    ggplot() + 
    geom_sf(data=or, aes(geometry=geom)) + 
    geom_sf(alpha=0.5, fill="firebrick") + 
    theme_minimal()

lengths(ifph_or)
```

## Creating dataframe

```{r}
ifph_df <- tibble(ifph_or)
# summaries/tests run much quicker on the tibble as it doesn't need to join geometries
```

# IFPH Cleaning

Will be running cleaning on both the sf and tibble (that's why it's there twice). 

## Time bounds

```{r}
# limiting FIRE_YEAR_ to 2015-2025 (inclusive)
ifph_or <- ifph_or %>%
    filter(FIRE_YEAR_ >= 2015, FIRE_YEAR_ <= 2025) 

ifph_df <- ifph_df %>%
    filter(FIRE_YEAR_ >= 2015, FIRE_YEAR_ <= 2025) 
    
ifph_df%>%
    select(FIRE_YEAR_) %>%
    summary()
```

```{r}
# converting INCIDENT = UNNAMED, UNKNOWN to NA
ifph_df %>%
    mutate(INCIDENT = toupper(INCIDENT)) %>%
    group_by(INCIDENT) %>%
    summarize(n = n()) %>%
    arrange(desc(n))

ifph_df <- ifph_df %>%
    mutate(INCIDENT = toupper(INCIDENT)) %>%
    mutate(INCIDENT = ifelse(INCIDENT %in% c("UNNAMED", "UNKNOWN"), NA, INCIDENT)) 

ifph_or <- ifph_or %>%
    mutate(INCIDENT = toupper(INCIDENT)) %>%
    mutate(INCIDENT = ifelse(INCIDENT %in% c("UNNAMED", "UNKNOWN"), NA, INCIDENT)) 

ifph_df %>%
    mutate(INCIDENT = toupper(INCIDENT)) %>%
    group_by(INCIDENT) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
```

```{r}
# converting DATE_CUR to actual datetime 
# not sure what the timezone is (presumably PST) but it doesn't matter for our purposes
ifph_df <- ifph_df %>%
    mutate(DATE_CUR = lubridate::ymd_hms(DATE_CUR))

ifph_or <- ifph_or %>%
    mutate(DATE_CUR = lubridate::ymd_hms(DATE_CUR))

# shows an error for the NAs that they "failed to parse" - it's fine
summary(is.na(ifph_df$DATE_CUR))
```

```{r}
# making FEATURE_CA into a factor
ifph_df <- ifph_df %>%
    mutate(FEATURE_CA = as_factor(FEATURE_CA)) 

ifph_or <- ifph_or %>%
    mutate(FEATURE_CA = as_factor(FEATURE_CA)) 

```

```{r}
# cleaning MAP_METHOD and turning into factor
print(n=30, ifph_df %>%
    mutate(MAP_METHOD = toupper(MAP_METHOD)) %>%
    group_by(MAP_METHOD) %>%
    summarize(n = n()) %>%
    arrange(desc(n)))

ifph_df <- ifph_df %>%
    mutate(MAP_METHOD = ifelse(MAP_METHOD %in% c("Mixed Method", "Mixed Collection Methods"), "Mixed Methods", MAP_METHOD),
        MAP_METHOD = ifelse(MAP_METHOD == "Digitized Other", "Digitized-Other", MAP_METHOD)) %>%
    mutate(MAP_METHOD = as_factor(MAP_METHOD))

# there are others that could be grouped (or are just the same) but for our purposes I'm not going to 
```

```{r}
# making SOURCE into a factor
ifph_df <- ifph_df %>%
    mutate(SOURCE = as_factor(SOURCE)) 

ifph_or <- ifph_or %>%
    mutate(SOURCE = as_factor(SOURCE)) 

```

```{r}
# making AGENCY into a factor
ifph_df <- ifph_df %>%
    mutate(AGENCY = as_factor(AGENCY)) 

ifph_or <- ifph_or %>%
    mutate(AGENCY = as_factor(AGENCY)) 

```

```{r}
# removing FIRE_YEAR col
ifph_df <- ifph_df %>%
    select(-FIRE_YEAR)

ifph_or <- ifph_or %>%
    select(-FIRE_YEAR)
```

# Writing to shp and csv

```{r}
object.size(ifph_df)
write_csv(ifph_df, "data/ifph_clean/ifph_clean.csv")

object.size(ifph_or)
st_write(ifph_or, "./data/ifph_clean/ifph_clean.shp", append=FALSE)
```
