---
title: "InFORM cleaning"
author: "Spencer Fiden"
date: "2026-05-29"
output: html_document
---

# InFORM ingestion & quality checks

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
library(ggplot2)
library(sf)
```

## Ingestion from download

```{r}
inform <- read_csv("/Users/nikolefiden/Desktop/DATA-510/InFORM_FireOccurrence_Public.csv")

```

```{r}
# replacing spaces in col names with "." 
inform <- inform %>% dplyr::rename_all(~ make.names(.))

```

## Overview 

```{r}
str(inform)
class(inform)
dim(inform)

names(inform) # that's a lot of columns. that's a LOT of columns
summary(inform)

```

## Column data types/summary/NA counts

There are 88 columns so this will take a long time.

``` {r}
# OBJECTID
class(inform$OBJECTID) # numeric
length(unique(inform$OBJECTID)) # all unique
summary(is.na(inform$OBJECTID)) # none missing

# ABCD.Misc
class(inform$ABCD.Misc)
summary(is.na(inform$ABCD.Misc)) # LOT of missing values
length(unique(inform$ABCD.Misc)) 
head(inform %>%
    group_by(ABCD.Misc) %>%
    summarize(n = n()) %>%
    arrange(desc(n)))
# 682 unique, a LOT of NAs, seems fine

# ADS Permission States
class(inform$ADS.Permission.State)
summary(is.na(inform$ADS.Permission.State)) # no missing values
length(unique(inform$ADS.Permission.State))
inform %>% 
    group_by(ADS.Permission.State) %>% 
    summarize(n=n())
# should be a factor

# Calculated.Acres
class(inform$Calculated.Acres) # numeric
summary(inform$Calculated.Acres) # no missing values
summary(is.na(inform$Calculated.Acres))
head(inform %>%
    group_by(Calculated.Acres) %>%
    summarize(n=n()) %>%
    arrange(Calculated.Acres))
# apparently one fire burned -1 acres. I dont think that's right and perhaps we should just remove that one

# Containment.Date.Time
class(inform$Containment.Date.Time) # character
head(inform %>% select(Containment.Date.Time)) # looks like a date/time
summary(is.na(inform$Containment.Date.Time)) # MANY missing values

# Control.Date.Time
class(inform$Control.Date.Time) # character
summary(is.na(inform$Control.Date.Time)) # many missing values
head(inform %>% select(Control.Date.Time)) # also looks like a date/time

# Created.By.System
class(inform$Created.By.System)
length(unique(inform$Created.By.System))
inform %>% 
    #mutate(Created.By.System = toupper(Created.By.System)) %>%
    group_by(Created.By.System) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should be a factor

# Created.On.Date.Time
class(inform$Created.On.Date.Time) # numeric??? ok
head(inform$Created.On.Date.Time) # is this like the posix thing? i will try lubridate
summary(is.na(inform$Created.On.Date.Time)) # none missing
length(unique(inform$Created.On.Date.Time)) # mostly unique, good

# Incident.Size
class(inform$Incident.Size) # numeric
summary(is.na(inform$Incident.Size)) # decent number of NA
summary(inform$Incident.Size)

# Discovery.Acres
class(inform$Discovery.Acres) # logical?
summary(inform$Discovery.Acres) # all. missing. hm. 
# not sure what to do about this?

# Dispatch.Center.ID
class(inform$Dispatch.Center.ID) # char
summary(is.na(inform$Dispatch.Center.ID)) # about split NA
head(inform$Dispatch.Center.ID)
length(unique(inform$Dispatch.Center.ID)) # only 241 unique, should probably be factor

# Estimated.Cost.To.Date
class(inform$Estimated.Cost.To.Date) # logical?
summary(is.na(inform$Estimated.Cost.To.Date)) # also all NA
# don't know what to do about this either

# Final.Acres
class(inform$Final.Acres) # logical?
summary(is.na(inform$Final.Acres)) # once again all NA

# Final.Fire.Report.Approved.By.Title
class(inform$Final.Fire.Report.Approved.By.Title) # char
summary(is.na(inform$Final.Fire.Report.Approved.By.Title)) # many NA
length(unique(inform$Final.Fire.Report.Approved.By.Title)) # abt 1000 unique
inform %>% 
    group_by(Final.Fire.Report.Approved.By.Title) %>% 
    summarize(n=n()) %>% 
    arrange(desc(n))
# should be a factor, needs to be cleaned as well (AFMO <- Acting FMO, etc.)
# the cleaning is deeply difficult. will return later if relevant

# Final.Fire.Report.Approved.By.Unit
class(inform$Final.Fire.Report.Approved.By.Unit) # logical?
summary(is.na(inform$Final.Fire.Report.Approved.By.Unit)) # all NA
# idk, probably remove

# Final.Fire.Report.Approved.Date
class(inform$Final.Fire.Report.Approved.Date) # char
summary(is.na(inform$Final.Fire.Report.Approved.Date)) # pretty split NA
head(inform$Final.Fire.Report.Approved.Date)
# should be turned into date format

# Fire.Behavior.General
class(inform$Fire.Behavior.General) # logical
summary(is.na(inform$Fire.Behavior.General)) # all NA

# FireCode
class(inform$FireCode) # char
summary(is.na(inform$FireCode)) # many NA
length(unique(inform$FireCode)) # why are they mostly unique. hey now.
inform %>% 
    group_by(FireCode) %>% 
    summarize(n=n()) %>% 
    arrange(desc(n))
# I don't really know what's going on here
# apparently it's something to do with cost information? but don't have a way to decode

# FireDepartmentID
class(inform$FireDepartmentID) # char
summary(is.na(inform$FireDepartmentID)) # mostly NA
length(unique(inform$FireDepartmentID)) # 831 unique
inform %>% 
    group_by(FireDepartmentID) %>% 
    summarize(n=n()) %>% 
    arrange(desc(n))
# should probably be factor, but seems lowkey useless

# Fire.Discovery.Date.Time
class(inform$Fire.Discovery.Date.Time) # char
summary(is.na(inform$Fire.Discovery.Date.Time)) # no NA
head(inform$Fire.Discovery.Date.Time)
# convert to datetime

# Fire.Mgmt.Complexity
length(unique(inform$Fire.Mgmt.Complexity))
unique(inform$Fire.Mgmt.Complexity)
inform %>%
    group_by(Fire.Mgmt.Complexity) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# 9 options, a lot of NA - should look into NA sizes (maybe small ones aren't rated like this)
# should be a factor

# FireOutDateTime
class(inform$FireOutDateTime) # char
summary(is.na(inform$FireOutDateTime)) # about half NA
head(inform$FireOutDateTime)
# should be converted to datet

# FS.Job.Code 
class(inform$FS.Job.Code) # char
summary(is.na(inform$FS.Job.Code)) # mostly NA
length(unique(inform$FS.Job.Code)) # only 78 unique, probably factor
inform %>%
    group_by(FS.Job.Code) %>%
    summarize(n = n()) %>%
    arrange(desc(n))

# FS.Override.Code
class(inform$FS.Override.Code) # char
summary(is.na(inform$FS.Override.Code)) # mostly NA
length(unique(inform$FS.Override.Code)) # only 221, probably factor
inform %>%
    group_by(FS.Override.Code) %>%
    summarize(n = n()) %>%
    arrange(desc(n))

# GACC
class(inform$GACC) # char
summary(is.na(inform$GACC)) # only 27 NA
inform %>% 
    group_by(GACC) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should be factor

# Incident.Name
class(inform$Incident.Name) # char
summary(is.na(inform$Incident.Name)) # no NA
inform %>% 
    group_by(Incident.Name) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should not be a factor

# Incident.Short.Description
class(inform$Incident.Short.Description) # logical
summary(is.na(inform$Incident.Short.Description)) # all NA
# idk what to do with her

# Incident.Type.Category
class(inform$Incident.Type.Category) # char
length(unique(inform$Incident.Type.Category))
inform %>% 
    group_by(Incident.Type.Category) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# should be factor - only WF or RX

# Incident.Type.Kind
class(inform$Incident.Type.Kind) # char
length(unique(inform$Incident.Type.Kind)) # only 1?
summary(is.na(inform$Incident.Type.Kind)) # no NA
inform %>% 
    group_by(Incident.Type.Kind) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# it's only FI, presumably for fire. possibly some of the excluded columns have another value. 

# Initial.Latitude
class(inform$Initial.Latitude) # numeric
summary(inform$Initial.Latitude) # 30k NA, range -32 to 123

# Initial.Longitude
class(inform$Initial.Longitude) # numeric
summary(inform$Initial.Longitude) # 30k NA, range -180 to 114

# Initial.Response.Date.Time
class(inform$Initial.Response.Date.Time) # char
summary(is.na(inform$Initial.Response.Date.Time)) # many NA
head(inform$Initial.Response.Date.Time)
# should be converted to datetime

# Is.Fire.Cause.Investigated
class(inform$Is.Fire.Cause.Investigated) # numeric?
summary(inform$Is.Fire.Cause.Investigated) # many NA, seems like a boolean
unique(inform$Is.Fire.Cause.Investigated)
# should be logical

# Is.FS.Assisted
class(inform$Is.FS.Assisted) # numeric
summary(inform$Is.FS.Assisted) # many NA, also boolean
unique(inform$Is.FS.Assisted)
# should be logical

# Is.Reimbursable
class(inform$Is.Reimbursable) # logical
summary(inform$Is.Reimbursable) # all NA

# Is.Trespass
class(inform$Is.Trespass) # numeric
summary(inform$Is.Trespass) # also seems to be bool, many NA
unique(inform$Is.Trespass)
# should be logical

# Local.Incident.Identifier
class(inform$Local.Incident.Identifier) # char
summary(is.na(inform$Local.Incident.Identifier)) # all present
length(unique(inform$Local.Incident.Identifier)) # mostly unique, char is good

# Modified.On.Date.Time
class(inform$Modified.On.Date.Time) # char
summary(is.na(inform$Modified.On.Date.Time)) # all present
head(inform$Modified.On.Date.Time)
# convert to datetime

# Percent.Contained
class(inform$Percent.Contained) # logical
summary(is.na(inform$Percent.Contained)) # all NA

# City
class(inform$City) # char
summary(is.na(inform$City)) # mostly missing
length(unique(inform$City)) # motsly unique
inform %>% 
    group_by(City) %>%
    summarize(n=n()) %>%
    arrange(desc(n))

# POO.County
class(inform$POO.County) # char
summary(is.na(inform$POO.County)) # only 16 NA
length(unique(inform$POO.County))
inform %>% 
    group_by(POO.County) %>%
    summarize(n=n()) %>%
    arrange(desc(n))

# POODispatchCenterID
class(inform$POODispatchCenterID) # char
summary(is.na(inform$POODispatchCenterID)) # only 89 NA
length(unique(inform$POODispatchCenterID)) # only 172 unique
inform %>% 
    group_by(POODispatchCenterID) %>%
    summarize(n=n()) %>%
    arrange(desc(n))

# POO.Fips
class(inform$POO.Fips) # char
summary(is.na(inform$POO.Fips)) # about half NA
length(unique(inform$POO.Fips))
inform %>% 
    group_by(POO.Fips) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# 5 digits, likely county codes

# POO.Jurisdictional.Agency
class(inform$POO.Jurisdictional.Agency) # char
summary(is.na(inform$POO.Jurisdictional.Agency)) # about half NA
inform %>% 
    group_by(POO.Jurisdictional.Agency) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# 64 unique, this may actually be useful!
# should be a factor

# POO.Jurisdictional.Unit
class(inform$POO.Jurisdictional.Unit) # char
summary(is.na(inform$POO.Jurisdictional.Unit)) # about half NA
inform %>% 
    group_by(POO.Jurisdictional.Unit) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# many unique

# POO.Jurisdictional.Unit.Parent.Unit
class(inform$POO.Jurisdictional.Unit.Parent.Unit) # logical
summary(is.na(inform$POO.Jurisdictional.Unit.Parent.Unit)) # all NA

# POOLandownerCategory
class(inform$POOLandownerCategory) # char
summary(is.na(inform$POOLandownerCategory)) # few NA
length(unique(inform$POOLandownerCategory)) # 21 unique
inform %>% 
    group_by(POOLandownerCategory) %>%
    summarize(n=n()) %>%
    arrange(desc(n)) %>%
    print(n=21)
# convert to factor, could be useful!

# POOLandownerKind
class(inform$POOLandownerKind) # char
summary(is.na(inform$POOLandownerKind)) # ~400 missing
length(unique(inform$POOLandownerKind)) # only 8
inform %>% 
    group_by(POOLandownerKind) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# convert to factor

# POO.Protecting.Agency
class(inform$POO.Protecting.Agency) # char
summary(is.na(inform$POO.Protecting.Agency)) # many NA
length(unique(inform$POO.Protecting.Agency)) # 58 unique
inform %>% 
    group_by(POO.Protecting.Agency) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# convert to factor

# POO.Protecting.Unit
class(inform$POO.Protecting.Unit) # char
summary(is.na(inform$POO.Protecting.Unit)) # some NA
length(unique(inform$POO.Protecting.Unit)) # ~1600 unique
inform %>% 
    group_by(POO.Protecting.Unit) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# I don't know what any of this means

# POO.State
class(inform$POO.State) # char
length(unique(inform$POO.State)) # 58 unique
inform %>% 
    group_by(POO.State) %>%
    summarize(n=n()) %>%
    arrange(POO.State) # a few in MX
# convert to factor

# Predominant.Fuel.Group
class(inform$Predominant.Fuel.Group) # char
length(unique(inform$Predominant.Fuel.Group)) # 7 unique
inform %>% 
    group_by(Predominant.Fuel.Group) %>%
    summarize(n=n()) %>%
    arrange(desc(n)) # many NA, could be useful though
# convert to factor

# Predominant.Fuel.Model
class(inform$Predominant.Fuel.Model) # char
length(unique(inform$Predominant.Fuel.Model)) # 46 unique
inform %>% 
    group_by(Predominant.Fuel.Model) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# i don't know what any of that means!

# UniqueFireIdentifier
class(inform$UniqueFireIdentifier) # char
summary(is.na(inform$UniqueFireIdentifier)) # ALL PRESENT this is excellent news friends
length(unique(inform$UniqueFireIdentifier)) # a few duplicates apparently?
inform %>% 
    group_by(UniqueFireIdentifier) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# not sure about the duplicates but otherwise this looks AWESOME

# FORID
class(inform$FORID) # char
summary(is.na(inform$FORID)) # all present
length(unique(inform$FORID)) # a few duplicates

# Initial.Response.Agencies
class(inform$Initial.Response.Agencies) # char
summary(is.na(inform$Initial.Response.Agencies)) # lots missing
length(unique(inform$Initial.Response.Agencies)) # ~1000
inform %>% 
    group_by(Initial.Response.Agencies) %>%
    summarize(n=n()) %>%
    arrange(Initial.Response.Agencies)
# should be cleaned up if we're going to use it, comma separated for doubles but at least alphabetical

# Fire.Cause
class(inform$Fire.Cause) # numeric?
summary(is.na(inform$Fire.Cause)) # some missing
length(unique(inform$Fire.Cause)) # only 4
inform %>% 
    group_by(Fire.Cause) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# ok. well. wish i knew what that meant.

# Fire.Cause.General
class(inform$Fire.Cause.General) # numeric?
summary(is.na(inform$Fire.Cause.General)) # many missing
length(unique(inform$Fire.Cause.General)) # 14 unique
inform %>% 
    group_by(Fire.Cause.General) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# it's numbers! wish i knew what they meant!

# Fire.Cause.Specific
class(inform$Fire.Cause.Specific) # numeric?
summary(is.na(inform$Fire.Cause.Specific)) # many missing
length(unique(inform$Fire.Cause.Specific)) # 77 unique
inform %>% 
    group_by(Fire.Cause.Specific) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# once again saying I wish I knew what these numbers meant

# Fire.Cause.Specific.Detail
class(inform$Fire.Cause.Specific.Detail) # numeric?
summary(is.na(inform$Fire.Cause.Specific.Detail)) # mostly missing
length(unique(inform$Fire.Cause.Specific.Detail)) # 56 unique
inform %>% 
    group_by(Fire.Cause.Specific.Detail) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# again, wish I knew what it meant

# Fire.Cause.Age.Category
class(inform$Fire.Cause.Age.Category) # numeric
summary(is.na(inform$Fire.Cause.Age.Category)) # many missing
length(unique(inform$Fire.Cause.Age.Category)) # only 5
inform %>% 
    group_by(Fire.Cause.Age.Category) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# yep. wish I knew what it meant.

# Fire.Cause.Activity.Group
class(inform$Fire.Cause.Activity.Group) # numeric
summary(is.na(inform$Fire.Cause.Activity.Group)) # mostly missing
length(unique(inform$Fire.Cause.Activity.Group)) # 20 unique
inform %>% 
    group_by(Fire.Cause.Activity.Group) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# more meaningless undefined numbers. thanks NIFC this is awesome

# GlobalID 
class(inform$GlobalID) # char
summary(is.na(inform$GlobalID)) # all present
length(unique(inform$GlobalID)) # all unique!
head(inform$GlobalID)
# yep looks fine to me

# IsCauseProhibited
class(inform$IsCauseProhibited) # numeric
inform %>% 
    group_by(IsCauseProhibited) %>%
    summarize(n=n()) %>%
    arrange(desc(n)) # mostly missing
# convert to logical

# ModifiedBySystem
class(inform$ModifiedBySystem) # char
summary(is.na(inform$ModifiedBySystem)) # about half NA
length(unique(inform$ModifiedBySystem)) # 21 unique
inform %>% 
    group_by(ModifiedBySystem) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# convert to factor

# Related.Irwin.IDs
class(inform$Related.Irwin.IDs) # char
summary(is.na(inform$Related.Irwin.IDs)) # about half NA
length(unique(inform$Related.Irwin.IDs)) # mostly unique
head(inform$Related.Irwin.IDs) # yep looks fine to me

# Status
class(inform$Status) # char
summary(is.na(inform$Status)) # all present
length(unique(inform$Status)) # 3 unique
inform %>% 
    group_by(Status) %>%
    summarize(n=n()) %>%
    arrange(desc(n))
# factor - Incomplete, Certified, Complete

# AcresBIA
class(inform$AcresBIA) # numeric
summary(inform$AcresBIA)

# AcresBLM
class(inform$AcresBLM) # numeric
summary(inform$AcresBLM)

# AcresBOR
class(inform$AcresBOR) # numeric
summary(inform$AcresBOR)

# AcresDOD
class(inform$AcresDOD) # numeric
summary(inform$AcresDOD)

# AcresDOE
class(inform$AcresDOE) # numeric
summary(inform$AcresDOE)

# AcresNPS
class(inform$AcresNPS) # numeric
summary(inform$AcresNPS)

# AcresUSFS
class(inform$AcresUSFS) # numeric
summary(inform$AcresUSFS) # min -1? seems. wrong. 

# AcresUSFWS
class(inform$AcresUSFWS) # numeric
summary(inform$AcresUSFWS) # min also -1

# AcresForeign 
class(inform$AcresForeign) # numeric
summary(inform$AcresForeign) 

# AcresTribal
class(inform$AcresTribal) # numeric
summary(inform$AcresTribal) 

# AcresCity
class(inform$AcresCity) # numeric
summary(inform$AcresCity) 

# AcresCounty
class(inform$AcresCounty) # numeric
summary(inform$AcresCounty) 

# AcresState
class(inform$AcresState) # numeric
summary(inform$AcresState) 

# AcresPrivate
class(inform$AcresPrivate) # numeric
summary(inform$AcresPrivate) # min -0.6

# AcresANCSA
class(inform$AcresANCSA) # numeric
summary(inform$AcresANCSA)

# AcresOtherLocal
class(inform$AcresOtherLocal) # numeric
summary(inform$AcresOtherLocal)

# AcresOtherFederal
class(inform$AcresOtherFederal) # numeric
summary(inform$AcresOtherFederal) # min -3.05

# Fire.Cause.Comments
class(inform$Fire.Cause.Comments) # char
summary(is.na(inform$Fire.Cause.Comments)) # mostly NA
length(unique(inform$Fire.Cause.Comments)) # nearly 10k unique
inform %>%
    group_by(Fire.Cause.Comments) %>%
    summarize(n = n()) %>%
    arrange(desc(n))
# needs to be cleaned badly - N/A, Unknown, unknown, etc. 

# Calendar.Year
summary(inform$Calendar.Year)

# x
class(inform$x) # numeric
summary(is.na(inform$x)) # all present
summary(inform$x)
# clean. don't know what it means. 

# y
class(inform$y) # numeric
summary(is.na(inform$y)) # all present
summary(inform$y)

```

# Missingness

```{r}
inform_missing <- inform %>%
    gather(key = "key", value = "val") %>%
    mutate(is_missing = is.na(val)) %>%
    group_by(key, is_missing) %>%
    summarize(num_missing = n()) %>%
    filter(is_missing==T) %>%
    select(-is_missing) %>%
    arrange(desc(num_missing))
    
```

```{r}
inform_missing %>% 
    ggplot(aes(reorder(key, num_missing), num_missing)) +
    geom_bar(stat="identity") +
    geom_hline(yintercept=pull(count(inform))) +
    theme_minimal() +
    coord_flip()
```


```{r}
inform_missing_pct <- inform %>%
    gather(key = "key", value = "val") %>%
    mutate(is_missing = is.na(val)) %>%
    group_by(key) %>%
    mutate(total = n()) %>%
    group_by(key, total, is_missing) %>%
    summarise(num_na = n()) %>%
    mutate(pct = num_na / total)

```


```{r}
levels <-
    (inform_missing_pct %>% filter(is_missing == F) %>% arrange(pct))$key

inform_missing_pct %>%
    ggplot(aes(key, pct, fill=is_missing)) +
    geom_bar(stat="identity") +
    scale_x_discrete(limits=levels) +
    scale_y_continuous(labels=scales::percent) +
    scale_fill_manual(name = "", values = c('steelblue', 'tomato3'), labels = c("Present", "Missing")) +
    coord_flip() +
    theme_minimal()

```


```{r}
# comparing the assorted time/date columns:
# Modified.On.Date.Time
# Fire.Discovery.Date.Time
# Created.On.Date.Time
# Calendar.Year
# Containment.Date.Time
# FireOutDateTime
# Final.Fire.Report.Approved.Date
# Control.Date.Time
inform %>%
    select(
        Modified.On.Date.Time,
        Fire.Discovery.Date.Time,
        Created.On.Date.Time,
        Calendar.Year,
        Containment.Date.Time,
        FireOutDateTime,
        Final.Fire.Report.Approved.Date,
        Control.Date.Time) %>%
    summarise(
        #across(everything(), ~ sum(is.na(.x))),
        across(everything(), ~ sum(date(.x)==ymd(19700101)))
    ) %>%
    pivot_longer(cols=everything(), names_to="column", values_to="na_count")

summary(inform$Fire.Discovery.Date.Time)
head(inform$Fire.Discovery.Date.Time)

inform %>%
    select(
        #Modified.On.Date.Time,
        Fire.Discovery.Date.Time,
        #Created.On.Date.Time,
        Calendar.Year,
        Containment.Date.Time,
        FireOutDateTime,
        #Final.Fire.Report.Approved.Date,
        #Control.Date.Time
    ) %>% 
    group_by(Calendar.Year) %>%
    summarize(
        calyear_firedisc = sum(year(Fire.Discovery.Date.Time) != Calendar.Year),
        calyear_na = sum(is.na(Calendar.Year))
    ) %>%
    arrange(desc(calyear_firedisc))

inform %>%
    select(#Modified.On.Date.Time,
        Fire.Discovery.Date.Time,
        #Created.On.Date.Time,
        Calendar.Year,
        Containment.Date.Time,
        FireOutDateTime,
        #Final.Fire.Report.Approved.Date,
        #Control.Date.Time
    ) %>%
    filter(is.na(Calendar.Year))

summary(is.na(inform$Calendar.Year))

```