---
title: "InFORM cleaning"
author: "Spencer Fiden"
date: "2026-05-29"
output: html_document
---

# InFORM ingestion & quality checks

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
library(ggplot2)
library(sf)
```

## Ingestion from download

```{r}
inform <- read_csv("/Users/nikolefiden/Desktop/DATA-510/InFORM_FireOccurrence_Public.csv")

```

```{r}
# replacing spaces in col names with "." 
inform <- inform %>% dplyr::rename_all(~ make.names(.))

```

## Overview 

```{r}
str(inform)
class(inform)
dim(inform)

names(inform) # that's a lot of columns. that's a LOT of columns
summary(inform)

head(inform %>% arrange(desc(`Calendar.Year`)) %>% select(`Calendar.Year`))
# one year marked as 2121 - probably actually 2021

```

## Cleaning

```{r}
# limiting Calendar.Year to just 2015-2026
# two missing values for Calendar.Year, but can impute from Fire.Discovery.Date.Time
inform <- inform %>%
    mutate(
        Calendar.Year = ifelse(is.na(Calendar.Year), 
                        date(Fire.Discovery.Date.Time), 
                        Calendar.Year)
    ) %>%
    filter(Calendar.Year >= 2015, Calendar.Year <= 2026)

inform %>%
    group_by(Calendar.Year) %>%
    summarize(n = n())
```

```{r}
# changing ADS.Permission.State to a factor
inform <- inform %>%
    mutate(ADS.Permission.State = as_factor(ADS.Permission.State))
```

```{r}
# removing anomaly -1 acres burned fire
inform <- inform %>%
    filter(Calculated.Acres >= 0)
```

```{r}
# converting Containment.Date.Time to a date
inform <- inform %>%
    mutate(Containment.Date.Time = lubridate::mdy_hms(Containment.Date.Time))

summary(inform$Containment.Date.Time)
# hey why is there one for 1970. hey.
inform %>% select(Containment.Date.Time, Calendar.Year, Fire.Discovery.Date.Time) %>% 
    group_by(Containment.Date.Time, Calendar.Year) %>%
    filter(!is.na(Containment.Date.Time)) %>%
    summarize(n=n()) %>%
    arrange(Containment.Date.Time)

# 1970-01-01 has to be a placeholder. changing to NA
inform %>% 
    mutate(Containment.Date.Time = na_if(Containment.Date.Time, as_datetime("1970-01-01 00:00:00"))) %>%
    group_by(Containment.Date.Time) %>%
    summarize(n=n()) %>%
    arrange(Containment.Date.Time)

inform <- inform %>% 
    mutate(Containment.Date.Time = na_if(Containment.Date.Time, as_datetime("1970-01-01 00:00:00")))

```

```{r}
# converting Control.Date.Time to a date
inform <- inform %>%
    mutate(Control.Date.Time = lubridate::mdy_hms(Control.Date.Time))

summary(inform$Control.Date.Time)
# these are not marked 1970! go team
```

```{r}
# Created.By.System -> factor
inform <- inform %>%
    mutate(Created.By.System = as_factor(Created.By.System))
```

```{r}
# converting Created.On.Date.Time to datetime
inform <- inform %>%
    mutate(Created.On.Date.Time = as_datetime(Created.On.Date.Time/1000)) 

inform %>%
    select(Created.On.Date.Time)

```

```{r}
# converting Dispatch.Center.ID to factor
inform <- inform %>% 
    mutate(Dispatch.Center.ID = as_factor(Dispatch.Center.ID))

inform %>% 
    group_by(Dispatch.Center.ID) %>% 
    summarize(n = n()) %>% 
    arrange(desc(n))
```

```{r}
# IN PROGRESS
# this is taking a long long long time
# so. going to move on for now

inform_report_title <- interim_inform %>% 
    #mutate(Final.Fire.Report.Approved.By.Title = toupper(Final.Fire.Report.Approved.By.Title)) %>%
    group_by(Final.Fire.Report.Approved.By.Title) %>% 
    summarize(n=n()) %>% 
    arrange(Final.Fire.Report.Approved.By.Title)

print(inform_report_title[60:200, 1:2], n=100)
length(unique(inform_report_title$Final.Fire.Report.Approved.By.Title))
length(unique(inform$Final.Fire.Report.Approved.By.Title))

interim_inform <- inform %>%
    mutate(
        # (Supervisory) Range Tech
        Final.Fire.Report.Approved.By.Title = ifelse(
            Final.Fire.Report.Approved.By.Title %in% c(
                "(Supervisor) Range Tech", 
                "(Supervisory Range Tech", 
                "(Supervisory) Range Tech)", 
                "(Supervsory) Range Tech"
            ), 
            "(Supervisory) Range Tech", Final.Fire.Report.Approved.By.Title),
        # Acting AFMO
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACTING AFMO", 
                "ACTING  AFMO",
                "AFMO (ACTING)", 
                "ACT AFMO",
                "ACTING ASSISTANT FMO", 
                "ACTING ASST. FMO",
                "ACTINT AFMO"
            ),
            "Acting AFMO", Final.Fire.Report.Approved.By.Title
        ),
        # Acting FMO
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACT FMO", 
                "ACTIG FIRE MANAGEMENT OFFICER", 
                "ACTING FMMO", 
                "ACTING FIRE MANAGEMENT OFFICE", 
                "ACTING FIRE MANAGEMENT OFFICER", 
                "ACTING FIRE MANAGEMENT OFFIER", 
                "ACTING FIRE MANAGEMTN", 
                "ACTING FIRE MANAGEMTN OFICER", 
                "ACTING FIRE MANAGMENT OFFICER", 
                "ACTING FIRE MGMT OFFICER", 
                "ACTING FMO", 
                "ACTING FIRE MANAGEMTN OFFICER", 
                "ACTING FRIE MANAGEMENT OFFICER", 
                "ACTING-FMO"
            ),
            "Acting FMO", Final.Fire.Report.Approved.By.Title
        ),
        # Acting Superintendent
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACTING SUPERINTENDENT", 
                "ACTING SUPT", 
                "ACTING SUPT."
            ),
            "Acting Superintendent", Final.Fire.Report.Approved.By.Title
        ),
        # Acting Zone FMO
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ACTING ZONE FMO", 
                "ACTING ZONE FIRE MANAGEMENT OFFICER", 
                "ACTING ZONE FIRE MGMT OFFICER",
                "ACTING ZONE FIRE MGT OFFICER",
                "ACTING ZONE FRIE MGMT OFFICER"
            ),
            "Acting Zone FMO", Final.Fire.Report.Approved.By.Title
        ),
        # AFMO (Assistant Fire Management Officer)
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "AFMO",
                "AMFO",
                "ASSIST FMO",
                "ASSISTANT FMO",
                "ASSISTANT FIRE MANAGEMENT OFFI",
                "ASST FIRE MANAGEMENT OFFICER",
                "ASST. FIRE MANAGEMENT OFFICER"
            ),
            "AFMO", Final.Fire.Report.Approved.By.Title
        ),
        # AFMO Ops
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "AFMO OPS",
                "AFMO  OPS",
                "AFMO OPS.",
                "AFMO OPERATIONS",
                "AFMO. OPS",
                "AFMO - OPERATIONS"
            ),
            "AFMO Ops", Final.Fire.Report.Approved.By.Title
        ),
        # Asst. District Forester
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "ASST DISCT. FORESTER",
                "ASST DISTRICT FORESTER",
                "ASST. DISTRICT FORESTER",
                "ASST, DISPTRICT FORESTER",
                "ASST, DISTC FORESTER",
                "ASST, DISTRICT FORESTER",
                "ASST. DISC FORESTER",
                "ASST. DISCTRIC FORESTER",
                "ASST. DITRICT FORESTER",
                "ASST, DISTRICT FOREST",
                "ASST. DISCTRIC FORESTER"
            ), "Asst. District Forester", Final.Fire.Report.Approved.By.Title
        ),
        # ASFT
        Final.Fire.Report.Approved.By.Title = ifelse(
            toupper(Final.Fire.Report.Approved.By.Title) %in% c(
                "A.S.F.T", 
                "A.S.F.T.", 
                "ASFT"
            ),
            "ASFT", Final.Fire.Report.Approved.By.Title
        )
    )

```

```{r}
# converting Final.Fire.Report.Approved.Date to datetime
inform %>% 
    select(Final.Fire.Report.Approved.Date) 

inform <- inform %>%
    mutate(Final.Fire.Report.Approved.Date = mdy_hms(Final.Fire.Report.Approved.Date))
```

```{r}
# converting Fire.Discovery.Date.Time to datetime
inform %>% 
    select(Fire.Discovery.Date.Time)

inform <- inform %>%
    mutate(Fire.Discovery.Date.Time = mdy_hms(Fire.Discovery.Date.Time))
```

```{r}
# converting Fire.Mgmt.Complexity to factor
inform %>% 
    group_by(Fire.Mgmt.Complexity) %>%
    summarize(n = n())

inform <- inform %>%
    mutate(Fire.Mgmt.Complexity = factor(Fire.Mgmt.Complexity, 
        levels=c(
            "Type 1 Incident",
            "Type 1 Prescribed Fire",
            "Type 2 Incident",
            "Type 3 Incident", 
            "Type 3 Prescribed Fire",
            "Type 4 Incident",
            "Type 5 Incident",
            "Complex Incident"
        ), ordered=TRUE))
```

```{r}
# converting FireOutDateTime to datetime
inform %>% 
    select(FireOutDateTime)

inform <- inform %>%
    mutate(FireOutDateTime = mdy_hms(FireOutDateTime))
```

```{r}
# converting FS.Job.Code to factor
inform <- inform %>%
    mutate(FS.Job.Code = as_factor(FS.Job.Code))

```

```{r}
# converting FS.Override.Code to factor
inform <- inform %>%
    mutate(FS.Override.Code = as_factor(FS.Override.Code))

```

```{r}
# converting GACC to factor
inform <- inform %>%
    mutate(GACC = as_factor(GACC))

```

```{r}
# converting Incident.Type.Category to factor
inform <- inform %>%
    mutate(Incident.Type.Category = as_factor(Incident.Type.Category))

```

```{r}
# converting Initial.Response.Date.Time to datetime
inform %>%
    select(Initial.Response.Date.Time)

inform <- inform %>%
    mutate(Initial.Response.Date.Time = mdy_hms(Initial.Response.Date.Time))

```

```{r}
# convert Is.Fire.Cause.Investigated to bool
inform %>% 
    select(Is.Fire.Cause.Investigated) 

inform <- inform %>% 
    mutate(Is.Fire.Cause.Investigated = as.logical(Is.Fire.Cause.Investigated))

```

```{r}
# convert Is.FS.Assisted to bool
inform %>% 
    select(Is.FS.Assisted) 

inform <- inform %>% 
    mutate(Is.FS.Assisted = as.logical(Is.FS.Assisted))

```

```{r}
# convert Is.Trespass to bool
inform %>% 
    select(Is.Trespass) 

inform <- inform %>% 
    mutate(Is.Trespass = as.logical(Is.Trespass))

```

```{r}
# converting Modified.On.Date.Time to datetime
inform %>%
    select(Modified.On.Date.Time)

inform <- inform %>%
    mutate(Modified.On.Date.Time = mdy_hms(Modified.On.Date.Time))

```

```{r}
# converting POO.Fips to numeric
inform <- inform %>%
    mutate(POO.Fips = as.numeric(POO.Fips)) 

```

```{r}
# converting POO.Jurisdictional.Agency to factor
inform <- inform %>%
    mutate(POO.Jurisdictional.Agency = as_factor(POO.Jurisdictional.Agency))

```

```{r}
# converting POOLandownerCategory to factor
inform <- inform %>%
    mutate(POOLandownerCategory = as_factor(POOLandownerCategory))
```

```{r}
# converting POOLandownerKind to factor
inform <- inform %>%
    mutate(POOLandownerKind = as_factor(POOLandownerKind))
```

```{r}
# converting POO.Protecting.Agency to factor
inform <- inform %>%
    mutate(POO.Protecting.Agency = as_factor(POO.Protecting.Agency))
```

```{r}
# converting POO.State to factor
inform <- inform %>%
    mutate(POO.State = as_factor(POO.State))
```

```{r}
# converting Predominant.Fuel.Group to factor
inform <- inform %>%
    mutate(Predominant.Fuel.Group = as_factor(Predominant.Fuel.Group))
```

```{r}
# convert IsCauseProhibited to bool
inform <- inform %>% 
    mutate(IsCauseProhibited = as.logical(IsCauseProhibited))
```

```{r}
# converting ModifiedBySystem to factor
inform <- inform %>%
    mutate(ModifiedBySystem = as_factor(ModifiedBySystem))
```

```{r}
# converting Status to factor
inform <- inform %>%
    mutate(Status = as_factor(Status))
```

```{r}
# cleaning Fire.Cause.Comments
inform %>%
    group_by(Fire.Cause.Comments) %>%
    summarize(n = n()) %>%
    arrange(Fire.Cause.Comments)

inform %>%
    mutate(Fire.Cause.Comments = str_remove(Fire.Cause.Comments, "\n")
    ) %>%
    mutate(Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("N/A", "NA", "", "*", ".", "-", ".."), NA, Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c(
                "UNKNOWN", 
                "UNDETERMINED", 
                "UNK", 
                "UN", 
                "UNKOWN", 
                "UNKNOWN CAUSE",
                "UK"
           ), "Unknown", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("UNDER INVESTIGATION"), "Under investigation", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NOT INVESTIGATED"), "Not investigated", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NONE"), "None", Fire.Cause.Comments)
    ) %>%
    group_by(Fire.Cause.Comments) %>%
    summarize(n = n()) %>%
    arrange(desc(n)) %>%
    print(n=25)

inform <- inform %>% 
    mutate(Fire.Cause.Comments = str_remove(Fire.Cause.Comments, "\n")) %>%
    mutate(Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("N/A", "NA", "", "*", ".", "-", ".."), NA, Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c(
                "UNKNOWN", 
                "UNDETERMINED", 
                "UNK", 
                "UN", 
                "UNKOWN", 
                "UNKNOWN CAUSE",
                "UK"
           ), "Unknown", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("UNDER INVESTIGATION"), "Under investigation", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NOT INVESTIGATED"), "Not investigated", Fire.Cause.Comments),
           Fire.Cause.Comments = ifelse(toupper(Fire.Cause.Comments) %in% c("NONE"), "None", Fire.Cause.Comments)
    )
```