
Using Python to do a random forest classification

```{python}
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
```

```{python}
# import data with pandas
tg = pd.read_csv("../data/processed_grid/time_grid.csv")
tg.head()
```

## Creating size_class feature

The National Wildfire Coordinating Group (NWCG) has size classifications for wildfires ([link](https://www.nwcg.gov/node/1737420)). We may limit smaller fires (which may represent minor incidents and not actual wildfires), so adding a factor for this classification.

Class A - one-fourth acre or less;
Class B - more than one-fourth acre, but less than 10 acres;
Class C - 10 acres or more, but less than 100 acres;
Class D - 100 acres or more, but less than 300 acres;
Class E - 300 acres or more, but less than 1,000 acres;
Class F - 1,000 acres or more, but less than 5,000 acres;
Class G - 5,000 acres or more.

```{python}
# categorizing max_acres into class bins
bins = [0, 0.01, 0.25, 9.99, 99.99, 299.99, 999.99, 4999.99, 9000000]
labels = ["No fire", "Class A", "Class B", "Class C", "Class D", "Class E", "Class F", "Class G"]

tg['size_class'] = pd.cut(x = tg['max_acres'], bins = bins, labels = labels, include_lowest=True)
```

# Random Forest Classifier

```{python}
# more libraries
# %pip install scikit-learn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_classification
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold
)
from sklearn.metrics import accuracy_score, f1_score

```

## Cumulative sum RX

### Model

```{python}
# label encoder for target variable
label_encoder = LabelEncoder()
target = label_encoder.fit_transform(tg["size_class"])

data = tg[['is_ndgn', 'plnt_sm', 'rx_csum']]

X_train, X_test, y_train, y_test = train_test_split(
    data, target, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, pred):.4f}")
```

### Feature Importance

```{python}
# %pip install shap
import shap
```

```{python}
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(data)

# calculate mean absolute SHAP values
shap_summary = np.abs(shap_values).mean(axis=0)

# list to store shap values for each feature
shap_summary_list = [np.mean(shap_summary[i]) for i in range(shap_summary.shape[0])]

# list of feature names
feature_names = ['is_ndgn', 'plnt_sm', 'rx_csum']

# dataframe using 1d list of SHAP values
shap_summary_df = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list})

print(shap_summary_df)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': rf.feature_importances_})

print(feature_imp_df)
```

### Metrics

```{python}
from sklearn.metrics import confusion_matrix, classification_report

```

```{python}
n_labs = np.arange(7,-1,-1)

c_matrix = confusion_matrix(y_test, pred, labels=n_labs)
print(c_matrix)
```

```{python}
sns.heatmap(c_matrix, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report = classification_report(y_test, pred, labels=n_labs, target_names=labels)
print(report)

```

## Prior RX and current RX

### Model

```{python}
tg['rx_prev'] = tg['rx_csum'] - tg['n_rx']
```

```{python}
# including cumulative sum of rx fires from previous years and number of rx fires in current year
data_rx2 = tg[['is_ndgn', 'plnt_sm', 'n_rx', 'rx_prev']]

X_train_rx2, X_test_rx2, y_train_rx2, y_test_rx2 = train_test_split(
    data_rx2, target, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_rx2 = RandomForestClassifier(random_state=42)

rf_rx2.fit(X_train_rx2, y_train_rx2)

pred_rx2 = rf_rx2.predict(X_test_rx2)

print(f"Accuracy: {accuracy_score(y_test_rx2, pred_rx2):.4f}")
```

### Feature Importance

```{python}
explainer_rx2 = shap.TreeExplainer(rf_rx2)
shap_values_rx2 = explainer_rx2.shap_values(data_rx2)

# calculate mean absolute SHAP values
shap_summary_rx2 = np.abs(shap_values_rx2).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_rx2 = [np.mean(shap_summary_rx2[i]) for i in range(shap_summary_rx2.shape[0])]

# list of feature names
feature_names_rx2 = ['is_ndgn', 'plnt_sm', 'n_rx', 'rx_prev']

# dataframe using 1d list of SHAP values
shap_summary_df_rx2 = pd.DataFrame({'Feature': feature_names_rx2, 'SHAP values': shap_summary_list_rx2})

print(shap_summary_df_rx2)
```

More importance for rx_prev than n_rx.

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_rx2 = pd.DataFrame({'Feature': feature_names_rx2, 'Gini Importance': rf_rx2.feature_importances_})

print(feature_imp_df_rx2)
```

### Metrics

```{python}
c_matrix_rx2 = confusion_matrix(y_test_rx2, pred_rx2, labels=n_labs)
print(c_matrix_rx2)
```

```{python}
sns.heatmap(c_matrix_rx2, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_rx2 = classification_report(y_test_rx2, pred_rx2, labels=n_labs, target_names=labels)
print(report_rx2)

```

## Cumulative sum RX with all plant species

### Model

```{python}
data_plant = tg[['is_ndgn', 'n_pinus', 'n_salix', 'n_qurcs', 'n_popls',
       'n_thuja', 'n_xrphy', 'n_rubus', 'rx_csum']]

X_train_plant, X_test_plant, y_train_plant, y_test_plant = train_test_split(
    data_plant, target, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_plant = RandomForestClassifier(random_state=42)

rf_plant.fit(X_train_plant, y_train_plant)

pred_plant = rf_plant.predict(X_test_plant)

print(f"Accuracy: {accuracy_score(y_test_plant, pred_plant):.4f}")
```

### Feature Importance

```{python}
explainer_plant = shap.TreeExplainer(rf_plant)
shap_values_plant = explainer_plant.shap_values(data_plant)

# calculate mean absolute SHAP values
shap_summary_plant = np.abs(shap_values_plant).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_plant = [np.mean(shap_summary_plant[i]) for i in range(shap_summary_plant.shape[0])]

# list of feature names
feature_names_plant = ['is_ndgn', 'n_pinus', 'n_salix', 'n_qurcs', 'n_popls',
       'n_thuja', 'n_xrphy', 'n_rubus', 'rx_csum']

# dataframe using 1d list of SHAP values
shap_summary_df_plant = pd.DataFrame({'Feature': feature_names_plant, 'SHAP values': shap_summary_list_plant})

print(shap_summary_df_plant)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_plant = pd.DataFrame({'Feature': feature_names_plant, 'Gini Importance': rf_plant.feature_importances_})

print(feature_imp_df_plant)
```

### Metrics

```{python}
c_matrix_plant = confusion_matrix(y_test_plant, pred_plant, labels=n_labs)
print(c_matrix_plant)
```

```{python}
sns.heatmap(c_matrix_plant, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_plant = classification_report(y_test_plant, pred_plant, labels=n_labs, target_names=labels)
print(report_plant)

```

## Rolling sum RX

Using rolling sum instead of cumulative. 

### Model

```{python}
# trying with rolling sum instead of cumulative
data_r = tg[['is_ndgn', 'plnt_sm', 'rx_rollsum']]

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    data_r, target, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_r = RandomForestClassifier(random_state=42)

rf_r.fit(X_train_r, y_train_r)

pred_r = rf_r.predict(X_test_r)

print(f"Accuracy: {accuracy_score(y_test_r, pred_r):.4f}")
```

It's the same accuracy with a rolling sum instead of a cumulative sum which seems strange but I guess who am I to judge. 

### Feature Importance

Feature importance for rolling sum of rx.

```{python}
feature_names_r = ['is_ndgn', 'plnt_sm', 'rx_rollsum']

# creating dataframe of gini importances
feature_imp_df_r = pd.DataFrame({'Feature': feature_names_r, 'Gini Importance': rf_r.feature_importances_})

print(feature_imp_df_r)
```

It appears that the rolling sum is worse! 

### Metrics

```{python}
c_matrix_r = confusion_matrix(y_test_r, pred_r, labels=n_labs)
print(c_matrix_r)
```

```{python}
sns.heatmap(c_matrix_r, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_r = classification_report(y_test_r, pred_r, labels=n_labs, target_names=labels)
print(report_r)

```

## Modeling without plant sum

Trying without plant sum. 

```{python}
# trying with rolling sum instead of cumulative
data_np = tg[['is_ndgn', 'rx_csum']]

X_train_np, X_test_np, y_train_np, y_test_np = train_test_split(
    data_np, target, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_np = RandomForestClassifier(random_state=42)

rf_np.fit(X_train_np, y_train_np)

pred_np = rf_np.predict(X_test_np)

print(f"Accuracy: {accuracy_score(y_test_np, pred_np):.4f}")
```

### Feature Importance

Feature importance without plant sum. 

```{python}
explainer_np = shap.TreeExplainer(rf_np)
shap_values_np = explainer_np.shap_values(data_np)

# calculate mean absolute SHAP values
shap_summary_np = np.abs(shap_values_np).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_np = [np.mean(shap_summary_np[i]) for i in range(shap_summary_np.shape[0])]

# list of feature names
feature_names_np = ['is_ndgn', 'rx_csum']

# dataframe using 1d list of SHAP values
shap_summary_df_np = pd.DataFrame({'Feature': feature_names_np, 'SHAP values': shap_summary_list_np})

print(shap_summary_df_np)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_np = pd.DataFrame({'Feature': feature_names_np, 'Gini Importance': rf_np.feature_importances_})

print(feature_imp_df_np)
```

In this case, Gini importance and SHAP values do not align! Fascinating. What a world. I need to go to sleep it is now one in the morning. 

### Metrics

```{python}
c_matrix_np = confusion_matrix(y_test_np, pred_np, labels=n_labs)
print(c_matrix_np)
```

```{python}
sns.heatmap(c_matrix_np, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_np = classification_report(y_test_np, pred_np, labels=n_labs, target_names=labels)
print(report_np)

```

## 2020-2025 only

Limiting to 2020 and beyond, as before that there weren't any recorded prescribed burns. 

```{python}
# label encoder for target variable
tg_cur = tg[tg['year']>=2020]
target_cur = label_encoder.fit_transform(tg_cur["size_class"])

data_cur = tg_cur[['is_ndgn', 'plnt_sm', 'rx_csum']]

X_train_cur, X_test_cur, y_train_cur, y_test_cur = train_test_split(
    data_cur, target_cur, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_cur = RandomForestClassifier(random_state=42)

rf_cur.fit(X_train_cur, y_train_cur)

pred_cur = rf_cur.predict(X_test_cur)

print(f"Accuracy: {accuracy_score(y_test_cur, pred_cur):.4f}")
```

### Feature importance

```{python}
explainer_cur = shap.TreeExplainer(rf_cur)
shap_values_cur = explainer_cur.shap_values(data_cur)

# calculate mean absolute SHAP values
shap_summary_cur = np.abs(shap_values_cur).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_cur = [np.mean(shap_summary_cur[i]) for i in range(shap_summary_cur.shape[0])]

# list of feature names
feature_names_cur = ['is_ndgn', 'plnt_sm','rx_csum']

# dataframe using 1d list of SHAP values
shap_summary_df_cur = pd.DataFrame({'Feature': feature_names_cur, 'SHAP values': shap_summary_list_cur})

print(shap_summary_df_cur)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_cur = pd.DataFrame({'Feature': feature_names_cur, 'Gini Importance': rf_cur.feature_importances_})

print(feature_imp_df_cur)
```

### Metrics

```{python}
c_matrix_cur = confusion_matrix(y_test_cur, pred_cur, labels=n_labs)
print(c_matrix_cur)
```

```{python}
sns.heatmap(c_matrix_cur, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_cur = classification_report(y_test_cur, pred_cur, labels=n_labs, target_names=labels)
print(report_cur)

```

## 2020-2025 only without plant sum

Limiting to 2020 and beyond, as before that there weren't any recorded prescribed burns. 

```{python}
data_cur_np = tg_cur[['is_ndgn', 'rx_csum']]

X_train_cur_np, X_test_cur_np, y_train_cur_np, y_test_cur_np = train_test_split(
    data_cur_np, target_cur, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_cur_np = RandomForestClassifier(random_state=42)

rf_cur_np.fit(X_train_cur_np, y_train_cur_np)

pred_cur_np = rf_cur_np.predict(X_test_cur_np)

print(f"Accuracy: {accuracy_score(y_test_cur_np, pred_cur_np):.4f}")
```

Slightly more accurate than with plant information! Fascinating!

### Feature importance

```{python}
explainer_cur_np = shap.TreeExplainer(rf_cur_np)
shap_values_cur_np = explainer_cur_np.shap_values(data_cur_np)

# calculate mean absolute SHAP values
shap_summary_cur_np = np.abs(shap_values_cur_np).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_cur_np = [np.mean(shap_summary_cur_np[i]) for i in range(shap_summary_cur_np.shape[0])]

# list of feature names
feature_names_cur_np = ['is_ndgn', 'rx_csum']

# dataframe using 1d list of SHAP values
shap_summary_df_cur_np = pd.DataFrame({'Feature': feature_names_cur_np, 'SHAP values': shap_summary_list_cur_np})

print(shap_summary_df_cur_np)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_cur_np = pd.DataFrame({'Feature': feature_names_cur_np, 'Gini Importance': rf_cur_np.feature_importances_})

print(feature_imp_df_cur_np)
```

Most of the feature importance is coming from rx cumulative sum, and is somewhat even between SHAP and Gini. 

### Metrics

```{python}
c_matrix_cur_np = confusion_matrix(y_test_cur_np, pred_cur_np, labels=n_labs)
print(c_matrix_cur_np)
```

```{python}
sns.heatmap(c_matrix_cur_np, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_cur_np = classification_report(y_test_cur_np, pred_cur_np, labels=n_labs, target_names=labels)
print(report_cur_np)

```

## 2020-2025, only including cells that have had wildfires/prescribed burns since 2015

Limiting to 2020 and beyond, as before that there weren't any recorded prescribed burns. 

```{python}
tg_fire = tg[(tg['sum_fires'] > 0) | (tg['sum_rx'] > 0)]
tg_fire_cur = tg_fire[tg['year']>=2020]
data_fire_cur = tg_fire_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'n_rx']]

target_fire_cur = label_encoder.fit_transform(tg_fire_cur["size_class"])

X_train_fire_cur, X_test_fire_cur, y_train_fire_cur, y_test_fire_cur = train_test_split(
    data_fire_cur, target_fire_cur, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_fire_cur = RandomForestClassifier(random_state=42)

rf_fire_cur.fit(X_train_fire_cur, y_train_fire_cur)

pred_fire_cur = rf_fire_cur.predict(X_test_fire_cur)

print(f"Accuracy: {accuracy_score(y_test_fire_cur, pred_fire_cur):.4f}")
```

This is worse than previous models (possibly because the data is less skewed? will check other metrics soon). Accuracy is 0.7841 with plant sums, 0.7857 without. 

Using both rx_prev and n_rx instead of rx_csum, the accuracy is 0.7837.

### Feature importance

```{python}
explainer_fire_cur = shap.TreeExplainer(rf_fire_cur)
shap_values_fire_cur = explainer_fire_cur.shap_values(data_fire_cur)

# calculate mean absolute SHAP values
shap_summary_fire_cur = np.abs(shap_values_fire_cur).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_fire_cur = [np.mean(shap_summary_fire_cur[i]) for i in range(shap_summary_fire_cur.shape[0])]

feature_names_fire_cur = ['is_ndgn', 'plnt_sm', 'rx_prev', 'n_rx']

# dataframe using 1d list of SHAP values
shap_summary_df_fire_cur = pd.DataFrame({'Feature': feature_names_fire_cur, 'SHAP values': shap_summary_list_fire_cur})

print(shap_summary_df_fire_cur)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_fire_cur = pd.DataFrame({'Feature': feature_names_fire_cur, 'Gini Importance': rf_fire_cur.feature_importances_})

print(feature_imp_df_fire_cur)
```

When plant sum is included, Gini importance is 0.922344 plnt_sm. 

Without plant sum, SHAP values and Gini importance are again misaligned - for Gini, 0.731176 is rx_csum. 

### Metrics

```{python}
c_matrix_fire_cur = confusion_matrix(y_test_fire_cur, pred_fire_cur, labels=n_labs)
print(c_matrix_fire_cur)
```

```{python}
sns.heatmap(c_matrix_fire_cur, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_fire_cur = classification_report(y_test_fire_cur, pred_fire_cur, labels=n_labs, target_names=labels)
print(report_fire_cur)

```

## All years, only including cells that have had wildfires/prescribed burns

```{python}
data_fire = tg_fire[['is_ndgn', 'plnt_sm', 'rx_csum']]

target_fire = label_encoder.fit_transform(tg_fire["size_class"])

X_train_fire, X_test_fire, y_train_fire, y_test_fire = train_test_split(
    data_fire, target_fire, test_size=0.3, random_state=42
)
```

```{python}
# random forest classifier with defaults
rf_fire = RandomForestClassifier(random_state=42)

rf_fire.fit(X_train_fire, y_train_fire)

pred_fire = rf_fire.predict(X_test_fire)

print(f"Accuracy: {accuracy_score(y_test_fire, pred_fire):.4f}")
```

This is worse than previous models (possibly because the data is less skewed? will check other metrics soon). Accuracy is 0.7841 with plant sums, 0.7857 without. 

### Feature importance

```{python}
explainer_fire = shap.TreeExplainer(rf_fire)
shap_values_fire = explainer_fire.shap_values(data_fire)

# calculate mean absolute SHAP values
shap_summary_fire = np.abs(shap_values_fire).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_fire = [np.mean(shap_summary_fire[i]) for i in range(shap_summary_fire.shape[0])]

# list of feature names
feature_names_fire = ['is_ndgn', 'plnt_sm', 'rx_csum']

# dataframe using 1d list of SHAP values
shap_summary_df_fire = pd.DataFrame({'Feature': feature_names_fire, 'SHAP values': shap_summary_list_fire})

print(shap_summary_df_fire)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_fire = pd.DataFrame({'Feature': feature_names_fire, 'Gini Importance': rf_fire.feature_importances_})

print(feature_imp_df_fire)
```

When plant sum is included, Gini importance is 0.922344 plnt_sm. 

Without plant sum, SHAP values and Gini importance are again misaligned - for Gini, 0.731176 is rx_csum. 

### Metrics

```{python}
c_matrix_fire = confusion_matrix(y_test_fire, pred_fire, labels=n_labs)
print(c_matrix_fire)
```

```{python}
sns.heatmap(c_matrix_fire, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_fire = classification_report(y_test_fire, pred_fire, labels=n_labs, target_names=labels)
print(report_fire)

```

Based on classification report, so far current fire and the first one have been best at classifying classes that are not "No fire". Still quite bad at it, but a bit better. May try an XGBoost shortly.

# Optuna tuning best models

Optimizing for macro average f1 score. 

```{python}
# %pip install optuna
import optuna
optuna.logging.set_verbosity(optuna.logging.INFO)
```

```{python}
def tune_random_forest_optuna(X_train, y_train, X_test, y_test, n_trials=100):
    """
    Random Forest tuning with Optuna (Multi-class support)
    """
    def objective(trial):
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 100, 500),
            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
            'max_depth': trial.suggest_int('max_depth', 5, 100),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 4),

            'random_state': 42
        }

        model = RandomForestClassifier(**params)

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        #accuracy = accuracy_score(y_test, y_pred)
        macro_f1 = f1_score(y_test, y_pred, average='macro')

        return macro_f1

    study = optuna.create_study(
        direction='maximize',
        study_name='random_forest_tuning',
        sampler=optuna.samplers.TPESampler(seed=42)
    )

    study.optimize(
        objective, n_trials=n_trials,
        show_progress_bar=True,
        callbacks=[
            lambda study, trial: print(
                f"  Trial {trial.number}: "
                f"F1={trial.value:.4f}"
                if trial.number % 10 == 0 else None
            )
        ]
    )

    return study

```

## Original (all data, using rx_csum, is_ndgn, plnt_sm)

```{python}
# with optuna tuning
# pulled from prof.cheng's code
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train, y_train, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study = tune_random_forest_optuna(
    X_tr, y_tr, X_val, y_val, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best F1: {rf_study.best_value:.4f}")

```

```{python}
rf_t = RandomForestClassifier(**rf_study.best_params)
rf_t.fit(X_train, y_train)
pred_t = rf_t.predict(X_test)

print(f"Accuracy: {accuracy_score(pred_t, y_test):.4f}")
```

```{python}
c_matrix_t = confusion_matrix(y_test, pred_t, labels=n_labs)
print(c_matrix_t)
```

```{python}
sns.heatmap(c_matrix_t, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_t = classification_report(y_test, pred_t, labels=n_labs, target_names=labels)
print(report_t)

```

## Double RX (using rx_csum and n_rx)

```{python}
# with optuna tuning
# pulled from prof.cheng's code
X_tr_rx2, X_val_rx2, y_tr_rx2, y_val_rx2 = train_test_split(
    X_train_rx2, y_train_rx2, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study_rx2 = tune_random_forest_optuna(
    X_tr_rx2, y_tr_rx2, X_val_rx2, y_val_rx2, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study_rx2.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best F1: {rf_study_rx2.best_value:.4f}")

```

```{python}
rf_t_rx2 = RandomForestClassifier(**rf_study_rx2.best_params)
rf_t_rx2.fit(X_train_rx2, y_train_rx2)
pred_t_rx2 = rf_t_rx2.predict(X_test_rx2)

print(f"Accuracy: {accuracy_score(pred_t_rx2, y_test_rx2):.4f}")
```

```{python}
c_matrix_t_rx2 = confusion_matrix(y_test_rx2, pred_t_rx2, labels=n_labs)
print(c_matrix_t_rx2)
```

```{python}
sns.heatmap(c_matrix_t_rx2, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_t_rx2 = classification_report(y_test_rx2, pred_t_rx2, labels=n_labs, target_names=labels)
print(report_t_rx2)

```

## Fire current (using rx_prev and n_rx)

```{python}
# with optuna tuning
X_tr_fc, X_val_fc, y_tr_fc, y_val_fc = train_test_split(
    X_train_fire_cur, y_train_fire_cur, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_fc_study = tune_random_forest_optuna(
    X_tr_fc, y_tr_fc, X_val_fc, y_val_fc, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best F1: {rf_fc_study.best_value:.4f}")

```

```{python}
rf_fc_t = RandomForestClassifier(**rf_fc_study.best_params)
rf_fc_t.fit(X_train_fire_cur, y_train_fire_cur)
pred_fc_t = rf_fc_t.predict(X_test_fire_cur)

print(f"Accuracy: {accuracy_score(pred_fc_t, y_test_fire_cur):.4f}")
```

```{python}
c_matrix_fc_t = confusion_matrix(y_test_fire_cur, pred_fc_t, labels=n_labs)
print(c_matrix_fc_t)
```

```{python}
sns.heatmap(c_matrix_fc_t, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_fc_t = classification_report(y_test_fire_cur, pred_fc_t, labels=n_labs, target_names=labels)
print(report_fc_t)

```