# Random Forest Classifier pt 2

```{python}
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
```

```{python}
# more libraries
# %pip install scikit-learn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_classification
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold
)
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, precision_score

```

```{python}
# %pip install shap
import shap
```

```{python}
# import data with pandas
tg = pd.read_csv("../data/processed_grid/time_grid.csv")
tg.head()
```

## DF and Size Class Creation

```{python}
tg['rx_prev'] = tg['rx_csum'] - tg['n_rx']
```

```{python}
# filtering to only cells with fire
tg_fire = tg[tg['n_fires']>0]
```

```{python}
# filtering to only cells that have acres over 0
tg_fire = tg[tg['max_acres']>0]
```

```{python}
labels = ['small', 'medium', 'large']
print(pd.qcut(x=tg_fire['max_acres'], q=3, retbins=True))
tg_fire['target'] = pd.qcut(x=tg_fire['max_acres'], q=3, labels=labels)
```

Size classes in target: [(-0.000965, 0.1] < (0.1, 4.583] < (4.583, 413715.0]]

Limited size class based on original classes: [0, 10, 5000, 9000000]
The small class is No fire and A-B, medium class is C-F, and large is class G. Depending on how it goes, it may be reasonable to split up F as well? 

```{python}
bins = [-0.1, 0.25, 1000, 9000000]
class_labs = ['0-A', 'B-E', 'F-G+']
tg_fire['size_2'] = pd.cut(x=tg_fire['max_acres'], bins=bins, labels=class_labs)
```

```{python}
# filtering to only cells with fire
tg_f_cur = tg_fire[tg_fire['year']>=2020]
```

```{python}
print(pd.qcut(x=tg_f_cur['max_acres'], q=3, retbins=True))
tg_f_cur['target'] = pd.qcut(x=tg_f_cur['max_acres'], q=3, labels=labels)
```

Class sizes: [(-0.000965, 0.1] < (0.1, 4.72] < (4.72, 413715.0]]



## rx_prev and max_acres_rx with new size class

### Model

```{python}
# label encoder for target variable
label_encoder = LabelEncoder()
target = label_encoder.fit_transform(tg_fire["target"])

target2 = label_encoder.fit_transform(tg_fire["size_2"])

data = tg_fire[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']]

X_train, X_test, y_train, y_test = train_test_split(
    data, target2, test_size=0.3, random_state=42, stratify=target2
)
```

```{python}
# random forest classifier with defaults
rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, pred):.4f}")
```

Accuracy: 0.4339

Accuracy with size_2 as target: 0.5037
Accuracy with size_2 and not stratified: 0.5004
Accuracy with size_2 and max_acres=0 removed: 0.4898

### Feature Importance

```{python}
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(data)

# calculate mean absolute SHAP values
shap_summary = np.abs(shap_values).mean(axis=0)

# list to store shap values for each feature
shap_summary_list = [np.mean(shap_summary[i]) for i in range(shap_summary.shape[0])]

# list of feature names
feature_names = ['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']

# dataframe using 1d list of SHAP values
shap_summary_df = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list})

print(shap_summary_df)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': rf.feature_importances_})

print(feature_imp_df)
```

### Metrics

```{python}
n_labs2 = np.arange(0,4, 1)
n_labs = np.arange(0,3,1)

c_matrix = confusion_matrix(y_test, pred, labels=n_labs)
print(c_matrix)
```

```{python}
sns.heatmap(c_matrix, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report = classification_report(y_test, pred, labels=n_labs, target_names=class_labs)
print(report)
```

## 2020-2025 rx_prev and max_duration_rx with new size class

### Model

```{python}
data_d = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_duration_rx']]

X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    data_d, target_c, test_size=0.3, random_state=42, stratify=target_c
)
```

```{python}
# random forest classifier with defaults
rf_d = RandomForestClassifier(random_state=42)

rf_d.fit(X_train_d, y_train_d)

pred_d = rf_d.predict(X_test_d)

print(f"Accuracy: {accuracy_score(y_test_d, pred_d):.4f}")
```

Accuracy: 0.4503

### Feature Importance

```{python}
explainer_d = shap.TreeExplainer(rf_d)
shap_values_d = explainer_d.shap_values(data_d)

# calculate mean absolute SHAP values
shap_summary_d = np.abs(shap_values_d).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_d = [np.mean(shap_summary_d[i]) for i in range(shap_summary_d.shape[0])]

# list of feature names
feature_names_d = ['is_ndgn', 'plnt_sm', 'rx_prev', 'max_duration_rx']

# dataframe using 1d list of SHAP values
shap_summary_df_d = pd.DataFrame({'Feature': feature_names_d, 'SHAP values': shap_summary_list_d})

print(shap_summary_df_d)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_d = pd.DataFrame({'Feature': feature_names_d, 'Gini Importance': rf_d.feature_importances_})

print(feature_imp_df_d)
```

### Metrics

```{python}
c_matrix_d = confusion_matrix(y_test_d, pred_d, labels=n_labs)
print(c_matrix_d)
```

```{python}
sns.heatmap(c_matrix_d, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_d = classification_report(y_test_d, pred_d, labels=n_labs, target_names=labels)
print(report_d)
```

## rx_prev and n_rx with new size class

### Model

```{python}
data_nrx = tg_fire[['is_ndgn', 'plnt_sm', 'rx_prev', 'n_rx']]

X_train_nrx, X_test_nrx, y_train_nrx, y_test_nrx = train_test_split(
    data_nrx, target, test_size=0.3, random_state=42, stratify=target
)
```

```{python}
# random forest classifier with defaults
rf_nrx = RandomForestClassifier(random_state=42)

rf_nrx.fit(X_train_nrx, y_train_nrx)

pred_nrx = rf_nrx.predict(X_test_nrx)

print(f"Accuracy: {accuracy_score(y_test_nrx, pred_nrx):.4f}")
```

Accuracy: 0.4339

### Feature Importance

```{python}
explainer_nrx = shap.TreeExplainer(rf_nrx)
shap_values_nrx = explainer_nrx.shap_values(data_nrx)

# calculate mean absolute SHAP values
shap_summary_nrx = np.abs(shap_values_nrx).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_nrx = [np.mean(shap_summary_nrx[i]) for i in range(shap_summary_nrx.shape[0])]

# list of feature names
feature_names_nrx = ['is_ndgn', 'plnt_sm', 'rx_prev', 'n_rx']

# dataframe using 1d list of SHAP values
shap_summary_df_nrx = pd.DataFrame({'Feature': feature_names_nrx, 'SHAP values': shap_summary_list_nrx})

print(shap_summary_df_nrx)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_nrx = pd.DataFrame({'Feature': feature_names_nrx, 'Gini Importance': rf_nrx.feature_importances_})

print(feature_imp_df_nrx)
```

### Metrics

```{python}
c_matrix_nrx = confusion_matrix(y_test_nrx, pred_nrx, labels=n_labs)
print(c_matrix_nrx)
```

```{python}
sns.heatmap(c_matrix_nrx, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_nrx = classification_report(y_test_nrx, pred_nrx, labels=n_labs, target_names=labels)
print(report_nrx)
```

Comparing n_rx to max_acres_rx.

```{python}
print(f"n_rx report:\n{report_nrx}")
print("="*55)
print(f"max_acres_rx report:\n{report}")
```

Almost identical - worth trying limited to 2020-2025. 

## all plants, rx_prev and max_acres_rx with new size class

### Model

```{python}
data_p = tg_fire[['is_ndgn', 'n_pinus', 'n_salix', 'n_qurcs', 'n_popls',
       'n_thuja', 'n_xrphy', 'n_rubus', 'rx_prev', 'max_acres_rx']]

X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    data_p, target, test_size=0.3, random_state=42, stratify=target
)
```

```{python}
# random forest classifier with defaults
rf_p = RandomForestClassifier(random_state=42)

rf_p.fit(X_train_p, y_train_p)

pred_p = rf_p.predict(X_test_p)

print(f"Accuracy: {accuracy_score(y_test_p, pred_p):.4f}")
```

Accuracy: 0.4317

### Feature Importance

```{python}
explainer_p = shap.TreeExplainer(rf_p)
shap_values_p = explainer.shap_values(data_p)

# calculate mean absolute SHAP values
shap_summary_p = np.abs(shap_values_p).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_p = [np.mean(shap_summary_p[i]) for i in range(shap_summary_p.shape[0])]

# list of feature names
feature_names_p = ['is_ndgn', 'n_pinus', 'n_salix', 'n_qurcs', 'n_popls',
       'n_thuja', 'n_xrphy', 'n_rubus', 'rx_prev', 'max_acres_rx']

# dataframe using 1d list of SHAP values
shap_summary_df_p = pd.DataFrame({'Feature': feature_names_p, 'SHAP values': shap_summary_list_p})

print(shap_summary_df_p)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_p = pd.DataFrame({'Feature': feature_names_p, 'Gini Importance': rf_p.feature_importances_})

print(feature_imp_df_p)
```

### Metrics

```{python}
c_matrix_p = confusion_matrix(y_test_p, pred_p, labels=n_labs)
print(c_matrix_p)
```

```{python}
sns.heatmap(c_matrix_p, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report = classification_report(y_test, pred, labels=n_labs, target_names=labels)
print(report)
```

## 2020-2025 rx_prev and max_acres_rx 

### Model

```{python}
# label encoder for target variable
target_c = label_encoder.fit_transform(tg_f_cur["target"])
target_c2 = label_encoder.fit_transform(tg_f_cur["size_2"])

data_c = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']]

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    data_c, target_c2, test_size=0.3, random_state=42, stratify=target_c2
)
```

```{python}
# random forest classifier with defaults
rf_c = RandomForestClassifier(random_state=42)

rf_c.fit(X_train_c, y_train_c)

pred_c = rf_c.predict(X_test_c)

print(f"Accuracy: {accuracy_score(y_test_c, pred_c):.4f}")
```

Accuracy: 0.4490

Accuracy with new size class: 0.5100
Accuracy with max_acres=0 removed: 0.4947

### Feature Importance

```{python}
explainer_c = shap.TreeExplainer(rf_c)
shap_values_c = explainer_c.shap_values(data_c)

# calculate mean absolute SHAP values
shap_summary_c = np.abs(shap_values_c).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_c = [np.mean(shap_summary_c[i]) for i in range(shap_summary_c.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_c = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list_c})

print(shap_summary_df_c)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_c = pd.DataFrame({'Feature': feature_names, 'Gini Importance': rf_c.feature_importances_})

print(feature_imp_df_c)
```

### Metrics

```{python}
c_matrix_c = confusion_matrix(y_test_c, pred_c, labels=n_labs)
print(c_matrix_c)
```

```{python}
sns.heatmap(c_matrix_c, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_c = classification_report(y_test_c, pred_c, labels=n_labs, target_names=class_labs)
print(report_c)
```

## 2020-2025 rx_prev, max_acres_rx, and max_duration_rx

### Model

```{python}
data_cd = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx', 'max_duration_rx']]

X_train_cd, X_test_cd, y_train_cd, y_test_cd = train_test_split(
    data_cd, target_c2, test_size=0.3, random_state=42, stratify=target_c2
)
```

```{python}
# random forest classifier with defaults
rf_cd = RandomForestClassifier(random_state=42)

rf_cd.fit(X_train_cd, y_train_cd)

pred_cd = rf_cd.predict(X_test_cd)

print(f"Accuracy: {accuracy_score(y_test_cd, pred_cd):.4f}")
```

Accuracy: 0.4392
With size_2 as target: 0.5138

### Feature Importance

```{python}
explainer_cd = shap.TreeExplainer(rf_cd)
shap_values_cd = explainer_cd.shap_values(data_cd)

# calculate mean absolute SHAP values
shap_summary_cd = np.abs(shap_values_cd).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_cd = [np.mean(shap_summary_cd[i]) for i in range(shap_summary_cd.shape[0])]

feature_names_ad = ['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx', 'max_duration_rx']

# dataframe using 1d list of SHAP values
shap_summary_df_cd = pd.DataFrame({'Feature': feature_names_ad, 'SHAP values': shap_summary_list_cd})

print(shap_summary_df_cd)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_cd = pd.DataFrame({'Feature': feature_names_ad, 'Gini Importance': rf_cd.feature_importances_})

print(feature_imp_df_cd)
```

### Metrics

```{python}
c_matrix_cd = confusion_matrix(y_test_cd, pred_cd, labels=n_labs)
print(c_matrix_cd)
```

```{python}
sns.heatmap(c_matrix_cd, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_cd = classification_report(y_test_cd, pred_cd, labels=n_labs, target_names=class_labs)
print(report_cd)
```

Confirmed adding duration doesn't help at all.

## 2020-2025 rx_prev and n_rx with new size class

### Model

```{python}
data_cnrx = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'n_rx']]

X_train_cnrx, X_test_cnrx, y_train_cnrx, y_test_cnrx = train_test_split(
    data_cnrx, target_c, test_size=0.3, random_state=42, stratify=target_c
)
```

```{python}
# random forest classifier with defaults
rf_cnrx = RandomForestClassifier(random_state=42)

rf_cnrx.fit(X_train_cnrx, y_train_cnrx)

pred_cnrx = rf_cnrx.predict(X_test_cnrx)

print(f"Accuracy: {accuracy_score(y_test_cnrx, pred_cnrx):.4f}")
```

Accuracy: 0.4490

### Feature Importance

```{python}
explainer_cnrx = shap.TreeExplainer(rf_cnrx)
shap_values_cnrx = explainer_cnrx.shap_values(data_cnrx)

# calculate mean absolute SHAP values
shap_summary_cnrx = np.abs(shap_values_cnrx).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_cnrx = [np.mean(shap_summary_cnrx[i]) for i in range(shap_summary_cnrx.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_cnrx = pd.DataFrame({'Feature': feature_names_nrx, 'SHAP values': shap_summary_list_cnrx})

print(shap_summary_df_cnrx)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_cnrx = pd.DataFrame({'Feature': feature_names_nrx, 'Gini Importance': rf_cnrx.feature_importances_})

print(feature_imp_df_cnrx)
```

Comparing featuring importance using n_rx vs max_acres_rx.

```{python}
print(f"n_rx feature importance:\n{feature_imp_df_cnrx}")
print("="*35)
print(f"max_acres_rx feature importance:\n{feature_imp_df_c}")
```

Interesting - max_acres_rx has higher importance than n_rx, and with acres, is_ndgn has higher importance as well. Neat!

### Metrics

```{python}
c_matrix_cnrx = confusion_matrix(y_test_cnrx, pred_cnrx, labels=n_labs)
print(c_matrix_cnrx)
```

```{python}
sns.heatmap(c_matrix_cnrx, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_cnrx = classification_report(y_test_cnrx, pred_cnrx, labels=n_labs, target_names=labels)
print(report_cnrx)
```

Comparing n_rx to max_acres_rx.

```{python}
print(f"n_rx report:\n{report_cnrx}")
print("="*55)
print(f"max_acres_rx report:\n{report_c}")
```

Pretty much identical. max_acres_rx has slightly, slightly higher macro avg precision.

# Tuning

```{python}
# %pip install optuna
import optuna
optuna.logging.set_verbosity(optuna.logging.INFO)
```

```{python}
def tune_random_forest_optuna(X_train, y_train, X_test, y_test, labels=labels, n_trials=100):
    """
    Random Forest tuning with Optuna (Multi-class support)
    """
    def objective(trial):
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 100, 500),
            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
            'max_depth': trial.suggest_int('max_depth', 5, 100),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 4),

            'random_state': 42
        }

        model = RandomForestClassifier(**params)

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        #accuracy = accuracy_score(y_test, y_pred)
        macro_f1 = f1_score(y_test, y_pred, average='macro')
        #precision = precision_score(y_test, y_pred, average='weighted', zero_division=0.0)

        return macro_f1

    study = optuna.create_study(
        direction='maximize',
        study_name='random_forest_tuning',
        sampler=optuna.samplers.TPESampler(seed=42)
    )

    study.optimize(
        objective, n_trials=n_trials,
        show_progress_bar=True,
        callbacks=[
            lambda study, trial: print(
                f"  Trial {trial.number}: "
                f"Score={trial.value:.4f}"
                if trial.number % 10 == 0 else None
            )
        ]
    )

    return study
```

## rx_prev and max_acres_rx with new size class

```{python}
# with optuna tuning
# pulled from prof.cheng's code
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train, y_train, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study = tune_random_forest_optuna(
    X_tr, y_tr, X_val, y_val, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best Accuracy: {rf_study.best_value:.4f}")

```

```{python}
rf_t = RandomForestClassifier(**rf_study.best_params)
rf_t.fit(X_train, y_train)
pred_t = rf_t.predict(X_test)

print(f"Accuracy: {accuracy_score(pred_t, y_test):.4f}")
print(f"Old accuracy: {accuracy_score(pred, y_test):.4f}")
print(f"Precision: {precision_score(y_test, pred_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test, pred, average='weighted', zero_division=0.0):.4f}")
```

with size 0 fires removed: 
Accuracy: 0.4898
Old accuracy: 0.4898
Precision: 0.3968
Old precision: 0.3936

```{python}
c_matrix_t = confusion_matrix(y_test, pred_t, labels=n_labs)
print(f"Confusion matrix:\n{c_matrix_t}")
print("="*35)
print(f"Old confusion matrix:\n{c_matrix}")
```

```{python}
sns.heatmap(c_matrix_t, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_t = classification_report(y_test, pred_t, labels=n_labs, target_names=labels)
print(report_t)
```

```{python}
# creating dataframe of gini importances
feature_imp_df_t = pd.DataFrame({'Feature': feature_names, 'Gini Importance': rf_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_t}")
```

## 2020-2025 rx_prev and max_acres_rx with new size class

### Tuning

```{python}
# with optuna tuning
# pulled from prof.cheng's code
X_tr_c, X_val_c, y_tr_c, y_val_c = train_test_split(
    X_train_c, y_train_c, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study_c = tune_random_forest_optuna(
    X_tr_c, y_tr_c, X_val_c, y_val_c, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study_c.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best Accuracy: {rf_study_c.best_value:.4f}")

```

```{python}
rf_c_t = RandomForestClassifier(**rf_study_c.best_params)
rf_c_t.fit(X_train_c, y_train_c)
pred_c_t = rf_c_t.predict(X_test_c)

print(f"Accuracy: {accuracy_score(pred_c_t, y_test_c):.4f}")
print(f"Old accuracy: {accuracy_score(pred_c, y_test_c):.4f}")
print(f"Precision: {precision_score(y_test_c, pred_c_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test_c, pred_c, average='weighted', zero_division=0.0):.4f}")
```

Accuracy: 0.4527
Old accuracy: 0.4490
Precision: 0.4741
Old precision: 0.4086

When stratified for y, got worse precision at 0.4017. 

With size 0 fires removed:
Accuracy: 0.4971
Old accuracy: 0.4947
Precision: 0.3517
Old precision: 0.4021

### Metrics

```{python}
c_matrix_c_t = confusion_matrix(y_test_c, pred_c_t, labels=n_labs)
print(f"Confusion matrix:\n{c_matrix_c_t}")
print("="*35)
print(f"Old confusion matrix:\n{c_matrix_c}")

```

```{python}
sns.heatmap(c_matrix_c_t, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_c_t = classification_report(y_test_c, pred_c_t, labels=n_labs, target_names=class_labs)
print(f"Report:\n{report_c_t}")
print("="*55)
print(f"Old report:\n{report_c}")
```

### Feature Importance

```{python}
# creating dataframe of gini importances
feature_imp_df_c_t = pd.DataFrame({'Feature': feature_names, 'Gini Importance': rf_c_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df_c}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_c_t}")
```

## 2020-2025 rx_prev and max_duration_rx with new size class

### Tuning

```{python}
# with optuna tuning
# pulled from prof.cheng's code
X_tr_d, X_val_d, y_tr_d, y_val_d = train_test_split(
    X_train_d, y_train_d, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study_d = tune_random_forest_optuna(
    X_tr_d, y_tr_d, X_val_d, y_val_d, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study_d.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best Accuracy: {rf_study_d.best_value:.4f}")

```

```{python}
rf_d_t = RandomForestClassifier(**rf_study_d.best_params)
rf_d_t.fit(X_train_d, y_train_d)
pred_d_t = rf_d_t.predict(X_test_d)

print(f"Accuracy: {accuracy_score(pred_d_t, y_test_d):.4f}")
print(f"Old accuracy: {accuracy_score(pred_d, y_test_d):.4f}")
print(f"Precision: {precision_score(y_test_d, pred_d_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test_d, pred_d, average='weighted', zero_division=0.0):.4f}")
```

Accuracy: 0.4527
Old accuracy: 0.4503
Precision: 0.4830
Old precision: 0.4178

Trained rx acres vs rx duration comparison

```{python}
print(f"Accuracy: {accuracy_score(pred_d_t, y_test_d):.4f}")
print(f"Acre Accuracy: {accuracy_score(pred_c_t, y_test_c):.4f}")
print(f"Precision: {precision_score(y_test_d, pred_d_t, average='weighted', zero_division=0.0):.4f}")
print(f"Acre Precision: {precision_score(y_test_c, pred_c_t, average='weighted', zero_division=0.0):.4f}")

```

### Metrics

```{python}
c_matrix_d_t = confusion_matrix(y_test_d, pred_d_t, labels=n_labs)
print(c_matrix_d_t)
```

```{python}
sns.heatmap(c_matrix_d_t, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_d_t = classification_report(y_test_d, pred_d_t, labels=n_labs, target_names=labels)

print(f"Old report:\n{report_d}")
print("="*55)
print(f"New Report:\n{report_d_t}")
print("="*55)
print(f"Acre report:\n{report_c_t}")
```

### Feature Importance

```{python}
# creating dataframe of gini importances
feature_imp_df_d_t = pd.DataFrame({'Feature': feature_names_d, 'Gini Importance': rf_d_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df_d}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_d_t}")
print("="*35)
print(f"Trained acre feature importance:\n{feature_imp_df_c_t}")
```

Okay yeah. Explains it! RX max acres is useless. Good to know!