# Random Forest Classifier CLEAN FINAL

```{python}
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
```

```{python}
# more libraries
# %pip install scikit-learn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_classification
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold
)
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, precision_score, roc_auc_score

```

```{python}
# %pip install shap
import shap
```

```{python}
# import data with pandas
tg = pd.read_csv("../data/processed_grid/time_grid.csv")
tg.head()
```

## DF and Size Class Creation

```{python}
tg['rx_prev'] = tg['rx_csum'] - tg['n_rx']
```

```{python}
tg['wf_prev'] = tg['fire_csum'] - tg['n_fires']
tg['wf_prev_r'] = tg['fire_rollsum'] - tg['n_fires']
tg['wf_prev_r5'] = tg['fire_rollsum_5'] - tg['n_fires']

```

```{python}
tg['max_acres_lim'] = tg['max_acres'].clip(upper=6178)
tg['wf_acres5_lim'] = tg.groupby('index')['max_acres_lim'].transform(lambda s: s.rolling(5, min_periods=1, center=False).sum())
tg['wf_prev_acres5_lim'] = tg['wf_acres5_lim'] - tg['max_acres_lim']

```

```{python}
# filtering to only cells that have fires of at least 0.25 acre
tg_fire = tg[tg['max_acres']>0]
```

```{python}
# filtering to only cells with fire
tg_f_cur = tg_fire[tg_fire['year']>=2020]
```

```{python}
labels = ['small', 'medium', 'large']
print(pd.qcut(x=tg_f_cur['max_acres'], q=3, retbins=True))
tg_f_cur['target'] = pd.qcut(x=tg_f_cur['max_acres'], q=3, labels=labels)
```

Class sizes: [(-0.000965, 0.1] < (0.1, 4.72] < (4.72, 413715.0]]

## 2020-2025 is_ndgn, plnt_sm, rx_prev

### Model

```{python}
# label encoder for target variable
label_encoder = LabelEncoder()
target_c = label_encoder.fit_transform(tg_f_cur["target"])
#target_c2 = label_encoder.fit_transform(tg_f_cur["size_2"])

data_c = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev']]

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    data_c, target_c, test_size=0.3, random_state=42, stratify=target_c
)
```

```{python}
# random forest classifier with defaults
rf_c = RandomForestClassifier(random_state=42)

rf_c.fit(X_train_c, y_train_c)

pred_c = rf_c.predict(X_test_c)

print(f"Accuracy: {accuracy_score(y_test_c, pred_c):.4f}")
```

Accuracy: 0.4321

### Feature Importance

```{python}
explainer_c = shap.TreeExplainer(rf_c)
shap_values_c = explainer_c.shap_values(data_c)

# calculate mean absolute SHAP values
shap_summary_c = np.abs(shap_values_c).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_c = [np.mean(shap_summary_c[i]) for i in range(shap_summary_c.shape[0])]

# dataframe using 1d list of SHAP values
feature_names = ['is_ndgn', 'plnt_sm', 'rx_prev']
shap_summary_df_c = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list_c})

print(shap_summary_df_c)
```

Feature  SHAP values
0  is_ndgn     0.006121
1  plnt_sm     0.057718
2  rx_prev     0.003374

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_c = pd.DataFrame({'Feature': feature_names, 'Gini Importance': rf_c.feature_importances_})

print(feature_imp_df_c)
```

Feature  Gini Importance
0  is_ndgn         0.030743
1  plnt_sm         0.916694
2  rx_prev         0.052564

### Metrics

```{python}
n_labs = np.unique(target_c)
class_labs = ["large", "medium", "small"]
```

```{python}
c_matrix_c = confusion_matrix(y_test_c, pred_c, labels=n_labs)
print(c_matrix_c)
```

[[320   7 370]
 [166   8 388]
 [242  15 576]]

```{python}
sns.heatmap(c_matrix_c, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_c = classification_report(y_test_c, pred_c, labels=n_labs, target_names=class_labs)
print(report_c)
```

precision    recall  f1-score   support

       large       0.44      0.46      0.45       697
      medium       0.27      0.01      0.03       562
       small       0.43      0.69      0.53       833

    accuracy                           0.43      2092
   macro avg       0.38      0.39      0.34      2092
weighted avg       0.39      0.43      0.37      2092

## 2020-2025 rx_prev and max_acres_rx without plant

### Model

```{python}
data_cnp = tg_f_cur[['is_ndgn', 'rx_prev', 'max_acres_rx']]

X_train_cnp, X_test_cnp, y_train_cnp, y_test_cnp = train_test_split(
    data_cnp, target_c2, test_size=0.3, random_state=42, stratify=target_c2
)
```

```{python}
# random forest classifier with defaults
rf_cnp = RandomForestClassifier(random_state=42)

rf_cnp.fit(X_train_cnp, y_train_cnp)

pred_cnp = rf_cnp.predict(X_test_cnp)

print(f"Accuracy: {accuracy_score(y_test_cnp, pred_cnp):.4f}")
```

Accuracy: 0.4357
Accuracy with smallest bin <=1: 0.3981

### Feature Importance

```{python}
explainer_cnp = shap.TreeExplainer(rf_cnp)
shap_values_cnp = explainer_cnp.shap_values(data_cnp)

# calculate mean absolute SHAP values
shap_summary_cnp = np.abs(shap_values_cnp).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_cnp = [np.mean(shap_summary_cnp[i]) for i in range(shap_summary_cnp.shape[0])]

feature_names_np = ['is_ndgn', 'rx_prev', 'max_acres_rx']

# dataframe using 1d list of SHAP values
shap_summary_df_cnp = pd.DataFrame({'Feature': feature_names_np, 'SHAP values': shap_summary_list_cnp})

print(shap_summary_df_cnp)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_cnp = pd.DataFrame({'Feature': feature_names_np, 'Gini Importance': rf_cnp.feature_importances_})

print(feature_imp_df_cnp)
```

### Metrics

```{python}
c_matrix_cnp = confusion_matrix(y_test_cnp, pred_cnp, labels=n_labs)
print(c_matrix_cnp)
```

```{python}
sns.heatmap(c_matrix_cnp, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_cnp = classification_report(y_test_cnp, pred_cnp, labels=n_labs, target_names=class_labs)
print(report_cnp)
```

## 2020-2025 adding previous wildfires

### Model

```{python}
# data with previous wildfires
data_wf = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'wf_prev_r5', 'wf_prev_acres5_lim']]

X_train_wf, X_test_wf, y_train_wf, y_test_wf = train_test_split(
    data_wf, target_c, test_size=0.3, random_state=42, stratify=target_c
)
```

```{python}
# random forest classifier with defaults
rf_wf = RandomForestClassifier(random_state=42)

rf_wf.fit(X_train_wf, y_train_wf)

pred_wf = rf_wf.predict(X_test_wf)

print(f"Accuracy: {accuracy_score(y_test_wf, pred_wf):.4f}")
```

Accuracy with wf_prev_r5 and wf_prev_acres5_lim: 0.4402

### Feature Importance

```{python}
explainer_wf = shap.TreeExplainer(rf_wf)
shap_values_wf = explainer_wf.shap_values(data_wf)

# calculate mean absolute SHAP values
shap_summary_wf = np.abs(shap_values_wf).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_wf = [np.mean(shap_summary_wf[i]) for i in range(shap_summary_wf.shape[0])]

feature_names_wf = ['is_ndgn', 'plnt_sm', 'rx_prev', 'wf_prev_r5', 'wf_prev_acres5_lim']

# dataframe using 1d list of SHAP values
shap_summary_df_wf = pd.DataFrame({'Feature': feature_names_wf, 'SHAP values': shap_summary_list_wf})

print(shap_summary_df_wf)
```

Feature  SHAP values
0             is_ndgn     0.007066
1             plnt_sm     0.064564
2             rx_prev     0.002331
3          wf_prev_r5     0.052754
4  wf_prev_acres5_lim     0.039358

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_wf = pd.DataFrame({'Feature': feature_names_wf, 'Gini Importance': rf_wf.feature_importances_})

print(feature_imp_df_wf)
```

Feature  Gini Importance
0             is_ndgn         0.023365
1             plnt_sm         0.281619
2             rx_prev         0.015803
3          wf_prev_r5         0.142505
4  wf_prev_acres5_lim         0.536709

### Metrics

```{python}
c_matrix_wf = confusion_matrix(y_test_wf, pred_wf, labels=n_labs)
print(c_matrix_wf)
```

[[291  43 363]
 [131  74 357]
 [180  97 556]]

```{python}
sns.heatmap(c_matrix_wf, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_wf = classification_report(y_test_wf, pred_wf, labels=n_labs, target_names=labels)
print(report_wf)
```

precision    recall  f1-score   support

       small       0.44      0.46      0.45       697
      medium       0.27      0.01      0.03       562
       large       0.43      0.69      0.53       833

    accuracy                           0.43      2092
   macro avg       0.38      0.39      0.34      2092
weighted avg       0.39      0.43      0.37      2092

## 2020-2025 adding previous wildfires and all plants

### Model

```{python}
# data with previous wildfires
data_p = tg_f_cur[['is_ndgn', 'rx_prev', 'wf_prev_r5', 'wf_prev_acres5_lim', 'n_pinus', 'n_salix', 'n_qurcs', 'n_popls', 'n_thuja', 'n_xrphy', 'n_rubus']]

X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    data_p, target_c, test_size=0.3, random_state=42, stratify=target_c
)
```

```{python}
# random forest classifier with defaults
rf_p = RandomForestClassifier(random_state=42)

rf_p.fit(X_train_p, y_train_p)

pred_p = rf_p.predict(X_test_p)

print(f"Accuracy: {accuracy_score(y_test_p, pred_p):.4f}")
```

Accuracy: 0.4546

### Feature Importance

```{python}
explainer_p = shap.TreeExplainer(rf_p)
shap_values_p = explainer_p.shap_values(data_p)

# calculate mean absolute SHAP values
shap_summary_p = np.abs(shap_values_p).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_p = [np.mean(shap_summary_p[i]) for i in range(shap_summary_p.shape[0])]

feature_names_p = ['is_ndgn', 'rx_prev', 'wf_prev_r5', 'wf_prev_acres5_lim', 'n_pinus', 'n_salix', 'n_qurcs', 'n_popls', 'n_thuja', 'n_xrphy', 'n_rubus']

# dataframe using 1d list of SHAP values
shap_summary_df_p = pd.DataFrame({'Feature': feature_names_p, 'SHAP values': shap_summary_list_p})

print(shap_summary_df_p)
```

Feature  SHAP values
0              is_ndgn     0.006585
1              rx_prev     0.001904
2           wf_prev_r5     0.047854
3   wf_prev_acres5_lim     0.039049
4              n_pinus     0.058195
5              n_salix     0.006272
6              n_qurcs     0.013686
7              n_popls     0.008190
8              n_thuja     0.009032
9              n_xrphy     0.008879
10             n_rubus     0.016421

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_p = pd.DataFrame({'Feature': feature_names_p, 'Gini Importance': rf_p.feature_importances_})

print(feature_imp_df_p)
```

Feature  Gini Importance
0              is_ndgn         0.023708
1              rx_prev         0.012722
2           wf_prev_r5         0.113431
3   wf_prev_acres5_lim         0.367580
4              n_pinus         0.149856
5              n_salix         0.022112
6              n_qurcs         0.076670
7              n_popls         0.051814
8              n_thuja         0.050681
9              n_xrphy         0.064442
10             n_rubus         0.066984

### Metrics

```{python}
c_matrix_p = confusion_matrix(y_test_p, pred_p, labels=n_labs)
print(c_matrix_p)
```

[[341  66 290]
 [141  96 325]
 [195 124 514]]

```{python}
sns.heatmap(c_matrix_p, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_p = classification_report(y_test_p, pred_p, labels=n_labs, target_names=class_labs)
print(report_p)
```

precision    recall  f1-score   support

       small       0.50      0.49      0.50       697
      medium       0.34      0.17      0.23       562
       large       0.46      0.62      0.52       833

    accuracy                           0.45      2092
   macro avg       0.43      0.43      0.42      2092
weighted avg       0.44      0.45      0.43      2092

# Tuning

```{python}
# %pip install optuna
import optuna
optuna.logging.set_verbosity(optuna.logging.INFO)
```

```{python}
# optuna tuning function
def tune_random_forest_optuna(X_train, y_train, X_val, y_val, labels=labels, n_trials=100):
    """
    Random Forest tuning with Optuna (Multi-class support)
    """
    def objective(trial):
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 100, 500),
            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
            'max_depth': trial.suggest_int('max_depth', 5, 100),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 4),

            'random_state': 42
        }

        model = RandomForestClassifier(**params)

        model.fit(X_train, y_train)

        y_proba = model.predict_proba(X_val)

        auc = roc_auc_score(y_val, y_proba, multi_class='ovr')

        return auc

    study = optuna.create_study(
        direction='maximize',
        study_name='random_forest_tuning',
        sampler=optuna.samplers.TPESampler(seed=42)
    )

    study.optimize(
        objective, n_trials=n_trials,
        show_progress_bar=True,
        callbacks=[
            lambda study, trial: print(
                f"  Trial {trial.number}: "
                f"Score={trial.value:.4f}"
                if trial.number % 10 == 0 else None
            )
        ]
    )

    return study
```

## 2020-2025 is_ndgn, plnt_sm, rx_prev

### Tuning

```{python}
# with optuna tuning
# pulled from prof.cheng's code
X_tr_c, X_val_c, y_tr_c, y_val_c = train_test_split(
    X_train_c, y_train_c, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study_c = tune_random_forest_optuna(
    X_tr_c, y_tr_c, X_val_c, y_val_c, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study_c.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best Accuracy: {rf_study_c.best_value:.4f}")

```

```{python}
rf_c_t = RandomForestClassifier(**rf_study_c.best_params)
rf_c_t.fit(X_train_c, y_train_c)
pred_c_t = rf_c_t.predict(X_test_c)

print(f"Accuracy: {accuracy_score(pred_c_t, y_test_c):.4f}")
print(f"Old accuracy: {accuracy_score(pred_c, y_test_c):.4f}")
print(f"Precision: {precision_score(y_test_c, pred_c_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test_c, pred_c, average='weighted', zero_division=0.0):.4f}")
```

Accuracy: 0.4374
Old accuracy: 0.4321
Precision: 0.4551
Old precision: 0.3900

### Metrics

```{python}
c_matrix_c_t = confusion_matrix(y_test_c, pred_c_t, labels=n_labs)
print(f"Confusion matrix:\n{c_matrix_c_t}")
print("="*35)
print(f"Old confusion matrix:\n{c_matrix_c}")

```

```{python}
sns.heatmap(c_matrix_c_t, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.savefig("../images/conf_matrix_ndgn_plnt_rx.png")
plt.show()

```

```{python}
report_c_t = classification_report(y_test_c, pred_c_t, labels=n_labs, target_names=class_labs)
print(f"Report:\n{report_c_t}")
print("="*55)
print(f"Old report:\n{report_c}")
```

Report:
              precision    recall  f1-score   support

       large       0.45      0.46      0.45       697
      medium       0.50      0.00      0.01       562
       small       0.43      0.71      0.54       833

    accuracy                           0.44      2092
   macro avg       0.46      0.39      0.33      2092
weighted avg       0.46      0.44      0.37      2092

=======================================================
Old report:
              precision    recall  f1-score   support

       large       0.44      0.46      0.45       697
      medium       0.27      0.01      0.03       562
       small       0.43      0.69      0.53       833

    accuracy                           0.43      2092
   macro avg       0.38      0.39      0.34      2092
weighted avg       0.39      0.43      0.37      2092

### Feature Importance

```{python}
# creating dataframe of gini importances
feature_imp_df_c_t = pd.DataFrame({'Feature': feature_names, 'Gini Importance': rf_c_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df_c}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_c_t}")
```

Trained feature importance:
   Feature  Gini Importance
0  is_ndgn         0.037574
1  plnt_sm         0.901449
2  rx_prev         0.060977

```{python}
explainer_c_t = shap.TreeExplainer(rf_c_t)
shap_values_c_t = explainer_c_t.shap_values(data_c)

# calculate mean absolute SHAP values
shap_summary_c_t = np.abs(shap_values_c_t).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_c_t = [np.mean(shap_summary_c_t[i]) for i in range(shap_summary_c_t.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_c_t = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list_c_t})

print(shap_summary_df_c_t)
```

Feature  SHAP values
0  is_ndgn     0.004786
1  plnt_sm     0.052765
2  rx_prev     0.002765

```{python}
fig = plt.figure(figsize=(6,6))

feature_names = ["Is Indigenous", "Plant sum", "Previous prescribed burn"]

shap.summary_plot(shap_values = shap_values_c_t, 
                  features = X_test_c.values,
                  feature_names = feature_names,
                  class_names = class_labs,
                  plot_type='bar',
                  max_display=15,
                  show=False)
plt.tight_layout()
plt.xlabel("Mean absolute SHAP value")
plt.savefig("../images/shap_summary_ndgn_plnt_rx.png")
plt.show()

# average impact on model output magnitude
```

## 2020-2025 with past wf

### Tuning

```{python}
# with optuna tuning
X_tr_wf, X_val_wf, y_tr_wf, y_val_wf = train_test_split(
    X_train_wf, y_train_wf, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study_wf = tune_random_forest_optuna(
    X_tr_wf, y_tr_wf, X_val_wf, y_val_wf, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study_wf.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best Score: {rf_study_wf.best_value:.4f}")

```

```{python}
rf_wf_t = RandomForestClassifier(**rf_study_wf.best_params)
rf_wf_t.fit(X_train_wf, y_train_wf)
pred_wf_t = rf_wf_t.predict(X_test_wf)

print(f"Accuracy: {accuracy_score(pred_wf_t, y_test_wf):.4f}")
print(f"Old accuracy: {accuracy_score(pred_wf, y_test_wf):.4f}")
print(f"Precision: {precision_score(y_test_wf, pred_wf_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test_wf, pred_wf, average='weighted', zero_division=0.0):.4f}")
```

Accuracy: 0.4594
Old accuracy: 0.4402
Precision: 0.4479
Old precision: 0.4275

### Metrics

```{python}
c_matrix_wf_t = confusion_matrix(y_test_wf, pred_wf_t, labels=n_labs)
print(f"Confusion matrix:\n{c_matrix_wf_t}")
print("="*35)
print(f"Old confusion matrix:\n{c_matrix_wf}")

```

```{python}
sns.heatmap(c_matrix_wf_t, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.savefig("../images/conf_matrix_ndgn_plnt_rx_wf.png")
plt.show()

```

```{python}
report_wf_t = classification_report(y_test_wf, pred_wf_t, labels=n_labs, target_names=class_labs)
print(f"Report:\n{report_wf_t}")
print("="*55)
print(f"Old report:\n{report_wf}")
```

Report:
              precision    recall  f1-score   support

       large       0.52      0.42      0.46       697
      medium       0.38      0.01      0.01       562
       small       0.44      0.80      0.57       833

    accuracy                           0.46      2092
   macro avg       0.44      0.41      0.35      2092
weighted avg       0.45      0.46      0.38      2092

=======================================================
Old report:
              precision    recall  f1-score   support

       small       0.48      0.42      0.45       697
      medium       0.35      0.13      0.19       562
       large       0.44      0.67      0.53       833

    accuracy                           0.44      2092
   macro avg       0.42      0.41      0.39      2092
weighted avg       0.43      0.44      0.41      2092

### Feature Importance

```{python}
# creating dataframe of gini importances
feature_imp_df_wf_t = pd.DataFrame({'Feature': feature_names_wf, 'Gini Importance': rf_wf_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df_wf}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_wf_t}")
```

Old feature importance:
              Feature  Gini Importance
0             is_ndgn         0.023365
1             plnt_sm         0.281619
2             rx_prev         0.015803
3          wf_prev_r5         0.142505
4  wf_prev_acres5_lim         0.536709
===================================
Trained feature importance:
              Feature  Gini Importance
0             is_ndgn         0.031678
1             plnt_sm         0.445384
2             rx_prev         0.019078
3          wf_prev_r5         0.217446
4  wf_prev_acres5_lim         0.286414

```{python}
explainer_wf_t = shap.TreeExplainer(rf_wf_t)
shap_values_wf_t = explainer_wf_t.shap_values(data_wf)

# calculate mean absolute SHAP values
shap_summary_wf_t = np.abs(shap_values_wf_t).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_wf_t = [np.mean(shap_summary_wf_t[i]) for i in range(shap_summary_wf_t.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_wf_t = pd.DataFrame({'Feature': feature_names_wf, 'SHAP values': shap_summary_list_wf_t})

print(shap_summary_df_wf_t)
```

Feature  SHAP values
0             is_ndgn     0.002928
1             plnt_sm     0.047727
2             rx_prev     0.001092
3          wf_prev_r5     0.031744
4  wf_prev_acres5_lim     0.022332

```{python}
fig = plt.figure(figsize=(6,6))

feature_names_wf = ["Is Indigenous", "Plant sum", "Previous prescribed burn", "Previous wildfire rolling sum", "Previous wildfire acreage rolling sum"]

shap.summary_plot(shap_values = shap_values_wf_t, 
                  features = X_test_wf.values,
                  feature_names = feature_names_wf,
                  class_names = class_labs,
                  plot_type='bar',
                  max_display=15,
                  show=False)
plt.tight_layout()
plt.xlabel("Mean absolute SHAP value")
plt.savefig("../images/shap_summary_ndgn_plnt_rx_wf.png")
plt.show()

# average impact on model output magnitude
```

## 2020-2025 with past wf, all plants

### Tuning

```{python}
# with optuna tuning
X_tr_p, X_val_p, y_tr_p, y_val_p = train_test_split(
    X_train_p, y_train_p, test_size=0.3, random_state=42
)

print("Tuning Random Forest with Optuna...")
print("-" * 55)
rf_study_p = tune_random_forest_optuna(
    X_tr_p, y_tr_p, X_val_p, y_val_p, n_trials=100
)
print(f"\n Best Random Forest Parameters:")
print("=" * 100)
for key, value in rf_study_p.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best Score: {rf_study_p.best_value:.4f}")

```

```{python}
rf_p_t = RandomForestClassifier(**rf_study_p.best_params)
rf_p_t.fit(X_train_p, y_train_p)
pred_p_t = rf_p_t.predict(X_test_p)

print(f"Accuracy: {accuracy_score(pred_p_t, y_test_p):.4f}")
print(f"Old accuracy: {accuracy_score(pred_p, y_test_p):.4f}")
print(f"Precision: {precision_score(y_test_p, pred_p_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test_p, pred_p, average='weighted', zero_division=0.0):.4f}")
```

Accuracy: 0.4728
Old accuracy: 0.4546
Precision: 0.4554
Old precision: 0.4393

### Metrics

```{python}
c_matrix_p_t = confusion_matrix(y_test_p, pred_p_t, labels=n_labs)
print(f"Confusion matrix:\n{c_matrix_p_t}")
print("="*35)
print(f"Old confusion matrix:\n{c_matrix_p}")

```

Confusion matrix:
[[357  35 305]
 [127  59 376]
 [191  69 573]]
===================================
Old confusion matrix:
[[341  66 290]
 [141  96 325]
 [195 124 514]]

```{python}
sns.heatmap(c_matrix_p_t, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.savefig("../images/conf_matrix_ndgn_plnt_rx_p.png")
plt.show()

```

```{python}
report_p_t = classification_report(y_test_p, pred_p_t, labels=n_labs, target_names=class_labs)
print(f"Report:\n{report_p_t}")
print("="*55)
print(f"Old report:\n{report_p}")
```

Report:
              precision    recall  f1-score   support

       large       0.53      0.51      0.52       697
      medium       0.36      0.10      0.16       562
       small       0.46      0.69      0.55       833

    accuracy                           0.47      2092
   macro avg       0.45      0.44      0.41      2092
weighted avg       0.46      0.47      0.44      2092

=======================================================
Old report:
              precision    recall  f1-score   support

       small       0.50      0.49      0.50       697
      medium       0.34      0.17      0.23       562
       large       0.46      0.62      0.52       833

    accuracy                           0.45      2092
   macro avg       0.43      0.43      0.42      2092
weighted avg       0.44      0.45      0.43      2092

### Feature Importance

```{python}
# creating dataframe of gini importances
feature_imp_df_p_t = pd.DataFrame({'Feature': feature_names_p, 'Gini Importance': rf_p_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df_p}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_p_t}")
```

Old feature importance:
              Feature  Gini Importance
0             is_ndgn         0.023365
1             plnt_sm         0.281619
2             rx_prev         0.015803
3          wf_prev_r5         0.142505
4  wf_prev_acres5_lim         0.536709
===================================
Trained feature importance:
              Feature  Gini Importance
0             is_ndgn         0.031678
1             plnt_sm         0.445384
2             rx_prev         0.019078
3          wf_prev_r5         0.217446
4  wf_prev_acres5_lim         0.286414

```{python}
explainer_p_t = shap.TreeExplainer(rf_p_t)
shap_values_p_t = explainer_p_t.shap_values(data_p)

# calculate mean absolute SHAP values
shap_summary_p_t = np.abs(shap_values_p_t).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_p_t = [np.mean(shap_summary_p_t[i]) for i in range(shap_summary_p_t.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_p_t = pd.DataFrame({'Feature': feature_names_p, 'SHAP values': shap_summary_list_p_t})

print(shap_summary_df_p_t)
```

Feature  SHAP values
0              is_ndgn     0.003421
1              rx_prev     0.000835
2           wf_prev_r5     0.032605
3   wf_prev_acres5_lim     0.024776
4              n_pinus     0.046897
5              n_salix     0.003180
6              n_qurcs     0.009106
7              n_popls     0.004238
8              n_thuja     0.006751
9              n_xrphy     0.004971
10             n_rubus     0.013184

```{python}
fig = plt.figure(figsize=(6,6))

feature_names_p = ["Is Indigenous", "Previous prescribed burn", "Previous wildfire rolling sum", "Previous wildfire acreage rolling sum", "Ponderosa Pine", "Scouler's Willow", "Oregon White Oak", "Black Cottonwood", "Western Redcedar", "Beargrass", "California Blackberry"]

shap.summary_plot(shap_values = shap_values_p_t, 
                  features = X_test_p.values,
                  feature_names = feature_names_p,
                  class_names = class_labs,
                  plot_type='bar',
                  max_display=15,
                  show=False)
plt.tight_layout()
plt.xlabel("Mean absolute SHAP value")
plt.savefig("../images/shap_summary_ndgn_plnt_rx_wf_p.png")
plt.show()

# average impact on model output magnitude
```