<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Spencer Fiden">
<meta name="dcterms.date" content="2026-05-29">

<title>capstone test</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="shapefile-test_files/libs/clipboard/clipboard.min.js"></script>
<script src="shapefile-test_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="shapefile-test_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="shapefile-test_files/libs/quarto-html/popper.min.js"></script>
<script src="shapefile-test_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="shapefile-test_files/libs/quarto-html/anchor.min.js"></script>
<link href="shapefile-test_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="shapefile-test_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="shapefile-test_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="shapefile-test_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="shapefile-test_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">capstone test</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Spencer Fiden </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># importing libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'sf' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.14.1, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE</code></pre>
</div>
</div>
<section id="landmark-data" class="level1">
<h1>LandMark data</h1>
<p>Initial test of LandMark polygon data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>shp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"/Users/nikolefiden/Desktop/DATA-510/Indigenous_comm_lands_v202509/LandMark_IPLC_poly_public_v202509.shp"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LandMark_IPLC_poly_public_v202509' from data source 
  `/Users/nikolefiden/Desktop/DATA-510/Indigenous_comm_lands_v202509/LandMark_IPLC_poly_public_v202509.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 124616 features and 26 fields
Geometry type: MULTIPOLYGON
Dimension:     XY, XYZ
Bounding box:  xmin: -19936490 ymin: -7041268 xmax: 19974720 ymax: 18422210
z_range:       zmin: 0 zmax: 333.9655
Projected CRS: WGS 84 / Pseudo-Mercator</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>shp <span class="ot">=</span> <span class="fu">st_zm</span>(shp) <span class="co"># removing z-coordinate as it is not needed for our purposes</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(shp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(shp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 26 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 14360270 ymin: -2730689 xmax: 15089150 ymax: -1217191
Projected CRS: WGS 84 / Pseudo-Mercator
    identity                                     name             form_rec
1 Indigenous                            Croker Island Acknowledged by govt
2 Indigenous                            Alice Springs Acknowledged by govt
3 Indigenous               St Vidgeon'S (Roper River) Acknowledged by govt
4 Indigenous                        Urapunga Township Acknowledged by govt
5 Indigenous Miriuwung-Gajerrong (Northern Territory) Acknowledged by govt
6 Indigenous                      Davenport/Murchison Acknowledged by govt
  doc_status  stat_date             stat_note   country
1 Documented 1998/09/04 In effect - Finalised Australia
2 Documented 2000/05/23 In effect - Finalised Australia
3 Documented 2000/11/14 In effect - Finalised Australia
4 Documented 2002/02/07 In effect - Finalised Australia
5 Documented 2003/12/09 In effect - Finalised Australia
6 Documented 2004/04/23 In effect - Finalised Australia
                      category
1 Native Title (Non-Exclusive)
2 Native Title (Non-Exclusive)
3 Native Title (Non-Exclusive)
4     Native Title (Exclusive)
5 Native Title (Non-Exclusive)
6     Native Title (Exclusive)
                                                                                                                                                                                    ethncty_1
1                                                                                        Yuwurruma members of the Mandilarri-Ildugij, Mangalara, Murran, Gadura-Minaga, and Ngaynjaharr clans
2                                                                                                                                                               Mbantuarinya/ Arrernte People
3                                                                                                                                                Wandarang, Alawa, Marra and Ngalakan Peoples
4                                                                                                                                                                         The Ngalakan People
5                                                                                                                                            Damberal, Bindjen and Nyawamnyawam estate groups
6 Aboriginal persons who are members of one or more of the seven landholding groups; Arrawatyen, Antarrengeny, Akweranty/Anwerret, Lyentyawal Ileparranem, Tyaw, Warwepenty and Kelantyerrang
  populatn pop_source pop_year area_ofcl     area_gis scale method
1        0       &lt;NA&gt;        0  293469.4 293432.54524  &lt;NA&gt;   &lt;NA&gt;
2        0       &lt;NA&gt;        0   13491.7  13491.65897  &lt;NA&gt;   &lt;NA&gt;
3        0       &lt;NA&gt;        0  642724.4 642724.41713  &lt;NA&gt;   &lt;NA&gt;
4        0       &lt;NA&gt;        0      47.4     47.44239  &lt;NA&gt;   &lt;NA&gt;
5        0       &lt;NA&gt;        0   59182.6  59182.53913  &lt;NA&gt;   &lt;NA&gt;
6        0       &lt;NA&gt;        0      26.9     26.91867  &lt;NA&gt;   &lt;NA&gt;
           data_ctrb                       data_src data_src_s
1 Publicly available National Native Title Tribunal       NNTT
2 Publicly available National Native Title Tribunal       NNTT
3 Publicly available National Native Title Tribunal       NNTT
4 Publicly available National Native Title Tribunal       NNTT
5 Publicly available National Native Title Tribunal       NNTT
6 Publicly available National Native Title Tribunal       NNTT
                      data_src_l  data_date add_note
1 National Native Title Tribunal 2024/01/05     &lt;NA&gt;
2 National Native Title Tribunal 2024/01/05     &lt;NA&gt;
3 National Native Title Tribunal 2024/01/05     &lt;NA&gt;
4 National Native Title Tribunal 2024/01/05     &lt;NA&gt;
5 National Native Title Tribunal 2024/01/05     &lt;NA&gt;
6 National Native Title Tribunal 2024/01/05     &lt;NA&gt;
                                                                              more_info
1 https://www.judgments.fedcourt.gov.au/judgments/Judgments/fca/single/1998/1998fca1185
2                              http://www.austlii.edu.au/au/cases/cth/FCA/2000/671.html
3                              http://www.austlii.edu.au/au/cases/cth/FCA/2000/923.html
4                                                               http://www.nntt.gov.au/
5                            http://www.austlii.edu.au/au/cases/cth/FCAFC/2003/283.html
6                              http://www.austlii.edu.au/au/cases/cth/FCA/2004/472.html
             layer download iso_code                       geometry
1 Indigenous Lands      Yes      AUS MULTIPOLYGON (((14797122 -1...
2 Indigenous Lands      Yes      AUS MULTIPOLYGON (((14889785 -2...
3 Indigenous Lands      Yes      AUS MULTIPOLYGON (((15011750 -1...
4 Indigenous Lands      Yes      AUS MULTIPOLYGON (((14973594 -1...
5 Indigenous Lands      Yes      AUS MULTIPOLYGON (((14365622 -1...
6 Indigenous Lands      Yes      AUS MULTIPOLYGON (((15048008 -2...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(shp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "identity"   "name"       "form_rec"   "doc_status" "stat_date" 
 [6] "stat_note"  "country"    "category"   "ethncty_1"  "populatn"  
[11] "pop_source" "pop_year"   "area_ofcl"  "area_gis"   "scale"     
[16] "method"     "data_ctrb"  "data_src"   "data_src_s" "data_src_l"
[21] "data_date"  "add_note"   "more_info"  "layer"      "download"  
[26] "iso_code"   "geometry"  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#st_geometry(shp[1, ])[[1]][[1]] </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># can run but output is very long</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(shp[<span class="dv">1</span>, ]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/LandMark%20test-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All looks good, example shape plots appropriately.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># checking dtype for each col for docs</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(shp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'sf' and 'data.frame':  124616 obs. of  27 variables:
 $ identity  : chr  "Indigenous" "Indigenous" "Indigenous" "Indigenous" ...
 $ name      : chr  "Croker Island" "Alice Springs" "St Vidgeon'S (Roper River)" "Urapunga Township" ...
 $ form_rec  : chr  "Acknowledged by govt" "Acknowledged by govt" "Acknowledged by govt" "Acknowledged by govt" ...
 $ doc_status: chr  "Documented" "Documented" "Documented" "Documented" ...
 $ stat_date : chr  "1998/09/04" "2000/05/23" "2000/11/14" "2002/02/07" ...
 $ stat_note : chr  "In effect - Finalised" "In effect - Finalised" "In effect - Finalised" "In effect - Finalised" ...
 $ country   : chr  "Australia" "Australia" "Australia" "Australia" ...
 $ category  : chr  "Native Title (Non-Exclusive)" "Native Title (Non-Exclusive)" "Native Title (Non-Exclusive)" "Native Title (Exclusive)" ...
 $ ethncty_1 : chr  "Yuwurruma members of the Mandilarri-Ildugij, Mangalara, Murran, Gadura-Minaga, and Ngaynjaharr clans" "Mbantuarinya/ Arrernte People" "Wandarang, Alawa, Marra and Ngalakan Peoples" "The Ngalakan People" ...
 $ populatn  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ pop_source: chr  NA NA NA NA ...
 $ pop_year  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ area_ofcl : num  293469.4 13491.7 642724.4 47.4 59182.6 ...
 $ area_gis  : num  293432.5 13491.7 642724.4 47.4 59182.5 ...
 $ scale     : chr  NA NA NA NA ...
 $ method    : chr  NA NA NA NA ...
 $ data_ctrb : chr  "Publicly available" "Publicly available" "Publicly available" "Publicly available" ...
 $ data_src  : chr  "National Native Title Tribunal" "National Native Title Tribunal" "National Native Title Tribunal" "National Native Title Tribunal" ...
 $ data_src_s: chr  "NNTT" "NNTT" "NNTT" "NNTT" ...
 $ data_src_l: chr  "National Native Title Tribunal" "National Native Title Tribunal" "National Native Title Tribunal" "National Native Title Tribunal" ...
 $ data_date : chr  "2024/01/05" "2024/01/05" "2024/01/05" "2024/01/05" ...
 $ add_note  : chr  NA NA NA NA ...
 $ more_info : chr  "https://www.judgments.fedcourt.gov.au/judgments/Judgments/fca/single/1998/1998fca1185" "http://www.austlii.edu.au/au/cases/cth/FCA/2000/671.html" "http://www.austlii.edu.au/au/cases/cth/FCA/2000/923.html" "http://www.nntt.gov.au/" ...
 $ layer     : chr  "Indigenous Lands" "Indigenous Lands" "Indigenous Lands" "Indigenous Lands" ...
 $ download  : chr  "Yes" "Yes" "Yes" "Yes" ...
 $ iso_code  : chr  "AUS" "AUS" "AUS" "AUS" ...
 $ geometry  :sfc_MULTIPOLYGON of length 124616; first list element: List of 1
  ..$ :List of 48
  .. ..$ : num [1:282, 1:2] 14797122 14797122 14796999 14796702 14796561 ...
  .. ..$ : num [1:13, 1:2] 14775079 14775037 14774694 14774650 14774661 ...
  .. ..$ : num [1:48, 1:2] 14781077 14780948 14780858 14780679 14780544 ...
  .. ..$ : num [1:8, 1:2] 14781255 14781352 14781437 14781561 14781641 ...
  .. ..$ : num [1:27, 1:2] 14775653 14775808 14775725 14775742 14775674 ...
  .. ..$ : num [1:68, 1:2] 14770140 14770085 14769742 14769256 14769127 ...
  .. ..$ : num [1:638, 1:2] 14758810 14758693 14758662 14758749 14758800 ...
  .. ..$ : num [1:9, 1:2] 14750692 14750596 14750548 14750414 14750407 ...
  .. ..$ : num [1:5, 1:2] 14750636 14750716 14750728 14750674 14750636 ...
  .. ..$ : num [1:5, 1:2] 14748194 14748139 14748145 14748201 14748194 ...
  .. ..$ : num [1:5, 1:2] 14759666 14759637 14759612 14759636 14759666 ...
  .. ..$ : num [1:24, 1:2] 14745272 14745216 14745169 14745143 14745082 ...
  .. ..$ : num [1:9, 1:2] 14786184 14786264 14786398 14786375 14786257 ...
  .. ..$ : num [1:33, 1:2] 14785969 14786077 14786038 14786064 14786127 ...
  .. ..$ : num [1:8, 1:2] 14785357 14785296 14785277 14785296 14785522 ...
  .. ..$ : num [1:100, 1:2] 14786395 14786291 14786188 14785834 14785817 ...
  .. ..$ : num [1:5, 1:2] 14785745 14785702 14785627 14785712 14785745 ...
  .. ..$ : num [1:86, 1:2] 14796215 14796356 14796344 14796052 14796043 ...
  .. ..$ : num [1:6, 1:2] 14796541 14796559 14796510 14796491 14796498 ...
  .. ..$ : num [1:5, 1:2] 14796563 14796527 14796520 14796539 14796563 ...
  .. ..$ : num [1:5, 1:2] 14796412 14796369 14796362 14796381 14796412 ...
  .. ..$ : num [1:6, 1:2] 14789906 14789932 14789955 14789974 14789931 ...
  .. ..$ : num [1:19, 1:2] 14791664 14791859 14791921 14792067 14792208 ...
  .. ..$ : num [1:33, 1:2] 14789281 14789471 14789673 14789918 14790273 ...
  .. ..$ : num [1:6, 1:2] 14791887 14791849 14791814 14791807 14791837 ...
  .. ..$ : num [1:6, 1:2] 14792060 14792116 14792158 14792153 14792080 ...
  .. ..$ : num [1:7, 1:2] 14792272 14792335 14792298 14792169 14792136 ...
  .. ..$ : num [1:6, 1:2] 14793106 14793149 14793179 14793106 14793038 ...
  .. ..$ : num [1:6, 1:2] 14792532 14792569 14792588 14792551 14792532 ...
  .. ..$ : num [1:5, 1:2] 14792962 14792918 14792913 14792955 14792962 ...
  .. ..$ : num [1:5, 1:2] 14786366 14786451 14786453 14786392 14786366 ...
  .. ..$ : num [1:6, 1:2] 14786446 14786507 14786533 14786526 14786446 ...
  .. ..$ : num [1:6, 1:2] 14786847 14786876 14786957 14786917 14786879 ...
  .. ..$ : num [1:12, 1:2] 14796799 14796755 14796779 14796809 14796889 ...
  .. ..$ : num [1:4, 1:2] 14797047 14797047 14796991 14797047 -1250786 ...
  .. ..$ : num [1:6, 1:2] 14796989 14797032 14797038 14796984 14796965 ...
  .. ..$ : num [1:5, 1:2] 14796734 14796777 14796796 14796741 14796734 ...
  .. ..$ : num [1:8, 1:2] 14806496 14806374 14806386 14806219 14806172 ...
  .. ..$ : num [1:7, 1:2] 14807301 14807294 14807233 14807233 14807184 ...
  .. ..$ : num [1:6, 1:2] 14807456 14807425 14807364 14807352 14807376 ...
  .. ..$ : num [1:5, 1:2] 14807475 14807444 14807401 14807439 14807475 ...
  .. ..$ : num [1:61, 1:2] 14805491 14805088 14804928 14804723 14804308 ...
  .. ..$ : num [1:7, 1:2] 14802290 14802229 14802199 14802275 14802307 ...
  .. ..$ : num [1:55, 1:2] 14809722 14809802 14810008 14810059 14810132 ...
  .. ..$ : num [1:12, 1:2] 14810469 14810479 14810489 14810496 14810489 ...
  .. ..$ : num [1:9, 1:2] 14810248 14810243 14810226 14810226 14810233 ...
  .. ..$ : num [1:10, 1:2] 14810313 14810309 14810294 14810279 14810279 ...
  .. ..$ : num [1:13, 1:2] 14810422 14810433 14810430 14810432 14810427 ...
  ..- attr(*, "class")= chr [1:3] "XY" "MULTIPOLYGON" "sfg"
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "names")= chr [1:26] "identity" "name" "form_rec" "doc_status" ...</code></pre>
</div>
</div>
<p>Limiting the data to the USA, removing some Alaska Native Allotment, and plotting again (takes a lot longer to run). Looks good, plotted appropriately.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>us_shp <span class="ot">&lt;-</span> shp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(iso_code <span class="sc">==</span> <span class="st">"USA"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_shp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 26 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -17790970 ymin: 7978735 xmax: -14918560 ymax: 10060490
Projected CRS: WGS 84 / Pseudo-Mercator
    identity                                  name             form_rec
1 Indigenous  BLM ALIS Case Number - AKA    002493 Acknowledged by govt
2 Indigenous  BLM ALIS Case Number - AKA    002493 Acknowledged by govt
3 Indigenous  BLM ALIS Case Number - AKA    002493 Acknowledged by govt
4 Indigenous  BLM ALIS Case Number - AKA    002876 Acknowledged by govt
5 Indigenous BLM ALIS Case Number - AKFF   018946C Acknowledged by govt
6 Indigenous  BLM ALIS Case Number - AKFF   017876 Acknowledged by govt
  doc_status stat_date stat_note                  country
1 Documented      &lt;NA&gt;      &lt;NA&gt; United States of America
2 Documented      &lt;NA&gt;      &lt;NA&gt; United States of America
3 Documented      &lt;NA&gt;      &lt;NA&gt; United States of America
4 Documented      &lt;NA&gt;      &lt;NA&gt; United States of America
5 Documented      &lt;NA&gt;      &lt;NA&gt; United States of America
6 Documented      &lt;NA&gt;      &lt;NA&gt; United States of America
                 category ethncty_1 populatn pop_source pop_year area_ofcl
1 Alaska Native Allotment      &lt;NA&gt;        0       &lt;NA&gt;        0         0
2 Alaska Native Allotment      &lt;NA&gt;        0       &lt;NA&gt;        0         0
3 Alaska Native Allotment      &lt;NA&gt;        0       &lt;NA&gt;        0         0
4 Alaska Native Allotment      &lt;NA&gt;        0       &lt;NA&gt;        0         0
5 Alaska Native Allotment      &lt;NA&gt;        0       &lt;NA&gt;        0         0
6 Alaska Native Allotment      &lt;NA&gt;        0       &lt;NA&gt;        0         0
    area_gis scale         method          data_ctrb                  data_src
1  8.1243131  &lt;NA&gt; Survey records Publicly available Bureau of Land Management
2 23.7423496  &lt;NA&gt; Survey records Publicly available Bureau of Land Management
3 14.4080953  &lt;NA&gt; Survey records Publicly available Bureau of Land Management
4  0.7282587  &lt;NA&gt; Survey records Publicly available Bureau of Land Management
5 16.1888918  &lt;NA&gt; Survey records Publicly available Bureau of Land Management
6 64.7360386  &lt;NA&gt; Survey records Publicly available Bureau of Land Management
  data_src_s                      data_src_l  data_date add_note
1        BLM Bureau of Land Management (BLM) 2015/08/31     &lt;NA&gt;
2        BLM Bureau of Land Management (BLM) 2015/08/31     &lt;NA&gt;
3        BLM Bureau of Land Management (BLM) 2015/08/31     &lt;NA&gt;
4        BLM Bureau of Land Management (BLM) 2015/08/31     &lt;NA&gt;
5        BLM Bureau of Land Management (BLM) 2015/08/31     &lt;NA&gt;
6        BLM Bureau of Land Management (BLM) 2015/08/31     &lt;NA&gt;
               more_info            layer download iso_code
1 http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
2 http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
3 http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
4 http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
5 http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
6 http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
                        geometry
1 MULTIPOLYGON (((-15117378 7...
2 MULTIPOLYGON (((-15116185 7...
3 MULTIPOLYGON (((-15116727 7...
4 MULTIPOLYGON (((-14918648 7...
5 MULTIPOLYGON (((-17790973 1...
6 MULTIPOLYGON (((-16868947 9...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_shp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(category <span class="sc">!=</span> <span class="st">"Alaska Native Allotment"</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 26 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -17659990 ymin: 8180262 xmax: -17611500 ymax: 8277694
Projected CRS: WGS 84 / Pseudo-Mercator
    identity                                   name                 form_rec
1 Indigenous BLM ALIS Case Number - AKAA   006648 O Not acknowledged by govt
2 Indigenous BLM ALIS Case Number - AKAA   006648 P Not acknowledged by govt
3 Indigenous BLM ALIS Case Number - AKAA   006659 A Not acknowledged by govt
                                     doc_status stat_date stat_note
1 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
2 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
3 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
                   country       category ethncty_1 populatn pop_source
1 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
2 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
3 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
  pop_year area_ofcl  area_gis scale
1        0         0  258.9986  &lt;NA&gt;
2        0         0 3595.7292  &lt;NA&gt;
3        0         0 7456.8273  &lt;NA&gt;
                                             method          data_ctrb
1 Generalized to Protracted Section Grid for Alaska Publicly available
2 Generalized to Protracted Section Grid for Alaska Publicly available
3 Generalized to Protracted Section Grid for Alaska Publicly available
                   data_src data_src_s                      data_src_l
1 Bureau of Land Management        BLM Bureau of Land Management (BLM)
2 Bureau of Land Management        BLM Bureau of Land Management (BLM)
3 Bureau of Land Management        BLM Bureau of Land Management (BLM)
   data_date add_note              more_info            layer download iso_code
1 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
2 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
3 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
                        geometry
1 MULTIPOLYGON (((-17611498 8...
2 MULTIPOLYGON (((-17617263 8...
3 MULTIPOLYGON (((-17659977 8...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(us_shp<span class="sc">$</span>category)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Alaska Native Allotment"                                   
[2] "ANCSA Selected"                                            
[3] "Metlakatla Indian Reservation"                             
[4] "ANCSA Conveyance - patented"                               
[5] "ANCSA Conveyance - interim conveyed"                       
[6] "ANCSA Conveyance - conveyed other"                         
[7] "American Indian and Alaska Native Land Area Representation"
[8] "AIAN National LAR Supplemental"                            </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>us_shp <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">st_is_empty</span>(geometry), category <span class="sc">!=</span> <span class="st">"Alaska Native Allotment"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/LandMark%20US%20test-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_shp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">st_is_empty</span>(geometry), category <span class="sc">!=</span> <span class="st">"Alaska Native Allotment"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 26 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -17689100 ymin: 8180262 xmax: -16586680 ymax: 8707575
Projected CRS: WGS 84 / Pseudo-Mercator
    identity                                   name                 form_rec
1 Indigenous BLM ALIS Case Number - AKAA   006648 O Not acknowledged by govt
2 Indigenous BLM ALIS Case Number - AKAA   006648 P Not acknowledged by govt
3 Indigenous BLM ALIS Case Number - AKAA   006659 A Not acknowledged by govt
4 Indigenous BLM ALIS Case Number - AKAA   006659 I Not acknowledged by govt
5 Indigenous BLM ALIS Case Number - AKAA   006661 F Not acknowledged by govt
6 Indigenous BLM ALIS Case Number - AKAA   006664 F Not acknowledged by govt
                                     doc_status stat_date stat_note
1 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
2 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
3 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
4 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
5 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
6 Held or used with formal land claim submitted      &lt;NA&gt;      &lt;NA&gt;
                   country       category ethncty_1 populatn pop_source
1 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
2 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
3 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
4 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
5 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
6 United States of America ANCSA Selected      &lt;NA&gt;        0       &lt;NA&gt;
  pop_year area_ofcl  area_gis scale
1        0         0  258.9986  &lt;NA&gt;
2        0         0 3595.7292  &lt;NA&gt;
3        0         0 7456.8273  &lt;NA&gt;
4        0         0 2848.9840  &lt;NA&gt;
5        0         0  268.1071  &lt;NA&gt;
6        0         0  486.8708  &lt;NA&gt;
                                             method          data_ctrb
1 Generalized to Protracted Section Grid for Alaska Publicly available
2 Generalized to Protracted Section Grid for Alaska Publicly available
3 Generalized to Protracted Section Grid for Alaska Publicly available
4 Generalized to Protracted Section Grid for Alaska Publicly available
5 Generalized to Protracted Section Grid for Alaska Publicly available
6 Generalized to Protracted Section Grid for Alaska Publicly available
                   data_src data_src_s                      data_src_l
1 Bureau of Land Management        BLM Bureau of Land Management (BLM)
2 Bureau of Land Management        BLM Bureau of Land Management (BLM)
3 Bureau of Land Management        BLM Bureau of Land Management (BLM)
4 Bureau of Land Management        BLM Bureau of Land Management (BLM)
5 Bureau of Land Management        BLM Bureau of Land Management (BLM)
6 Bureau of Land Management        BLM Bureau of Land Management (BLM)
   data_date add_note              more_info            layer download iso_code
1 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
2 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
3 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
4 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
5 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
6 2015/08/31     &lt;NA&gt; http://sdms.ak.blm.gov Indigenous Lands      Yes      USA
                        geometry
1 MULTIPOLYGON (((-17611498 8...
2 MULTIPOLYGON (((-17617263 8...
3 MULTIPOLYGON (((-17659977 8...
4 MULTIPOLYGON (((-17651556 8...
5 MULTIPOLYGON (((-16586676 8...
6 MULTIPOLYGON (((-16712008 8...</code></pre>
</div>
</div>
<p>Plotting with the sf <code>plot</code> function instead of ggplot - also works.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(us_shp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/plot%20LandMark%20US%20with%20sf-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="landmark-point-data" class="level2">
<h2 class="anchored" data-anchor-id="landmark-point-data">LandMark Point Data</h2>
<p>LandMark also has point data, which will be far less relevant to us, but can confirm it works as expected.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>shppt <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"/Users/nikolefiden/Desktop/DATA-510/Indigenous_comm_lands_v202509/LandMark_IPLC_pt_public_v202509.shp"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LandMark_IPLC_pt_public_v202509' from data source 
  `/Users/nikolefiden/Desktop/DATA-510/Indigenous_comm_lands_v202509/LandMark_IPLC_pt_public_v202509.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 2646 features and 26 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -19391920 ymin: -3554163 xmax: 11961370 ymax: 11502370
Projected CRS: WGS 84 / Pseudo-Mercator</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(shppt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(shppt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 26 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -6157938 ymin: -2747755 xmax: -5029304 ymax: -358598.9
Projected CRS: WGS 84 / Pseudo-Mercator
                                  name   identity             form_rec
1                          Taquaritiua Indigenous Acknowledged by govt
2                            Vitoi Kuê Indigenous Acknowledged by govt
3             Dourados-Amambaipeguá II Indigenous Acknowledged by govt
4         Laguna Piru (Nhandeva Peguá) Indigenous Acknowledged by govt
5 Laranjeira Nhanderu (Brilhantepeguá) Indigenous Acknowledged by govt
6           Potrerito (Nhandeva Peguá) Indigenous Acknowledged by govt
      doc_status stat_date stat_note country iso_code
1 Not documented      &lt;NA&gt; Em Estudo  Brazil      BRA
2 Not documented      &lt;NA&gt; Em Estudo  Brazil      BRA
3 Not documented      &lt;NA&gt; Em Estudo  Brazil      BRA
4 Not documented      &lt;NA&gt; Em Estudo  Brazil      BRA
5 Not documented      &lt;NA&gt; Em Estudo  Brazil      BRA
6 Not documented      &lt;NA&gt; Em Estudo  Brazil      BRA
                                 category      ethncty_1 populatn pop_source
1 Terra Indígena Tradicionalmente Ocupada         Gamela        0       &lt;NA&gt;
2 Terra Indígena Tradicionalmente Ocupada        Guaraní        0       &lt;NA&gt;
3 Terra Indígena Tradicionalmente Ocupada        Guaraní        0       &lt;NA&gt;
4 Terra Indígena Tradicionalmente Ocupada        Guaraní        0       &lt;NA&gt;
5 Terra Indígena Tradicionalmente Ocupada Guarani Kaiowá        0       &lt;NA&gt;
6 Terra Indígena Tradicionalmente Ocupada        Guaraní        0       &lt;NA&gt;
  pop_year area_ofcl area_gis scale method          data_ctrb
1        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
2        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
3        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
4        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
5        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
6        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
                                       data_src data_src_s
1 Fundação Nacional dos Povos Indígenas - FUNAI      FUNAI
2 Fundação Nacional dos Povos Indígenas - FUNAI      FUNAI
3 Fundação Nacional dos Povos Indígenas - FUNAI      FUNAI
4 Fundação Nacional dos Povos Indígenas - FUNAI      FUNAI
5 Fundação Nacional dos Povos Indígenas - FUNAI      FUNAI
6 Fundação Nacional dos Povos Indígenas - FUNAI      FUNAI
                                     data_src_l  data_date add_note
1 Fundação Nacional dos Povos Indígenas - FUNAI 2023/10/06     &lt;NA&gt;
2 Fundação Nacional dos Povos Indígenas - FUNAI 2023/10/06     &lt;NA&gt;
3 Fundação Nacional dos Povos Indígenas - FUNAI 2023/10/06     &lt;NA&gt;
4 Fundação Nacional dos Povos Indígenas - FUNAI 2023/10/06     &lt;NA&gt;
5 Fundação Nacional dos Povos Indígenas - FUNAI 2023/10/06     &lt;NA&gt;
6 Fundação Nacional dos Povos Indígenas - FUNAI 2023/10/06     &lt;NA&gt;
                       more_info            layer download
1 https://www.gov.br/funai/pt-br Indigenous Lands      Yes
2 https://www.gov.br/funai/pt-br Indigenous Lands      Yes
3 https://www.gov.br/funai/pt-br Indigenous Lands      Yes
4 https://www.gov.br/funai/pt-br Indigenous Lands      Yes
5 https://www.gov.br/funai/pt-br Indigenous Lands      Yes
6 https://www.gov.br/funai/pt-br Indigenous Lands      Yes
                    geometry
1 POINT (-5029304 -358598.9)
2  POINT (-6050982 -2747755)
3  POINT (-6040648 -2640527)
4  POINT (-6040062 -2705956)
5  POINT (-6073090 -2496056)
6  POINT (-6157938 -2739669)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#st_geometry(shppt[1, ])[[1]][[1]]</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># again can run but output is very long</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(shppt[<span class="dv">1</span>, ]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>us_shppt <span class="ot">&lt;-</span> shppt <span class="sc">%&gt;%</span> <span class="fu">filter</span>(iso_code <span class="sc">==</span> <span class="st">"USA"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_shppt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 26 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -18163540 ymin: 7373850 xmax: -16992430 ymax: 10033390
Projected CRS: WGS 84 / Pseudo-Mercator
       name   identity             form_rec doc_status stat_date stat_note
1  Agdaagux Indigenous Acknowledged by govt Documented      &lt;NA&gt;      &lt;NA&gt;
2  Akiachak Indigenous Acknowledged by govt Documented      &lt;NA&gt;      &lt;NA&gt;
3     Akiak Indigenous Acknowledged by govt Documented      &lt;NA&gt;      &lt;NA&gt;
4    Alatna Indigenous Acknowledged by govt Documented      &lt;NA&gt;      &lt;NA&gt;
5  Algaaciq Indigenous Acknowledged by govt Documented      &lt;NA&gt;      &lt;NA&gt;
6 Allakaket Indigenous Acknowledged by govt Documented      &lt;NA&gt;      &lt;NA&gt;
                   country iso_code               category ethncty_1 populatn
1 United States of America      USA Alaska Native Villages      &lt;NA&gt;        0
2 United States of America      USA Alaska Native Villages      &lt;NA&gt;        0
3 United States of America      USA Alaska Native Villages      &lt;NA&gt;        0
4 United States of America      USA Alaska Native Villages      &lt;NA&gt;        0
5 United States of America      USA Alaska Native Villages      &lt;NA&gt;        0
6 United States of America      USA Alaska Native Villages      &lt;NA&gt;        0
  pop_source pop_year area_ofcl area_gis scale method          data_ctrb
1       &lt;NA&gt;        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
2       &lt;NA&gt;        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
3       &lt;NA&gt;        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
4       &lt;NA&gt;        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
5       &lt;NA&gt;        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
6       &lt;NA&gt;        0         0        0  &lt;NA&gt;   &lt;NA&gt; Publicly available
                  data_src data_src_s               data_src_l   data_date
1 Bureau of Indian Affairs        BIA Bureau of Indian Affairs 29 May 2024
2 Bureau of Indian Affairs        BIA Bureau of Indian Affairs 29 May 2024
3 Bureau of Indian Affairs        BIA Bureau of Indian Affairs 29 May 2024
4 Bureau of Indian Affairs        BIA Bureau of Indian Affairs 29 May 2024
5 Bureau of Indian Affairs        BIA Bureau of Indian Affairs 29 May 2024
6 Bureau of Indian Affairs        BIA Bureau of Indian Affairs 29 May 2024
                                                            add_note
1             Tribal leadership locations; Alternate name: King Cove
2                                        Tribal leadership locations
3                                        Tribal leadership locations
4 Tribal leadership locations; Alternate name: Alatna Tribal Council
5            Tribal leadership locations; Alternate name: St. Mary's
6                                        Tribal leadership locations
                         more_info            layer download
1 https://biamaps.geoplatform.gov/ Indigenous Lands      Yes
2 https://biamaps.geoplatform.gov/ Indigenous Lands      Yes
3 https://biamaps.geoplatform.gov/ Indigenous Lands      Yes
4 https://biamaps.geoplatform.gov/ Indigenous Lands      Yes
5 https://biamaps.geoplatform.gov/ Indigenous Lands      Yes
6 https://biamaps.geoplatform.gov/ Indigenous Lands      Yes
                    geometry
1  POINT (-18068302 7373850)
2  POINT (-17970464 8605050)
3  POINT (-17946252 8605691)
4 POINT (-16999291 10031038)
5  POINT (-18163536 8871745)
6 POINT (-16992434 10033389)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(us_shppt<span class="sc">$</span>category)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Alaska Native Villages"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ggplot(data=us_shp) + geom_sf()</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>us_shppt <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">st_is_empty</span>(geometry)) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="interagency-fire-perimeter-history" class="level1">
<h1>Interagency Fire Perimeter History</h1>
<p>Moving on to IFPH data, which covers many years where the LM data is relatively static.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># i don't know why I called it IAFP instead of IFPH. don't worry about it</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>iafp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"/Users/nikolefiden/Desktop/DATA-510/InterAgencyFirePerimeterHistory_All_Years_View/InteragencyFirePerimeterHistory.shp"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `InteragencyFirePerimeterHistory' from data source 
  `/Users/nikolefiden/Desktop/DATA-510/InterAgencyFirePerimeterHistory_All_Years_View/InteragencyFirePerimeterHistory.shp' 
  using driver `ESRI Shapefile'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, : GDAL
Message 1:
/Users/nikolefiden/Desktop/DATA-510/InterAgencyFirePerimeterHistory_All_Years_View/InteragencyFirePerimeterHistory.shp
contains polygon(s) with rings with invalid winding order. Autocorrecting them,
but that shapefile should be corrected using ogr2ogr for example.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 116337 features and 18 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -19908540 ymin: 377500.3 xmax: 16125010 ymax: 11120630
Projected CRS: WGS 84 / Pseudo-Mercator</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(iafp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iafp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 18 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -11778610 ymin: 3771761 xmax: -11652870 ymax: 3981859
Projected CRS: WGS 84 / Pseudo-Mercator
                                 IRWINID                                  FORID
1                                   &lt;NA&gt;                                   &lt;NA&gt;
2 {305E7BCF-5630-4B74-B046-9E6CA71B189D} {5CE0191D-4E64-4552-9052-40C22FEBCAB3}
3                                   &lt;NA&gt;                                   &lt;NA&gt;
4                                   &lt;NA&gt;                                   &lt;NA&gt;
5                                   &lt;NA&gt;                                   &lt;NA&gt;
6                                   &lt;NA&gt;                                   &lt;NA&gt;
    INCIDENT GIS_ACRES        UNQE_FIRE_       DATE_CUR FIRE_YEAR_ UNIT_ID
1       Read     10.92 2013-NMLNF-000015 20140201000000       2013   NMLNF
2 Blue Front    323.20 2024-NMLNF-000552 20241125192323       2024   NMLNF
3     Ussery     35.93 1978-NMLNF-000030 19940201000000       1978   NMLNF
4     Yankee    127.12 1968-NMLNF-000004 19940201000000       1968   NMLNF
5   Antelope     90.14 2005-NMLNF-000015 20060201000000       2005   NMLNF
6    Crooked     72.37 2005-NMLNF-000016 20060201000000       2005   NMLNF
  POO_RESP_I LOCAL_NUM                    FEATURE_CA
1      NMLNF    000015 Wildfire Final Fire Perimeter
2      NMLNF    000552 Wildfire Final Fire Perimeter
3      NMLNF    000030 Wildfire Final Fire Perimeter
4      NMLNF    000004 Wildfire Final Fire Perimeter
5      NMLNF    000015 Wildfire Final Fire Perimeter
6      NMLNF    000016 Wildfire Final Fire Perimeter
                       MAP_METHOD
1          GPS - Uncorrected Data
2            Other Agency Digital
3 Digitized From Hardcopy PBS/SEQ
4 Digitized From Hardcopy PBS/SEQ
5 Digitized From Hardcopy PBS/SEQ
6 Digitized From Hardcopy PBS/SEQ
                                                                          COMMENTS
1                                       Data received from district fire personnel
2 Smokey Bear RD, White Mountain Wilderness, Southfork Campground, Crest Trail, Sk
3                                          Individual fire report used to populate
4                                          Individual fire report used to populate
5                                                                             &lt;NA&gt;
6                                                                             &lt;NA&gt;
                                  GEO_ID SOURCE AGENCY FIRE_YEAR
1 {29F9DCCC-6429-4CB7-9797-0A1FDE5339B7}   USFS   USFS      2013
2 {6D8FB68C-8995-4C2B-AA82-C879AC2B4258}   USFS   USFS      2024
3 {BA6ACBC9-5084-4968-BA28-F8839214B5C9}   USFS   USFS      1978
4 {EEC624E6-68C7-4651-A5DA-26676E8131C4}   USFS   USFS      1968
5 {8337EF53-01A2-4DB6-B862-2098CA0D4C69}   USFS   USFS      2005
6 {D69E4F1D-7082-48A9-B4E7-C4E39109DA35}   USFS   USFS      2005
                              GlobalID                       geometry
1 53d18533-e3c0-41c6-9c6a-93030c142fa6 MULTIPOLYGON (((-11757376 3...
2 9e4b0e8c-a1f1-4df5-b26b-c60ceaf9cbaa MULTIPOLYGON (((-11777537 3...
3 b7b568a0-db32-4ee1-8edc-c4824a834023 MULTIPOLYGON (((-11653388 3...
4 07884dee-9530-4312-b50a-24ea85798251 MULTIPOLYGON (((-11745792 3...
5 f4005d3c-950b-438e-b2fd-e1fb8c599b1f MULTIPOLYGON (((-11683505 3...
6 bfd67859-d4f9-4c39-8d63-ac4b2fc60d75 MULTIPOLYGON (((-11689920 3...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#st_geometry(iafp[1, ])[[1]][[1]]</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># can run but output is long</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(iafp[<span class="dv">1</span>, ]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/IFPH%20test-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(iafp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "IRWINID"    "FORID"      "INCIDENT"   "GIS_ACRES"  "UNQE_FIRE_"
 [6] "DATE_CUR"   "FIRE_YEAR_" "UNIT_ID"    "POO_RESP_I" "LOCAL_NUM" 
[11] "FEATURE_CA" "MAP_METHOD" "COMMENTS"   "GEO_ID"     "SOURCE"    
[16] "AGENCY"     "FIRE_YEAR"  "GlobalID"   "geometry"  </code></pre>
</div>
</div>
<p>Cols include a lot of things! Explained in the IFPH documentation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lengths</span>(iafp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FIRE_YEAR_ <span class="sc">&lt;=</span> <span class="dv">1900</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   IRWINID      FORID   INCIDENT  GIS_ACRES UNQE_FIRE_   DATE_CUR FIRE_YEAR_ 
      2494       2494       2494       2494       2494       2494       2494 
   UNIT_ID POO_RESP_I  LOCAL_NUM FEATURE_CA MAP_METHOD   COMMENTS     GEO_ID 
      2494       2494       2494       2494       2494       2494       2494 
    SOURCE     AGENCY  FIRE_YEAR   GlobalID   geometry 
      2494       2494       2494       2494       2494 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lengths</span>(iafp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FIRE_YEAR_ <span class="sc">&gt;=</span> <span class="dv">2050</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   IRWINID      FORID   INCIDENT  GIS_ACRES UNQE_FIRE_   DATE_CUR FIRE_YEAR_ 
       268        268        268        268        268        268        268 
   UNIT_ID POO_RESP_I  LOCAL_NUM FEATURE_CA MAP_METHOD   COMMENTS     GEO_ID 
       268        268        268        268        268        268        268 
    SOURCE     AGENCY  FIRE_YEAR   GlobalID   geometry 
       268        268        268        268        268 </code></pre>
</div>
</div>
<p>2494 fires are listed at before 1900 - some are historical record, some were unknown so marked with an indicator. 268 fires are listed as later than 2050.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(iafp<span class="sc">$</span>SOURCE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "USFS"       "AICC"       "CALFIRE"    "BLM"        "WFIGS"     
[6] "NPS"        "BIA"        "WFIGS-AICC" "FWS"       </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Testing with FIRE_YEAR_ == 2022 and limiting to large fires (so it doens't take forever to run)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>iafp <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(FIRE_YEAR_ <span class="sc">==</span> <span class="dv">2022</span>, GIS_ACRES <span class="sc">&gt;</span> <span class="dv">25</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All looks good, that’s the US!</p>
</section>
<section id="st_contains" class="level1">
<h1>st_contains</h1>
<p>Getting just OR from <code>usmap</code> to filter fires/native land to our area of interest with <code>st_contains</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>states<span class="ot">&lt;-</span>usmap<span class="sc">::</span><span class="fu">us_map</span>()</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>or <span class="ot">=</span> states <span class="sc">%&gt;%</span> <span class="fu">filter</span>(abbr<span class="sc">==</span><span class="st">"OR"</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>or <span class="sc">%&gt;%</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/OR%20map-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering fires to 2020 for testing purposes (otherwise it is a lot of data)</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>iafp2020 <span class="ot">&lt;-</span> iafp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FIRE_YEAR_ <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>or <span class="ot">=</span> <span class="fu">st_transform</span>(or, <span class="at">crs=</span><span class="fu">st_crs</span>(iafp2020))</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>con <span class="ot">=</span> <span class="fu">st_contains</span>(or, iafp2020)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>con_sparse <span class="ot">=</span> <span class="fu">st_contains</span>(or, iafp2020, <span class="at">sparse=</span>F)</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>iafp2020_or <span class="ot">=</span> iafp2020[<span class="fu">unlist</span>(con),]</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iafp2020_or)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 18 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -13705340 ymin: 5350146 xmax: -13004790 ymax: 5748998
Projected CRS: WGS 84 / Pseudo-Mercator
                                   IRWINID
188 {FA38B126-32BD-408A-B042-35170B47071D}
364 {DA702D8A-CD7E-4A72-9B53-931EEFF78F4E}
365 {8D8E2A9C-3A7B-4724-8CDB-7201F413CEF8}
367 {DC9FEF19-D7AB-4500-B319-ACBA1DB2776A}
369 {47839EA3-1520-4582-B4FC-D4385699CDF1}
370 {C9370388-6098-44F9-8F5E-013F9E297ADA}
                                     FORID     INCIDENT   GIS_ACRES
188 {C1802FD3-E7DD-4B13-AD0C-93C5848283FB} Cherry Creek 1.50000e-01
364 {F945DC62-B792-4E96-9498-E148C35AC3A2}   Canal Fire 8.78717e-04
365 {C05118CA-21E2-42C7-B51C-EE5F3B4059A6} Archie Creek 1.31595e+05
367 {0773A26E-C794-487B-B6A6-1BF62E007361}    Lionshead 2.04588e+05
369 {36CB2088-FE29-4BE3-89CC-6B33510DC3F8} Mosier Creek 9.97070e+02
370 {0928A6D8-39E5-4DD0-B430-05CEDE7D73C2}       Rowena 1.38000e+01
            UNQE_FIRE_       DATE_CUR FIRE_YEAR_ UNIT_ID POO_RESP_I LOCAL_NUM
188  2020-ORWWF-000185 20200528215400       2020    &lt;NA&gt;       &lt;NA&gt;      &lt;NA&gt;
364  2020-ORWWF-000202 20201208233115       2020   ORWWF      ORWWF       202
365  2020-ORUPF-000436 20201006134849       2020   ORUPF      ORUPF    000436
367  2020-ORWSA-000077 20201009001325       2020   ORWSA      ORWSA    000077
369 2020-OR954S-000022 20200831152513       2020  OR954S     OR954S    000022
370 2020-OR954S-000269 20201208233138       2020  OR954S     OR954S    000269
                       FEATURE_CA              MAP_METHOD
188 Wildfire Final Fire Perimeter                   Other
364 Wildfire Final Fire Perimeter                   Other
365 Wildfire Final Fire Perimeter Infrared Interpretation
367 Wildfire Final Fire Perimeter Infrared Interpretation
369 Wildfire Final Fire Perimeter                   Other
370 Wildfire Final Fire Perimeter                   Other
                                                                                                                                                                                                           COMMENTS
188                                                                                                                                                                                                            &lt;NA&gt;
364                                                                                                                                                                                                            &lt;NA&gt;
365 InFORM fire record is not certified because the fire was not declared out, as of 03/22/2021. TOTALACRES field value was obtained from the field GISACRES value, because the fire is not in the InFORM database.
367                                                                            IR 20201007 2049. TOTALACRES field value was obtained from the field GISACRES value, because the fire is not in the InFORM database.
369                                                                                              TOTALACRES field value was obtained from the field GISACRES value, because the fire is not in the InFORM database.
370    Need to confirm which IRWINID - 2 Fires listed for same, most likely 1 for ODF and 1 CGF. TOTALACRES field value was obtained from the field GISACRES value, because the fire is not in the InFORM database.
                                    GEO_ID SOURCE AGENCY FIRE_YEAR
188 {73850E55-7712-49E6-81C0-AC68A27D746F}   USFS   USFS      2020
364 {89FEAF5C-C31C-402B-90D3-910728007C65}   USFS   USFS      2020
365 {B5C25104-795F-4EA4-9B6B-FE58D9EB7D0B}   USFS   USFS      2020
367 {543DC929-D0A9-45C3-9EAE-5BA3E3B6A993}   USFS   USFS      2020
369 {6D314F17-5F75-43B6-BAD9-F4C466E0EC45}   USFS   USFS      2020
370 {62D8FDBF-7113-49D7-9855-AA0B41AA2303}   USFS   USFS      2020
                                GlobalID                       geometry
188 c721939a-43c7-4428-addc-9aa1da255539 MULTIPOLYGON (((-13004787 5...
364 f6cd748a-e63a-4db4-a20a-5cbb443300f0 MULTIPOLYGON (((-13035482 5...
365 7db7b8e0-23dd-438a-b55b-2ef2eb2fe97b MULTIPOLYGON (((-13669812 5...
367 a62ae6ce-c1eb-426d-8909-dd5c4fadc874 MULTIPOLYGON (((-13591023 5...
369 0933045a-88e6-46c3-96e3-c3d512e75d24 MULTIPOLYGON (((-13506506 5...
370 d85bedc4-3095-414d-83a2-50d8654613dd MULTIPOLYGON (((-13499416 5...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>iafp2020_or <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/IFPH%202020%20in%20OR-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As far as I can tell, that’s the fires in Oregon in 2020!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>con <span class="ot">=</span> <span class="fu">st_contains</span>(or, iafp)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>con_sparse <span class="ot">=</span> <span class="fu">st_contains</span>(or, iafp, <span class="at">sparse=</span>F)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>iafp_or <span class="ot">=</span> iafp[<span class="fu">unlist</span>(con),]</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>iafp_or <span class="ot">&lt;-</span> iafp_or <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FIRE_YEAR_ <span class="sc">&gt;=</span> <span class="dv">2000</span>, FIRE_YEAR_ <span class="sc">&lt;=</span> <span class="dv">2030</span>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lengths</span>(iafp_or)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   IRWINID      FORID   INCIDENT  GIS_ACRES UNQE_FIRE_   DATE_CUR FIRE_YEAR_ 
      4139       4139       4139       4139       4139       4139       4139 
   UNIT_ID POO_RESP_I  LOCAL_NUM FEATURE_CA MAP_METHOD   COMMENTS     GEO_ID 
      4139       4139       4139       4139       4139       4139       4139 
    SOURCE     AGENCY  FIRE_YEAR   GlobalID   geometry 
      4139       4139       4139       4139       4139 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop_na</span>(<span class="fu">as.data.frame</span>(iafp_or<span class="sc">$</span>FIRE_YEAR_)) <span class="sc">%&gt;%</span> summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> iafp_or$FIRE_YEAR_
 Min.   :2000      
 1st Qu.:2006      
 Median :2011      
 Mean   :2012      
 3rd Qu.:2019      
 Max.   :2024      </code></pre>
</div>
</div>
<p>There are many fires! A lot of them are between 1981 and 2011, which is less relevant for our purposes, but that’s ok. Limited to between 2000-2030 (max is 2024 anyway), and there are 4139.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>intersects <span class="ot">=</span> <span class="fu">st_intersects</span>(or, iafp)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>iafp_or_int <span class="ot">=</span> iafp[<span class="fu">unlist</span>(intersects),]</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>iafp_or_int <span class="ot">&lt;-</span> iafp_or_int <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FIRE_YEAR_ <span class="sc">&gt;=</span> <span class="dv">2000</span>, FIRE_YEAR_ <span class="sc">&lt;=</span> <span class="dv">2030</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>iafp_or_int <span class="sc">%&gt;%</span> <span class="fu">filter</span>(FIRE_YEAR_ <span class="sc">==</span> <span class="dv">2020</span>) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_sf</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="shapefile-test_files/figure-html/IFPH%20in%20OR%20intersection-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lengths</span>(iafp_or_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   IRWINID      FORID   INCIDENT  GIS_ACRES UNQE_FIRE_   DATE_CUR FIRE_YEAR_ 
      4262       4262       4262       4262       4262       4262       4262 
   UNIT_ID POO_RESP_I  LOCAL_NUM FEATURE_CA MAP_METHOD   COMMENTS     GEO_ID 
      4262       4262       4262       4262       4262       4262       4262 
    SOURCE     AGENCY  FIRE_YEAR   GlobalID   geometry 
      4262       4262       4262       4262       4262 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop_na</span>(<span class="fu">as.data.frame</span>(iafp_or<span class="sc">$</span>FIRE_YEAR_)) <span class="sc">%&gt;%</span> summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> iafp_or$FIRE_YEAR_
 Min.   :2000      
 1st Qu.:2006      
 Median :2011      
 Mean   :2012      
 3rd Qu.:2019      
 Max.   :2024      </code></pre>
</div>
</div>
<p>This version includes slightly more fires, as it includes those that intersect but are not entirely contained within Oregon’s border. We’ll have to decide on our operational definitions for what cells contain fire/Indigenous land.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>