---
title: "Time grid eda"
author: "Spencer Fiden"
date: "2026-07-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(ggplot2)
library(dplyr)
library(zoo)
```

```{r}
tg <- st_read("../DATA-510/time_grid/time_grid.shp")
tgdf <- read_csv("data/processed_grid/time_grid.csv")
```

```{r}
names(tgdf)
```

```{r}
tgdf <- tgdf %>%
    mutate(prev_rx = rx_csum - n_rx)

tgdf <- tgdf %>%
    mutate(size_class = factor(sz_clss, levels=c("No fire", "Class A", "Class B", "Class C", "Class D", "Class E", "Class F", "Class G"))) %>%
    mutate(size_class_pretty = recode(size_class, `Class A`="A", `Class B`="B", `Class C`="C", `Class D`="D", `Class E`="E", `Class F`="F", `Class G`="G"))

tgdf %>%
    # filter((n_rx > 0) | (prev_rx > 0) | (rx_csum > 0)) %>%
    select(index, year, n_rx, prev_rx, rx_csum, max_acres) %>%
    arrange(index) %>%
    filter(year==2023, prev_rx>0)

```

Primary question: differences between wildfires in grid cells that have had previous RX burns vs those that have not.

```{r}
tgdf %>%
    group_by(index) %>% 
    mutate(
        had_rx = rx_csum > 0,
        has_plant = plnt_sm > 0
    ) %>%
    group_by(has_plant, had_rx, year) %>%
    summarize(
        mean_acres = mean(max_acres, na.rm=TRUE),
        mean_dur = mean(max_duration, na.rm=TRUE),
        n = n()
    ) %>%
    arrange(year) %>%
    print(n=Inf)

tgdf %>%
    group_by(index) %>% 
    mutate(
        had_rx = rx_rollsum > 0,
        rx_lim = ifelse(rx_rollsum > 2, 3, rx_rollsum),
        has_plant = plnt_sm > 0
    ) %>%
    group_by(has_plant, rx_lim, year) %>%
    summarize(
        mean_acres = mean(max_acres, na.rm=TRUE),
        mean_dur = mean(max_duration, na.rm=TRUE),
        n = n()
    ) %>%
    arrange(year) %>%
    print(n=Inf)

```


```{r}
tgdf %>%
    group_by(index) %>% 
    mutate(
        had_rx = rx_csum > 0,
        has_plant = plnt_sm > 0
    ) %>%
    ggplot(aes(x=year, y=max_acres, color=had_rx)) +
    geom_point() +
    facet_wrap(~had_rx)

# i think there's something here but it's hard to evaluate
tgdf %>%
    group_by(index) %>% 
    mutate(
        had_rx = rx_csum > 0,
        has_plant = plnt_sm > 0
    ) %>%
    filter(year>2020) %>%
    ggplot(aes(x=max_acres, fill=had_rx)) +
    geom_density(alpha=0.4) +
    scale_x_log10() +
    facet_wrap(~year)

tgdf %>%
    group_by(index) %>% 
    mutate(had_rx = prev_rx > 0) %>%
    filter(year>2020) %>%
    ggplot(aes(x=max_acres, fill=had_rx)) +
    geom_density(alpha=0.4) +
    scale_x_log10() +
    facet_wrap(~year)

# note: fires don't appear for 2023 because they've mostly got 0 acres, which is removed by the log transformation

```


```{r}
tgdf %>%
    group_by(index) %>% 
    mutate(rx_csum = cumsum(n_rx)) %>%
    mutate(
        had_rx = rx_csum > 0,
        has_plant = plnt_sm > 0
    ) %>%
    filter(year>2020) %>%
    ggplot(aes(y=max_acres, fill=had_rx)) +
    geom_boxplot() +
    facet_grid(year~had_rx) +
    scale_y_log10(labels = scales::label_log(digits=2)) +
    theme_bw()

```

```{r}
size_by_rx_ind <- tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    group_by(had_rx, is_ndgn, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, is_ndgn, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) 
    
size_by_rx_ind %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge", show.legend=FALSE) +
    facet_grid(is_ndgn~year) +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum fire size class",
        y="Percent of fires",
        title="Fire size distribution by presence of prescribed burn and whether \nfederally recognized Indigenous land"
    )
```

```{r}
tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    group_by(had_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge", show.legend=FALSE) +
    facet_grid(~year) +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum fire size class",
        y="Percent of fires",
        title="Fire size distribution by presence of prescribed burn and whether \nfederally recognized Indigenous land"
    )
```


```{r}
tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    group_by(had_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge", show.legend=FALSE) +
    facet_grid(~year) +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum fire size class",
        y="Percent of fires",
        title="Fire size distribution by presence of prescribed burn and whether \nfederally recognized Indigenous land"
    )
```


```{r}
fire_size_class_pct_prev_rx <- tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    group_by(had_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    #filter(size_class_pretty != "No fire") %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge", show.legend=FALSE) +
    facet_grid(~year) +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum fire size class",
        y="Percent of fires",
        title="Fire size distribution by presence of prescribed burn and whether federally recognized Indigenous land"
    )

ggsave("images/fire_size_class_pct_prev_rx.jpeg", fire_size_class_pct_prev_rx)
```


```{r}
# fire size distribution by previous prescribed burn, not including "no fire"
burn_cols <- c(
    "Previous prescribed burns" = "darkslategray", 
    "No previous prescribed burns" = "sienna1"
)

fire_size_class_pct_prev_rx_fire <- tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    group_by(had_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge") +
    facet_grid(~year) +
    scale_y_continuous(labels=scales::percent) +
    scale_fill_manual(values=burn_cols) +
    labs(
        x="Maximum fire size class",
        y="Percent of cells (with/without prescribed burns)",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        #subtitle='"No fire" class not shown',
        caption="Source: NIFC InFORM, IFPH"
    ) +
    theme_minimal() +
    theme(legend.position="top")
```

```{r}
# time series version that is very bad!
tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    group_by(had_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    ggplot(aes(year, pct_sz, color=had_rx)) +
    geom_line(linewidth=1) +
    geom_point() +
    facet_wrap(~size_class_pretty) +
    scale_y_continuous(labels=scales::percent) +
    scale_color_manual(values=burn_cols) +
    labs(
        x="Maximum fire size class",
        y="Percent of cells (with/without prescribed burns)",
        title="Fire size distribution by presence of prescribed burn",
        fill=""
    ) +
    theme_minimal() +
    theme(legend.position="top")
```

```{r}
tgdf %>%
    filter(year > 2020) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    group_by(has_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(has_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=has_rx)) +
    geom_col(color="white", position="dodge", show.legend=FALSE) +
    facet_grid(~year) +
    scale_y_continuous(labels=scales::percent) +
    theme_minimal() +
    labs(
        x="Maximum fire size class",
        y="Percent of fires",
        title="Fire size distribution by presence of prescribed burn and whether federally recognized Indigenous land"
    )
```


```{r}
burn_cols <- c(
    "Previous prescribed burns" = "darkslategray", 
    "No previous prescribed burns" = "sienna1"
)

tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous"), 
        size_class_lim = fct_collapse(size_class_pretty, `C-E` = c("C", "D", "E"))
    ) %>%
    filter(size_class_lim != "No fire") %>%
    group_by(had_rx, size_class_lim, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(size_class_lim, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge") +
    facet_grid(~year) +
    scale_y_continuous(labels=scales::percent) +
    scale_fill_manual(values=burn_cols) +
    labs(
        x="Maximum fire size class",
        y="Percent of cells (with/without prescribed burns)",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        #subtitle='"No fire" class not shown',
        caption='Source: InFORM, IFPH\n"No fire" class not included in totals.'
    ) +
    theme_bw() +
    theme(legend.position="top")

only_fires_size_prev_rx <- tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    group_by(had_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge") +
    facet_grid(~year) +
    scale_y_continuous(labels=scales::percent) +
    scale_fill_manual(values=burn_cols) +
    labs(
        x="Maximum fire size class",
        y="Percent of fires in cells with/without prescribed burns",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        #subtitle='"No fire" class not shown',
        caption='Source: InFORM, IFPH\nCells without wildfires in a given year not included in totals.'
    ) +
    theme_bw() +
    theme(legend.position="top")

only_fires_size_prev_rx
ggsave("images/only_fires_size_prev_rx.jpeg", only_fires_size_prev_rx, width=6, height=5)

```

```{r}
only_fires_ind_size_prev_rx <- tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    group_by(had_rx, size_class_pretty, is_ndgn) %>%
    summarize(n=n()) %>%
    group_by(had_rx, is_ndgn) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge") +
    facet_grid(is_ndgn~had_rx) +
    scale_y_continuous(labels=scales::percent) +
    scale_fill_manual(values=burn_cols) +
    labs(
        x="Maximum fire size class",
        y="Percent of fires in cells with/without prescribed burns",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        #subtitle='"No fire" class not shown',
        caption='Source: InFORM, IFPH\nCells without wildfires in a given year not included in totals.'
    ) +
    theme_bw() +
    theme(legend.position="top")

```


```{r}
tgdf_rx_ndgn <- tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    group_by(had_rx, size_class_pretty, is_ndgn) %>%
    summarize(n=n()) %>%
    group_by(had_rx, is_ndgn) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    )

labels_df = tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    group_by(had_rx, is_ndgn) %>%
    summarize(label=n())

only_fires_ind_size_prev_rx <- tgdf_rx_ndgn %>%
    ggplot(aes(size_class_pretty, pct_sz, fill=had_rx)) +
    geom_col(color="white", position="dodge") +
    facet_grid(is_ndgn~had_rx) +
    scale_y_continuous(labels=scales::percent) +
    scale_fill_manual(values=burn_cols) +
    labs(
        x="Maximum fire size class",
        y="Percent of fires in cells with/without prescribed burns",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        #subtitle='"No fire" class not shown',
        caption='Source: InFORM, IFPH\nCells without wildfires in a given year not included in totals.'
    ) +
    theme_bw() +
    theme(legend.position="top") + 
    geom_text(data = labels_df, size = 3,
        mapping = aes(x = Inf, y = Inf, label = paste("n =", label), hjust = 1.2, vjust = 2)
    )

only_fires_ind_size_prev_rx

ggsave("images/only_fires_ind_size_prev_rx.jpeg", only_fires_ind_size_prev_rx, width=6, height=5)
```

Attempts at a better version of the faceted plot (unsuccessful).

```{r}
tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        has_rx = ifelse(rx_csum > 0, "Prescribed burns", "No prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    filter(size_class_pretty != "No fire") %>%
    group_by(had_rx, size_class_pretty, year) %>%
    summarize(n=n()) %>%
    group_by(had_rx, year) %>%
    mutate(
        total = sum(n),
        pct_sz = n/total
    ) %>%
    ggplot(aes(year, pct_sz, color=size_class_pretty)) +
    #geom_col(color="white", position="dodge") +
    geom_line(linewidth=2) +
    facet_grid(~had_rx) +
    scale_y_continuous(labels=scales::percent) +
    scale_color_viridis_d(option='inferno') +
    # scale_fill_manual(values=burn_cols) +
    labs(
        x="Maximum fire size class",
        y="Percent of fires in cells with/without prescribed burns",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        caption='Source: InFORM, IFPH\nCells without wildfires in a given year not included in totals.'
    ) +
    theme_bw() +
    theme(legend.position="top")
```

```{r}
tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    # filter(size_class_pretty != "No fire") %>%
    filter(max_acres > 0) %>%
    group_by(had_rx, year) %>%
    summarize(
        n=n(),
        q1_acres = quantile(max_acres, 0.25),
        med_max_acres = median(max_acres),
        q3_acres = quantile(max_acres, 0.75),

    ) %>%
    ggplot(aes(year, med_max_acres, color=had_rx, fill=had_rx)) +
    geom_line(linewidth=2) +
    geom_line(aes(y=q1_acres)) +
    geom_line(aes(y=q3_acres)) +
    geom_ribbon(aes(ymin=q1_acres, ymax=q3_acres), alpha=0.3, show.legend=FALSE) +
    scale_y_log10() +
    scale_color_manual(values=burn_cols) +
    scale_fill_manual(values=burn_cols) +
    labs(
        y="Median maximum fire size (acres)",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        caption='Source: InFORM, IFPH\nCells without wildfires in a given year not included in totals.',
        color=""
    ) +
    theme_bw() +
    theme(legend.position="top")

tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    filter(max_acres > 0) %>%
    ggplot(aes(max_acres, fill=had_rx)) +
    geom_boxplot() +
    coord_flip() +
    facet_grid(~year) +
    scale_x_log10(labels=scales::comma) +
    scale_fill_manual(values=burn_cols) +
    labs(
        x="Fire size (acres)",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        caption='Source: InFORM, IFPH\nCells without wildfires in a given year not included in totals.'
    ) +
    theme_bw() +
    theme(
        legend.position="top"
    )

tgdf %>%
    filter(year > 2021) %>%
    mutate(
        had_rx = ifelse(prev_rx > 0, "Previous prescribed burns", "No previous prescribed burns"),
        is_ndgn = ifelse(is_ndgn==1, "Indigenous", "Not Indigenous")
    ) %>%
    filter(max_acres > 0.25) %>%
    ggplot(aes(max_acres, fill=had_rx)) +
    geom_boxplot() +
    coord_flip() +
    facet_grid(~year) +
    scale_x_continuous(transform=scales::pseudo_log_trans(base = 10), labels=scales::comma) +
    scale_fill_manual(values=burn_cols) +
    labs(
        x="Fire size (acres)",
        title="Fire size distribution by presence of prescribed burn",
        fill="",
        caption='Source: InFORM, IFPH\nCells without wildfires in a given year not included in totals.'
    ) +
    theme_bw() +
    theme(
        legend.position="top"
    )

```