# Random Forest Classifier pt 2

```{python}
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
```

```{python}
# more libraries
# %pip install scikit-learn
# %pip install xgboost
# %pip install xgboost --no-binary xgboost -v
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_classification
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold
)
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, precision_score
from sklearn.metrics import roc_auc_score

```

```{python}
# %pip install shap
import shap
```

```{python}
# import data with pandas
tg = pd.read_csv("../data/processed_grid/time_grid.csv")
tg.head()
```

## DF and Size Class Creation

```{python}
tg['rx_prev'] = tg['rx_csum'] - tg['n_rx']
```

```{python}
# filtering to only cells with fire
tg_fire = tg[tg['n_fires']>0]
```

```{python}
labels = ['small', 'medium', 'large']
print(pd.qcut(x=tg_fire['max_acres'], q=3, retbins=True))
tg_fire['target'] = pd.qcut(x=tg_fire['max_acres'], q=3, labels=labels)
```

sizes: [(-0.001, 0.1] < (0.1, 3.83] < (3.83, 413715.0]]

```{python}
# filtering to only cells with fire
tg_f_cur = tg_fire[tg_fire['year']>=2020]
```

```{python}
print(pd.qcut(x=tg_f_cur['max_acres'], q=3, retbins=True))
tg_f_cur['target'] = pd.qcut(x=tg_f_cur['max_acres'], q=3, labels=labels)
```

sizes: [(-0.001, 0.1] < (0.1, 3.593] < (3.593, 413715.0]]

```{python}
class_labs = np.unique(tg_fire["size_class"])
```

# Models

## normal (all years)

```{python}
label_encoder = LabelEncoder()
target2 = label_encoder.fit_transform(tg_fire["size_class"])

data = tg_fire[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']]

X_train, X_test, y_train, y_test = train_test_split(
    data, target2, test_size=0.3, random_state=42, stratify=target2
)
```

```{python}
# Normal XGBoost
xgb = XGBClassifier(random_state=42)
xgb.fit(X_train, y_train)

pred = xgb.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, pred):.4f}")
```

Accuracy: 0.4749

### Feature Importance

```{python}
explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(data)

# calculate mean absolute SHAP values
shap_summary = np.abs(shap_values).mean(axis=0)

# list to store shap values for each feature
shap_summary_list = [np.mean(shap_summary[i]) for i in range(shap_summary.shape[0])]

# list of feature names
feature_names = ['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']

# dataframe using 1d list of SHAP values
shap_summary_df = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list})

print(shap_summary_df)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': xgb.feature_importances_})

print(feature_imp_df)
```

### Metrics

```{python}
n_labs2 = np.unique(target2)
n_labs = np.arange(0,3,1)

c_matrix = confusion_matrix(y_test, pred, labels=n_labs2)
print(c_matrix)
```

```{python}
sns.heatmap(c_matrix, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report = classification_report(y_test, pred, labels=n_labs2, target_names=class_labs)
print(report)
```

## 2020-2025

```{python}
target2_c = label_encoder.fit_transform(tg_f_cur["size_class"])

data_c = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']]

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    data_c, target2_c, test_size=0.3, random_state=42, stratify=target2_c
)
```

```{python}
# time limited XGBoost
xgb_c = XGBClassifier(random_state=42)
xgb_c.fit(X_train_c, y_train_c)

pred_c = xgb_c.predict(X_test_c)
print(f"Accuracy: {accuracy_score(y_test_c, pred_c):.4f}")
```

Accuracy: 0.4848

### Feature Importance

```{python}
explainer_c = shap.TreeExplainer(xgb_c)
shap_values_c = explainer_c.shap_values(data_c)

# calculate mean absolute SHAP values
shap_summary_c = np.abs(shap_values_c).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_c = [np.mean(shap_summary_c[i]) for i in range(shap_summary_c.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_c = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list_c})

print(shap_summary_df_c)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_c = pd.DataFrame({'Feature': feature_names, 'Gini Importance': xgb_c.feature_importances_})

print(feature_imp_df_c)
```

### Metrics

```{python}
c_matrix_c = confusion_matrix(y_test_c, pred_c, labels=n_labs2)
print(c_matrix_c)
```

```{python}
sns.heatmap(c_matrix_c, annot=True, fmt="d", cmap="Purples", xticklabels=class_labs, yticklabels=class_labs)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_c = classification_report(y_test_c, pred_c, labels=n_labs2, target_names=class_labs)
print(report_c)
```

# Models with new target (engineered, not original size class)

## normal (all years)

```{python}
target = label_encoder.fit_transform(tg_fire["target"])
data = tg_fire[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']]

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    data, target, test_size=0.3, random_state=42, stratify=target
)
```

```{python}
# Normal XGBoost
xgb_s = XGBClassifier(random_state=42)
xgb_s.fit(X_train_s, y_train_s)

pred_s = xgb_s.predict(X_test_s)
print(f"Accuracy: {accuracy_score(y_test_s, pred_s):.4f}")
```

Accuracy: 0.4365

### Feature Importance

```{python}
explainer_s = shap.TreeExplainer(xgb_s)
shap_values_s = explainer_s.shap_values(data)

# calculate mean absolute SHAP values
shap_summary_s = np.abs(shap_values_s).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_s = [np.mean(shap_summary_s[i]) for i in range(shap_summary_s.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_s = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list_s})

print(shap_summary_df_s)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_s = pd.DataFrame({'Feature': feature_names, 'Gini Importance': xgb_s.feature_importances_})

print(feature_imp_df_s)
```

### Metrics

```{python}
n_labs = np.unique(target)

c_matrix_s = confusion_matrix(y_test_s, pred_s, labels=n_labs)
print(c_matrix_s)
```

```{python}
sns.heatmap(c_matrix_s, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_s = classification_report(y_test_s, pred_s, labels=n_labs, target_names=labels)
print(report_s)
```

## 2020-2025

this one does overwrite the previous 2020-2025 one because i am sick of changing it lol

```{python}
target_c = label_encoder.fit_transform(tg_f_cur["target"])

data_c = tg_f_cur[['is_ndgn', 'plnt_sm', 'rx_prev', 'max_acres_rx']]

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    data_c, target_c, test_size=0.3, random_state=42, stratify=target_c
)
```

```{python}
# time limited XGBoost
xgb_c = XGBClassifier(random_state=42)
xgb_c.fit(X_train_c, y_train_c)

pred_c = xgb_c.predict(X_test_c)
print(f"Accuracy: {accuracy_score(y_test_c, pred_c):.4f}")
```

Accuracy: 0.4476

### Feature Importance

```{python}
explainer_c = shap.TreeExplainer(xgb_c)
shap_values_c = explainer_c.shap_values(data_c)

# calculate mean absolute SHAP values
shap_summary_c = np.abs(shap_values_c).mean(axis=0)

# list to store shap values for each feature
shap_summary_list_c = [np.mean(shap_summary_c[i]) for i in range(shap_summary_c.shape[0])]

# dataframe using 1d list of SHAP values
shap_summary_df_c = pd.DataFrame({'Feature': feature_names, 'SHAP values': shap_summary_list_c})

print(shap_summary_df_c)
```

Feature importance using Gini importance.

```{python}
# creating dataframe of gini importances
feature_imp_df_c = pd.DataFrame({'Feature': feature_names, 'Gini Importance': xgb_c.feature_importances_})

print(feature_imp_df_c)
```

### Metrics

```{python}
c_matrix_c = confusion_matrix(y_test_c, pred_c, labels=n_labs)
print(c_matrix_c)
```

```{python}
sns.heatmap(c_matrix_c, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()
```

```{python}
report_c = classification_report(y_test_c, pred_c, labels=n_labs, target_names=labels)
print(report_c)
```

# Tuning

```{python}
import optuna
optuna.logging.set_verbosity(optuna.logging.INFO)
```

```{python}
# with optuna tuning
# pulled from prof.cheng's code

def tune_xgboost_optuna(X_train, y_train, X_val, y_val, n_trials=100):
    """
    Professional XGBoost tuning with Optuna (Multi-class support)
    """
    def objective(trial):
        params = {
            'max_depth': trial.suggest_int('max_depth', 3, 10),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),

            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
            'n_estimators': trial.suggest_int('n_estimators', 60, 3000),

            'gamma': trial.suggest_float('gamma', 0, 5),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10, log=True),

            'subsample': trial.suggest_float('subsample', 0.5, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1.0),
            'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.3, 1.0),

            'random_state': 42,
            'eval_metric': 'mlogloss',
            'tree_method': 'hist',
            'early_stopping_rounds': 50,
        }

        model = XGBClassifier(**params)
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )

        y_proba = model.predict_proba(X_val)

        auc = roc_auc_score(y_val, y_proba, multi_class='ovr')

        return auc

    study = optuna.create_study(
        direction='maximize',
        study_name='xgboost_tuning',
        sampler=optuna.samplers.TPESampler(seed=42)
    )

    study.optimize(
        objective, n_trials=n_trials,
        show_progress_bar=True,
        callbacks=[
            lambda study, trial: print(
                f"  Trial {trial.number}: "
                f"AUC={trial.value:.4f}"
                if trial.number % 20 == 0 else None
            )
        ]
    )

    return study
```

## normal with new target (all years)

```{python}
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train_s, y_train_s, test_size=0.3, random_state=42
)
```

### tuning

```{python}
print("Tuning XGBoost with Optuna...")
print("=" * 55)
xgb_study = tune_xgboost_optuna(
    X_tr, y_tr, X_val, y_val, n_trials=100
)
print(f"\n Best XGBoost Parameters:")
print("=" * 50)
for key, value in xgb_study.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best AUC (with multiclass): {xgb_study.best_value:.4f}")
```

### testing 

```{python}
xgb_t = XGBClassifier(**xgb_study.best_params)
xgb_t.fit(X_train_s, y_train_s)
pred_t = xgb_t.predict(X_test_s)

print(f"Accuracy: {accuracy_score(pred_t, y_test_s):.4f}")
print(f"Old accuracy: {accuracy_score(pred_s, y_test_s):.4f}")
print(f"Precision: {precision_score(y_test_s, pred_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test_s, pred_s, average='weighted', zero_division=0.0):.4f}")
```

Accuracy: 0.4332
Old accuracy: 0.4365
Precision: 0.3666
Old precision: 0.3682

```{python}
c_matrix_t = confusion_matrix(y_test_s, pred_t, labels=n_labs)
print(f"Confusion matrix:\n{c_matrix_t}")
print("="*35)
print(f"Old confusion matrix:\n{c_matrix_s}")
```

```{python}
sns.heatmap(c_matrix_t, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_t = classification_report(y_test_s, pred_t, labels=n_labs, target_names=labels)
print(report_t)
```

```{python}
# creating dataframe of gini importances
feature_imp_df_t = pd.DataFrame({'Feature': feature_names, 'Gini Importance': xgb_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df_s}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_t}")
```

## 2020-2025 with new target (all years)

```{python}
X_tr_c, X_val_c, y_tr_c, y_val_c = train_test_split(
    X_train_c, y_train_c, test_size=0.3, random_state=42
)
```

### tuning

```{python}
print("Tuning XGBoost with Optuna...")
print("=" * 55)
xgb_study_c = tune_xgboost_optuna(
    X_tr_c, y_tr_c, X_val_c, y_val_c, n_trials=100
)
print(f"\n Best XGBoost Parameters:")
print("=" * 50)
for key, value in xgb_study_c.best_params.items():
    if isinstance(value, float):
        print(f"  {key}: {value:.6f}")
    else:
        print(f"  {key}: {value}")
print(f"\n  Best AUC (with multiclass): {xgb_study_c.best_value:.4f}")
```

### testing 

```{python}
xgb_c_t = XGBClassifier(**xgb_study_c.best_params)
xgb_c_t.fit(X_train_c, y_train_c)
pred_c_t = xgb_c_t.predict(X_test_c)

print(f"Accuracy: {accuracy_score(pred_c_t, y_test_c):.4f}")
print(f"Old accuracy: {accuracy_score(pred_c, y_test_c):.4f}")
print(f"Precision: {precision_score(y_test_c, pred_c_t, average='weighted', zero_division=0.0):.4f}")
print(f"Old precision: {precision_score(y_test_c, pred_c, average='weighted', zero_division=0.0):.4f}")
```

Accuracy: 0.4490
Old accuracy: 0.4476
Precision: 0.3359
Old precision: 0.4036

```{python}
c_matrix_c_t = confusion_matrix(y_test_c, pred_c_t, labels=n_labs)
print(f"Confusion matrix:\n{c_matrix_c_t}")
print("="*35)
print(f"Old confusion matrix:\n{c_matrix_c}")
```

```{python}
sns.heatmap(c_matrix_c_t, annot=True, fmt="d", cmap="Purples", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

```

```{python}
report_c_t = classification_report(y_test_c, pred_c_t, labels=n_labs, target_names=labels)
print(report_c_t)
```

```{python}
# creating dataframe of gini importances
feature_imp_df_c_t = pd.DataFrame({'Feature': feature_names, 'Gini Importance': xgb_c_t.feature_importances_})

print(f"Old feature importance:\n{feature_imp_df_c}")
print("="*35)
print(f"Trained feature importance:\n{feature_imp_df_c_t}")
```
