---
title: "GBIF quality check"
author: "Amaya Supancich-McCord"
date: "2026-06-26"
output: html_document
---

# Ingestion from download

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# importing libraries
library(tidyverse)
```

```{r}
gbif = read.csv("C://Users//amaya//Downloads//updated_gbif_data.csv")
```

# Number of Total Rows
```{r}
nrow(gbif) #25442
```

# Limiting to OR
```{r}
oregon_gbif <- gbif %>% 
  filter(stateProvince == "Oregon")
```
# Number of Total Oregon Rows
```{r}
nrow(oregon_gbif) #23571
```

```{r}
names(oregon_gbif)
summary(oregon_gbif)
```

```{r}
# gbifID
summary(is.na(oregon_gbif$gbifID)) # no missing values
class(oregon_gbif$gbifID) # numeric
length(unique(oregon_gbif$gbifID)) # 23571 unique values
```


```{r}
# datasetKey
summary(is.na(oregon_gbif$datasetKey)) # no missing values
class(oregon_gbif$datasetKey) # char
length(unique(oregon_gbif$datasetKey)) #29 unique values, interesting, may invite further analysis
```

```{r}
# occurrenceID
summary(is.na(oregon_gbif$occurrenceID)) #no missing values
class(oregon_gbif$occurrenceID) # character
length(unique(oregon_gbif$occurrenceID)) # 23571 unique values
```

```{r}
# kingdom
summary(is.na(oregon_gbif$kingdom)) #no missing values
class(oregon_gbif$kingdom) # char
length(unique(oregon_gbif$kingdom)) # 1 unique value, as expected ("Plantae")
```

```{r}
# phylum
summary(is.na(oregon_gbif$phylum)) #no missing values
class(oregon_gbif$phylum) # char
length(unique(oregon_gbif$phylum)) # 1 unique value, as expected ("Tracheophyta")
```

```{r}
# class
summary(is.na(oregon_gbif$class)) #no missing values
class(oregon_gbif$class) # char
length(unique(oregon_gbif$class)) # 3 unique values (Magnoliopsida", "Pinopsida", "Liliopsida")
```

```{r}
# order
summary(is.na(oregon_gbif$order)) #no missing values
class(oregon_gbif$order) # char
length(unique(oregon_gbif$order)) #6 unique values ("Fagales", "Cupressales", "Liliales", "Malpighiales", "Rosales", "Pinales" )
```

```{r}
# family
summary(is.na(oregon_gbif$family)) #no missing values
class(oregon_gbif$family) # char
length(unique(oregon_gbif$family)) #6 unique values ("Fagaceae", "Cupressaceae", "Melanthiaceae", "Salicaceae", "Rosaceae", "Pinaceae")
```

```{r}
# genus
summary(is.na(oregon_gbif$genus)) #no missing values
class(oregon_gbif$genus) # char
length(unique(oregon_gbif$genus)) # 7 unique, as expected ("Quercus", "Thuja", "Xerophyllum", "Populus", "Rubus", "Salix", "Pinus")
```

```{r}
# species
summary(is.na(oregon_gbif$species)) #no missing 
class(oregon_gbif$species) # char
length(unique(oregon_gbif$species)) # 7 unique, as expected ("Quercus garryana", "Thuja plicata", "Xerophyllum tenax", "Populus trichocarpa", "Rubus ursinus", "Salix scouleriana", "Pinus ponderosa")
```

```{r}
# infraspecificEpithet
summary(is.na(oregon_gbif$infraspecificEpithet)) # no missing
class(oregon_gbif$infraspecificEpithet) # char
length(unique(oregon_gbif$infraspecificEpithet)) #4 unique ("", "garryana", "ponderosa", "benthamiana")
```

```{r}
# taxonRank
summary(is.na(oregon_gbif$taxonRank)) # no missing
class(oregon_gbif$taxonRank) # char
length(unique(oregon_gbif$taxonRank)) #2 unique ("SPECIES" & "VARIETY")
```

```{r}
# scientificName
summary(is.na(oregon_gbif$scientificName)) # no missing
class(oregon_gbif$scientificName) # char
length(unique(oregon_gbif$scientificName)) #13 unique ("Quercus garryana Douglas ex Hook.", "Xerophyllum tenax (Pursh) Nutt.", "Thuja plicata Donn ex D.Don", "Populus trichocarpa Torr. & A.Gray ex Hook.", "Rubus ursinus Cham. & Schltdl.", "Quercus garryana var. garryana", "Pinus ponderosa var. ponderosa", "Salix scouleriana Barratt ex Hook.", "Salix scouleriana Barratt", "Pinus ponderosa var. benthamiana (Hartw.) Vasey", "Pinus washoensis Mason & Stockw.", "Quercus garryana var. breweri (Engelm.) Jeps.", "Quercus garryana var. fruticosa (Engelm.) Govaerts")
```

```{r}
# verbatimScientificName
summary(is.na(oregon_gbif$verbatimScientificName)) #no missing
class(oregon_gbif$verbatimScientificName) # char
length(unique(oregon_gbif$verbatimScientificName)) #19 unique ("Quercus garryana", "Xerophyllum tenax", "Thuja plicata", "Populus trichocarpa", "Rubus ursinus", "Quercus garryana garryana", "Pinus ponderosa var. ponderosa", "Salix scouleriana", "Pinus ponderosa ponderosa", "Pinus ponderosa benthamiana", "Quercus garryana var. garryana", "Pinus ponderosa var. benthamiana", "Pinus washoensis", "Thuja plicata Donn ex D. Don", "Quercus garryana var. breweri", "Quercus garryana breweri", "Pinus ponderosa  benthamiana", "Quercus garryana var. breweri (Engelm.) Wenzig", "Quercus garryana Douglas ex Hook. var. fruticosa (Engelm.) Govaerts")
```

```{r}
# verbatimScientificNameAuthorship
summary(is.na(oregon_gbif$verbatimScientificNameAuthorship)) # no missing
class(oregon_gbif$verbatimScientificNameAuthorship) # char
length(unique(oregon_gbif$verbatimScientificNameAuthorship)) #16 ("", "(Pursh) Nutt.", "Cham. & Schltdl.", "Donn ex D. Don", "Douglas ex Hook.", "Barratt ex Hook.", "T. & G.", "Cham. & Schlecht.", "(Hartw.) Vasey", "Torr. & A. Gray ex Hook.", Torr. & A. Gray", "H. Mason & Stockw.", "D. Don", "(Engelm.) Jeps.", "Torr. & A.Gray", "(Schltdl.) Cham.")
```

```{r}
# countryCode
summary(is.na(oregon_gbif$countryCode)) # no missing
class(oregon_gbif$countryCode) # char
length(unique(oregon_gbif$countryCode)) #1 unique, as expected (US)
```

```{r}
# locality
summary(is.na(oregon_gbif$locality)) # no missing
class(oregon_gbif$locality) # char
length(unique(oregon_gbif$locality)) #87 unique values (some values are "")
```

```{r}
# stateProvince
summary(is.na(oregon_gbif$stateProvince)) # no missing
class(oregon_gbif$stateProvince) # char
length(unique(oregon_gbif$stateProvince)) #1, as expected ("Oregon")
```

```{r}
# occurrenceStatus              
summary(is.na(oregon_gbif$occurrenceStatus)) #no missing
class(oregon_gbif$occurrenceStatus) # char
length(unique(oregon_gbif$occurrenceStatus)) #1 unique, as expected ("PRESENT")
```

```{r}
# individualCount              
summary(is.na(oregon_gbif$individualCountoccurrenceStatus)) #all missing
class(oregon_gbif$individualCount) # int
length(unique(oregon_gbif$individualCount)) #2 unique value ("NA" and "1")
# how can they all be missing, but there also be a value of "1"?
```

```{r}
# publishingOrgKey              
summary(is.na(oregon_gbif$publishingOrgKey)) # no missing
class(oregon_gbif$publishingOrgKey) # char
length(unique(oregon_gbif$publishingOrgKey)) #22 unique
```

```{r}
# decimalLatitude              
summary(is.na(oregon_gbif$decimalLatitude)) # no missing
class(oregon_gbif$decimalLatitude) # numeric
length(unique(oregon_gbif$decimalLatitude)) #22527 unique values, not a huge concern, but maybe make note of it
```

```{r}
# decimalLongitude              
summary(is.na(oregon_gbif$decimalLongitude)) # no missing
class(oregon_gbif$decimalLongitude) # numeric
length(unique(oregon_gbif$decimalLongitude)) #22545 unique values, not a huge concern, but maybe make note of it
```

```{r}
# coordinateUncertaintyInMeters              
summary(is.na(oregon_gbif$coordinateUncertaintyInMeters)) #3390 missing values, roughly 9.6% of total, but make note of the issue
class(oregon_gbif$coordinateUncertaintyInMeters) # int
length(unique(oregon_gbif$coordinateUncertaintyInMeters)) #1053 unique values
```

```{r}
# coordinatePrecision              
summary(is.na(oregon_gbif$coordinatePrecision)) #all missing
class(oregon_gbif$coordinatePrecision) # logical
length(unique(oregon_gbif$coordinatePrecision)) #1 unique value ("NA")
```

```{r}
# elevation              
summary(is.na(oregon_gbif$elevation)) #23490 missing
class(oregon_gbif$elevation) # int
length(unique(oregon_gbif$elevation)) #57 unique value, ("NA" & positive/negative int values)
```

```{r}
# elevationAccuracy              
summary(is.na(oregon_gbif$elevationAccuracy)) #23566 missing
class(oregon_gbif$elevationAccuracy) # numeric
length(unique(oregon_gbif$elevationelevationAccuracy)) #0 unique values (NULL)
```

```{r}
# depth              
summary(is.na(oregon_gbif$depth)) #all missing
class(oregon_gbif$depth) # logical
length(unique(oregon_gbif$depth)) #1 (NA)
```

```{r}
# depthAccuracy              
summary(is.na(oregon_gbif$depthAccuracy)) #all missing
class(oregon_gbif$depthAccuracy) # logical
length(unique(oregon_gbif$depthAccuracy)) #1 (NA)
```

```{r}
# eventDate              
summary(is.na(oregon_gbif$eventDate)) #no missing
class(oregon_gbif$eventDate) # char
length(unique(oregon_gbif$eventDate)) #23256 unique values
```

```{r}
# day              
summary(is.na(oregon_gbif$day)) #1 missing
class(oregon_gbif$day) # int
length(unique(oregon_gbif$day)) #32 unique (the unexpected value is "NA")
```

```{r}
# month             
summary(is.na(oregon_gbif$month)) #no missing
class(oregon_gbif$month) # int
length(unique(oregon_gbif$month)) #12 unique (that them months right there baby)
```

```{r}
# year             
summary(is.na(oregon_gbif$year)) #no missing
class(oregon_gbif$year) # int
length(unique(oregon_gbif$year)) #11 unique (2025 2021 2020 2023 2024 2017 2015 2018 2016 2022 2019)
```

```{r}
# taxonKey            
summary(is.na(oregon_gbif$taxonKey)) #no missing
class(oregon_gbif$taxonKey) # char
length(unique(oregon_gbif$taxonKey)) #12 unique
```

```{r}
# speciesKey            
summary(is.na(oregon_gbif$speciesKey)) #no missing
class(oregon_gbif$speciesKey) # char
length(unique(oregon_gbif$speciesKey)) #7 unique
```

```{r}
# basisOfRecord            
summary(is.na(oregon_gbif$basisOfRecord)) #no missing
class(oregon_gbif$basisOfRecord) # char
length(unique(oregon_gbif$basisOfRecord)) #3 unique (HUMAN_OBSERVATION", "PRESERVED_SPECIMEN", "LIVING_SPECIMEN")
```

```{r}
# institutionCode            
summary(is.na(oregon_gbif$institutionCode)) #no missing
class(oregon_gbif$institutionCode) # char
length(unique(oregon_gbif$institutionCode)) #29
```

```{r}
# collectionCode            
summary(is.na(oregon_gbif$collectionCode)) #no missing
class(oregon_gbif$collectionCode) # char
length(unique(oregon_gbif$collectionCode)) #12
```

```{r}
# catalogNumber           
summary(is.na(oregon_gbif$catalogNumber)) #no missing
class(oregon_gbif$catalogNumber) # char
length(unique(oregon_gbif$catalogNumber)) #23565 unique
```

```{r}
# recordNumber           
summary(is.na(oregon_gbif$recordNumber)) #no missing
class(oregon_gbif$recordNumber) # char
length(unique(oregon_gbif$recordNumber)) # 64 unique (one of the values is "")
```

```{r}
# identifiedBy           
summary(is.na(oregon_gbif$identifiedBy)) #no missing
class(oregon_gbif$identifiedBy) # char
length(unique(oregon_gbif$identifiedBy)) #3571 unique values
# human names, gotta remove these
```

```{r}
# dateIdentified           
summary(is.na(oregon_gbif$dateIdentified)) #no missing
class(oregon_gbif$dateIdentified) # char
length(unique(oregon_gbif$dateIdentified)) #16044
```

```{r}
# license           
summary(is.na(oregon_gbif$license)) #no missing
class(oregon_gbif$license) # char
length(unique(oregon_gbif$license)) #3 ("CC_BY_NC_4_0", "CC_BY_4_0", "CC0_1_0", "CC0")
```

```{r}
# rightsHolder           
summary(is.na(oregon_gbif$rightsHolder)) #no missing
class(oregon_gbif$rightsHolder) # char
length(unique(oregon_gbif$rightsHolder)) #4306 unique
```

```{r}
# recordedBy           
summary(is.na(oregon_gbif$recordedBy)) #no missing
class(oregon_gbif$recordedBy) # char
length(unique(oregon_gbif$recordedBy)) #4334 unique
```

```{r}
# typeStatus           
summary(is.na(oregon_gbif$typeStatus)) #all missing
class(oregon_gbif$typeStatus) # logical
length(unique(oregon_gbif$typeStatus)) #1 (NA)
```

```{r}
# establishmentMeans          
summary(is.na(oregon_gbif$establishmentMeans)) #no missing
class(oregon_gbif$establishmentMeans) # char
length(unique(oregon_gbif$establishmentMeans)) #2 unique ("", "uncertain")
```

```{r}
# lastInterpreted         
summary(is.na(oregon_gbif$lastInterpreted)) #no missing
class(oregon_gbif$lastInterpreteds) # "NULL"
length(unique(oregon_gbif$lastInterpreted)) #84 unique values
# whats up with this column
```

```{r}
# mediaType         
summary(is.na(oregon_gbif$mediaType)) #no missing
class(oregon_gbif$mediaType) # char
length(unique(oregon_gbif$mediaType)) #2 ("StillImage" "")
```

```{r}
# issue         
summary(is.na(oregon_gbif$issue)) #no missing
class(oregon_gbif$issue) # char
length(unique(oregon_gbif$issue)) #35
```


